// Code generated by internal/ast/storeexp/_gen (EXPERIMENT). DO NOT EDIT.

//go:build storeexp

package storeexp

import "github.com/microsoft/TypeScript/tsc/internal/ast"

// Convert builds a Store from a Pointer AST in post-order. It follows exactly
// the children that the Pointer ForEachChild visits, so JSDoc is not converted.
func Convert(file *ast.SourceFile, fileIndex uint32) *Store {
	c := &converter{b: NewBuilder(file.Text(), fileIndex)}
	c.node(file.AsNode())
	return c.b.Finish()
}

type converter struct {
	b     *Builder
	elems []NodeRef // stack of the elements of the lists under construction
}

func (c *converter) elements(pos, end int32, nodes []*ast.Node) uint32 {
	mark := len(c.elems)
	for _, n := range nodes {
		ref := NodeRef(c.node(n))
		c.elems = append(c.elems, ref)
	}
	at := c.b.List(pos, end, c.elems[mark:])
	c.elems = c.elems[:mark]
	return at
}

func (c *converter) list(l *ast.NodeList) uint32 {
	if l == nil {
		return 0
	}
	return c.elements(int32(l.Pos()), int32(l.End()), l.Nodes)
}

func (c *converter) modifiers(l *ast.ModifierList) uint32 {
	if l == nil {
		return 0
	}
	return c.list(&l.NodeList)
}

// A raw list has no Loc of its own.
func (c *converter) raw(nodes []*ast.Node) uint32 {
	if nodes == nil {
		return 0
	}
	return c.elements(0, 0, nodes)
}

func (c *converter) node(n *ast.Node) uint32 {
	if n == nil {
		return 0
	}
	pos, end := int32(n.Pos()), int32(n.End())
	switch n.Kind {
	case ast.KindIdentifier:
		return uint32(c.b.Identifier(n.Flags, pos, end, n.AsIdentifier().Text))
	case ast.KindQualifiedName:
		d := n.AsQualifiedName()
		slots := [...]uint32{
			c.node(d.Left),
			c.node(d.Right),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindComputedPropertyName:
		d := n.AsComputedPropertyName()
		slots := [...]uint32{
			c.node(d.Expression),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindTypeParameter:
		d := n.AsTypeParameterDeclaration()
		slots := [...]uint32{
			c.modifiers(d.Modifiers()),
			c.node(d.Name()),
			c.node(d.Constraint),
			c.node(d.Expression),
			c.node(d.DefaultType),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindParameter:
		d := n.AsParameterDeclaration()
		slots := [...]uint32{
			c.modifiers(d.Modifiers()),
			c.node(d.DotDotDotToken),
			c.node(d.Name()),
			c.node(d.QuestionToken),
			c.node(d.Type),
			c.node(d.Initializer),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindDecorator:
		d := n.AsDecorator()
		slots := [...]uint32{
			c.node(d.Expression),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindPropertySignature:
		d := n.AsPropertySignatureDeclaration()
		slots := [...]uint32{
			c.modifiers(d.Modifiers()),
			c.node(d.Name()),
			c.node(d.PostfixToken),
			c.node(d.Type),
			c.node(d.Initializer),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindPropertyDeclaration:
		d := n.AsPropertyDeclaration()
		slots := [...]uint32{
			c.modifiers(d.Modifiers()),
			c.node(d.Name()),
			c.node(d.PostfixToken),
			c.node(d.Type),
			c.node(d.Initializer),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindMethodSignature:
		d := n.AsMethodSignatureDeclaration()
		slots := [...]uint32{
			c.modifiers(d.Modifiers()),
			c.node(d.Name()),
			c.node(d.PostfixToken),
			c.list(d.TypeParameters),
			c.list(d.Parameters),
			c.node(d.Type),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindMethodDeclaration:
		d := n.AsMethodDeclaration()
		slots := [...]uint32{
			c.modifiers(d.Modifiers()),
			c.node(d.AsteriskToken),
			c.node(d.Name()),
			c.node(d.PostfixToken),
			c.list(d.TypeParameters),
			c.list(d.Parameters),
			c.node(d.Type),
			c.node(d.FullSignature),
			c.node(d.Body),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindClassStaticBlockDeclaration:
		d := n.AsClassStaticBlockDeclaration()
		slots := [...]uint32{
			c.modifiers(d.Modifiers()),
			c.node(d.Body),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindConstructor:
		d := n.AsConstructorDeclaration()
		slots := [...]uint32{
			c.modifiers(d.Modifiers()),
			c.list(d.TypeParameters),
			c.list(d.Parameters),
			c.node(d.Type),
			c.node(d.FullSignature),
			c.node(d.Body),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindGetAccessor:
		d := n.AsGetAccessorDeclaration()
		slots := [...]uint32{
			c.modifiers(d.Modifiers()),
			c.node(d.Name()),
			c.list(d.TypeParameters),
			c.list(d.Parameters),
			c.node(d.Type),
			c.node(d.FullSignature),
			c.node(d.Body),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindSetAccessor:
		d := n.AsSetAccessorDeclaration()
		slots := [...]uint32{
			c.modifiers(d.Modifiers()),
			c.node(d.Name()),
			c.list(d.TypeParameters),
			c.list(d.Parameters),
			c.node(d.Type),
			c.node(d.FullSignature),
			c.node(d.Body),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindCallSignature:
		d := n.AsCallSignatureDeclaration()
		slots := [...]uint32{
			c.list(d.TypeParameters),
			c.list(d.Parameters),
			c.node(d.Type),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindConstructSignature:
		d := n.AsConstructSignatureDeclaration()
		slots := [...]uint32{
			c.list(d.TypeParameters),
			c.list(d.Parameters),
			c.node(d.Type),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindIndexSignature:
		d := n.AsIndexSignatureDeclaration()
		slots := [...]uint32{
			c.modifiers(d.Modifiers()),
			c.list(d.Parameters),
			c.node(d.Type),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindTypePredicate:
		d := n.AsTypePredicateNode()
		slots := [...]uint32{
			c.node(d.AssertsModifier),
			c.node(d.ParameterName),
			c.node(d.Type),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindTypeReference:
		d := n.AsTypeReferenceNode()
		slots := [...]uint32{
			c.node(d.TypeName),
			c.list(d.TypeArguments),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindFunctionType:
		d := n.AsFunctionTypeNode()
		slots := [...]uint32{
			c.list(d.TypeParameters),
			c.list(d.Parameters),
			c.node(d.Type),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindConstructorType:
		d := n.AsConstructorTypeNode()
		slots := [...]uint32{
			c.modifiers(d.Modifiers()),
			c.list(d.TypeParameters),
			c.list(d.Parameters),
			c.node(d.Type),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindTypeQuery:
		d := n.AsTypeQueryNode()
		slots := [...]uint32{
			c.node(d.ExprName),
			c.list(d.TypeArguments),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindTypeLiteral:
		d := n.AsTypeLiteralNode()
		slots := [...]uint32{
			c.list(d.Members),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindArrayType:
		d := n.AsArrayTypeNode()
		slots := [...]uint32{
			c.node(d.ElementType),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindTupleType:
		d := n.AsTupleTypeNode()
		slots := [...]uint32{
			c.list(d.Elements),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindOptionalType:
		d := n.AsOptionalTypeNode()
		slots := [...]uint32{
			c.node(d.Type),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindRestType:
		d := n.AsRestTypeNode()
		slots := [...]uint32{
			c.node(d.Type),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindUnionType:
		d := n.AsUnionTypeNode()
		slots := [...]uint32{
			c.list(d.Types),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindIntersectionType:
		d := n.AsIntersectionTypeNode()
		slots := [...]uint32{
			c.list(d.Types),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindConditionalType:
		d := n.AsConditionalTypeNode()
		slots := [...]uint32{
			c.node(d.CheckType),
			c.node(d.ExtendsType),
			c.node(d.TrueType),
			c.node(d.FalseType),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindInferType:
		d := n.AsInferTypeNode()
		slots := [...]uint32{
			c.node(d.TypeParameter),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindParenthesizedType:
		d := n.AsParenthesizedTypeNode()
		slots := [...]uint32{
			c.node(d.Type),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindTypeOperator:
		d := n.AsTypeOperatorNode()
		slots := [...]uint32{
			c.node(d.Type),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindIndexedAccessType:
		d := n.AsIndexedAccessTypeNode()
		slots := [...]uint32{
			c.node(d.ObjectType),
			c.node(d.IndexType),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindMappedType:
		d := n.AsMappedTypeNode()
		slots := [...]uint32{
			c.node(d.ReadonlyToken),
			c.node(d.TypeParameter),
			c.node(d.NameType),
			c.node(d.QuestionToken),
			c.node(d.Type),
			c.list(d.Members),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindLiteralType:
		d := n.AsLiteralTypeNode()
		slots := [...]uint32{
			c.node(d.Literal),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindNamedTupleMember:
		d := n.AsNamedTupleMember()
		slots := [...]uint32{
			c.node(d.DotDotDotToken),
			c.node(d.Name()),
			c.node(d.QuestionToken),
			c.node(d.Type),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindTemplateLiteralType:
		d := n.AsTemplateLiteralTypeNode()
		slots := [...]uint32{
			c.node(d.Head),
			c.list(d.TemplateSpans),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindTemplateLiteralTypeSpan:
		d := n.AsTemplateLiteralTypeSpan()
		slots := [...]uint32{
			c.node(d.Type),
			c.node(d.Literal),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindImportType:
		d := n.AsImportTypeNode()
		slots := [...]uint32{
			c.node(d.Argument),
			c.node(d.Attributes),
			c.node(d.Qualifier),
			c.list(d.TypeArguments),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindObjectBindingPattern, ast.KindArrayBindingPattern:
		d := n.AsBindingPattern()
		slots := [...]uint32{
			c.list(d.Elements),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindBindingElement:
		d := n.AsBindingElement()
		slots := [...]uint32{
			c.node(d.DotDotDotToken),
			c.node(d.PropertyName),
			c.node(d.Name()),
			c.node(d.Initializer),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindArrayLiteralExpression:
		d := n.AsArrayLiteralExpression()
		slots := [...]uint32{
			c.list(d.Elements),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindObjectLiteralExpression:
		d := n.AsObjectLiteralExpression()
		slots := [...]uint32{
			c.list(d.Properties),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindPropertyAccessExpression:
		d := n.AsPropertyAccessExpression()
		slots := [...]uint32{
			c.node(d.Expression),
			c.node(d.QuestionDotToken),
			c.node(d.Name()),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindElementAccessExpression:
		d := n.AsElementAccessExpression()
		slots := [...]uint32{
			c.node(d.Expression),
			c.node(d.QuestionDotToken),
			c.node(d.ArgumentExpression),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindCallExpression:
		d := n.AsCallExpression()
		slots := [...]uint32{
			c.node(d.Expression),
			c.node(d.QuestionDotToken),
			c.list(d.TypeArguments),
			c.list(d.Arguments),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindNewExpression:
		d := n.AsNewExpression()
		slots := [...]uint32{
			c.node(d.Expression),
			c.list(d.TypeArguments),
			c.list(d.Arguments),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindTaggedTemplateExpression:
		d := n.AsTaggedTemplateExpression()
		slots := [...]uint32{
			c.node(d.Tag),
			c.node(d.QuestionDotToken),
			c.list(d.TypeArguments),
			c.node(d.Template),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindTypeAssertionExpression:
		d := n.AsTypeAssertion()
		slots := [...]uint32{
			c.node(d.Type),
			c.node(d.Expression),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindParenthesizedExpression:
		d := n.AsParenthesizedExpression()
		slots := [...]uint32{
			c.node(d.Expression),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindFunctionExpression:
		d := n.AsFunctionExpression()
		slots := [...]uint32{
			c.modifiers(d.Modifiers()),
			c.node(d.AsteriskToken),
			c.node(d.Name()),
			c.list(d.TypeParameters),
			c.list(d.Parameters),
			c.node(d.Type),
			c.node(d.FullSignature),
			c.node(d.Body),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindArrowFunction:
		d := n.AsArrowFunction()
		slots := [...]uint32{
			c.modifiers(d.Modifiers()),
			c.list(d.TypeParameters),
			c.list(d.Parameters),
			c.node(d.Type),
			c.node(d.FullSignature),
			c.node(d.EqualsGreaterThanToken),
			c.node(d.Body),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindDeleteExpression:
		d := n.AsDeleteExpression()
		slots := [...]uint32{
			c.node(d.Expression),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindTypeOfExpression:
		d := n.AsTypeOfExpression()
		slots := [...]uint32{
			c.node(d.Expression),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindVoidExpression:
		d := n.AsVoidExpression()
		slots := [...]uint32{
			c.node(d.Expression),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindAwaitExpression:
		d := n.AsAwaitExpression()
		slots := [...]uint32{
			c.node(d.Expression),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindPrefixUnaryExpression:
		d := n.AsPrefixUnaryExpression()
		slots := [...]uint32{
			c.node(d.Operand),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindPostfixUnaryExpression:
		d := n.AsPostfixUnaryExpression()
		slots := [...]uint32{
			c.node(d.Operand),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindBinaryExpression:
		d := n.AsBinaryExpression()
		slots := [...]uint32{
			c.modifiers(d.Modifiers()),
			c.node(d.Left),
			c.node(d.Type),
			c.node(d.OperatorToken),
			c.node(d.Right),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindConditionalExpression:
		d := n.AsConditionalExpression()
		slots := [...]uint32{
			c.node(d.Condition),
			c.node(d.QuestionToken),
			c.node(d.WhenTrue),
			c.node(d.ColonToken),
			c.node(d.WhenFalse),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindTemplateExpression:
		d := n.AsTemplateExpression()
		slots := [...]uint32{
			c.node(d.Head),
			c.list(d.TemplateSpans),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindYieldExpression:
		d := n.AsYieldExpression()
		slots := [...]uint32{
			c.node(d.AsteriskToken),
			c.node(d.Expression),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindSpreadElement:
		d := n.AsSpreadElement()
		slots := [...]uint32{
			c.node(d.Expression),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindClassExpression:
		d := n.AsClassExpression()
		slots := [...]uint32{
			c.modifiers(d.Modifiers()),
			c.node(d.Name()),
			c.list(d.TypeParameters),
			c.list(d.HeritageClauses),
			c.list(d.Members),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindExpressionWithTypeArguments:
		d := n.AsExpressionWithTypeArguments()
		slots := [...]uint32{
			c.node(d.Expression),
			c.list(d.TypeArguments),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindAsExpression:
		d := n.AsAsExpression()
		slots := [...]uint32{
			c.node(d.Expression),
			c.node(d.Type),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindNonNullExpression:
		d := n.AsNonNullExpression()
		slots := [...]uint32{
			c.node(d.Expression),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindMetaProperty:
		d := n.AsMetaProperty()
		slots := [...]uint32{
			c.node(d.Name()),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindSyntheticExpression:
		d := n.AsSyntheticExpression()
		slots := [...]uint32{
			c.node(d.TupleNameSource),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindSatisfiesExpression:
		d := n.AsSatisfiesExpression()
		slots := [...]uint32{
			c.node(d.Expression),
			c.node(d.Type),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindTemplateSpan:
		d := n.AsTemplateSpan()
		slots := [...]uint32{
			c.node(d.Expression),
			c.node(d.Literal),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindBlock:
		d := n.AsBlock()
		slots := [...]uint32{
			c.list(d.Statements),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindVariableStatement:
		d := n.AsVariableStatement()
		slots := [...]uint32{
			c.modifiers(d.Modifiers()),
			c.node(d.DeclarationList),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindExpressionStatement:
		d := n.AsExpressionStatement()
		slots := [...]uint32{
			c.node(d.Expression),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindIfStatement:
		d := n.AsIfStatement()
		slots := [...]uint32{
			c.node(d.Expression),
			c.node(d.ThenStatement),
			c.node(d.ElseStatement),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindDoStatement:
		d := n.AsDoStatement()
		slots := [...]uint32{
			c.node(d.Statement),
			c.node(d.Expression),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindWhileStatement:
		d := n.AsWhileStatement()
		slots := [...]uint32{
			c.node(d.Expression),
			c.node(d.Statement),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindForStatement:
		d := n.AsForStatement()
		slots := [...]uint32{
			c.node(d.Initializer),
			c.node(d.Condition),
			c.node(d.Incrementor),
			c.node(d.Statement),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindForInStatement, ast.KindForOfStatement:
		d := n.AsForInOrOfStatement()
		slots := [...]uint32{
			c.node(d.AwaitModifier),
			c.node(d.Initializer),
			c.node(d.Expression),
			c.node(d.Statement),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindContinueStatement:
		d := n.AsContinueStatement()
		slots := [...]uint32{
			c.node(d.Label),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindBreakStatement:
		d := n.AsBreakStatement()
		slots := [...]uint32{
			c.node(d.Label),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindReturnStatement:
		d := n.AsReturnStatement()
		slots := [...]uint32{
			c.node(d.Expression),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindWithStatement:
		d := n.AsWithStatement()
		slots := [...]uint32{
			c.node(d.Expression),
			c.node(d.Statement),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindSwitchStatement:
		d := n.AsSwitchStatement()
		slots := [...]uint32{
			c.node(d.Expression),
			c.node(d.CaseBlock),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindLabeledStatement:
		d := n.AsLabeledStatement()
		slots := [...]uint32{
			c.node(d.Label),
			c.node(d.Statement),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindThrowStatement:
		d := n.AsThrowStatement()
		slots := [...]uint32{
			c.node(d.Expression),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindTryStatement:
		d := n.AsTryStatement()
		slots := [...]uint32{
			c.node(d.TryBlock),
			c.node(d.CatchClause),
			c.node(d.FinallyBlock),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindVariableDeclaration:
		d := n.AsVariableDeclaration()
		slots := [...]uint32{
			c.node(d.Name()),
			c.node(d.ExclamationToken),
			c.node(d.Type),
			c.node(d.Initializer),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindVariableDeclarationList:
		d := n.AsVariableDeclarationList()
		slots := [...]uint32{
			c.list(d.Declarations),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindFunctionDeclaration:
		d := n.AsFunctionDeclaration()
		slots := [...]uint32{
			c.modifiers(d.Modifiers()),
			c.node(d.AsteriskToken),
			c.node(d.Name()),
			c.list(d.TypeParameters),
			c.list(d.Parameters),
			c.node(d.Type),
			c.node(d.FullSignature),
			c.node(d.Body),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindClassDeclaration:
		d := n.AsClassDeclaration()
		slots := [...]uint32{
			c.modifiers(d.Modifiers()),
			c.node(d.Name()),
			c.list(d.TypeParameters),
			c.list(d.HeritageClauses),
			c.list(d.Members),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindInterfaceDeclaration:
		d := n.AsInterfaceDeclaration()
		slots := [...]uint32{
			c.modifiers(d.Modifiers()),
			c.node(d.Name()),
			c.list(d.TypeParameters),
			c.list(d.HeritageClauses),
			c.list(d.Members),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindTypeAliasDeclaration, ast.KindJSTypeAliasDeclaration:
		d := n.AsTypeAliasDeclaration()
		slots := [...]uint32{
			c.modifiers(d.Modifiers()),
			c.node(d.Name()),
			c.list(d.TypeParameters),
			c.node(d.Type),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindEnumDeclaration:
		d := n.AsEnumDeclaration()
		slots := [...]uint32{
			c.modifiers(d.Modifiers()),
			c.node(d.Name()),
			c.list(d.Members),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindModuleDeclaration:
		d := n.AsModuleDeclaration()
		slots := [...]uint32{
			c.modifiers(d.Modifiers()),
			c.node(d.Name()),
			c.node(d.Attributes),
			c.node(d.Body),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindModuleBlock:
		d := n.AsModuleBlock()
		slots := [...]uint32{
			c.list(d.Statements),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindCaseBlock:
		d := n.AsCaseBlock()
		slots := [...]uint32{
			c.list(d.Clauses),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindNamespaceExportDeclaration:
		d := n.AsNamespaceExportDeclaration()
		slots := [...]uint32{
			c.modifiers(d.Modifiers()),
			c.node(d.Name()),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindImportEqualsDeclaration:
		d := n.AsImportEqualsDeclaration()
		slots := [...]uint32{
			c.modifiers(d.Modifiers()),
			c.node(d.Name()),
			c.node(d.ModuleReference),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindImportDeclaration, ast.KindJSImportDeclaration:
		d := n.AsImportDeclaration()
		slots := [...]uint32{
			c.modifiers(d.Modifiers()),
			c.node(d.ImportClause),
			c.node(d.ModuleSpecifier),
			c.node(d.Attributes),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindImportClause:
		d := n.AsImportClause()
		slots := [...]uint32{
			c.node(d.Name()),
			c.node(d.NamedBindings),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindNamespaceImport:
		d := n.AsNamespaceImport()
		slots := [...]uint32{
			c.node(d.Name()),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindNamedImports:
		d := n.AsNamedImports()
		slots := [...]uint32{
			c.list(d.Elements),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindImportSpecifier:
		d := n.AsImportSpecifier()
		slots := [...]uint32{
			c.node(d.PropertyName),
			c.node(d.Name()),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindExportAssignment:
		d := n.AsExportAssignment()
		slots := [...]uint32{
			c.modifiers(d.Modifiers()),
			c.node(d.Type),
			c.node(d.Expression),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindExportDeclaration:
		d := n.AsExportDeclaration()
		slots := [...]uint32{
			c.modifiers(d.Modifiers()),
			c.node(d.ExportClause),
			c.node(d.ModuleSpecifier),
			c.node(d.Attributes),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindNamedExports:
		d := n.AsNamedExports()
		slots := [...]uint32{
			c.list(d.Elements),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindNamespaceExport:
		d := n.AsNamespaceExport()
		slots := [...]uint32{
			c.node(d.Name()),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindExportSpecifier:
		d := n.AsExportSpecifier()
		slots := [...]uint32{
			c.node(d.PropertyName),
			c.node(d.Name()),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindMissingDeclaration:
		d := n.AsMissingDeclaration()
		slots := [...]uint32{
			c.modifiers(d.Modifiers()),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindExternalModuleReference:
		d := n.AsExternalModuleReference()
		slots := [...]uint32{
			c.node(d.Expression),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJsxElement:
		d := n.AsJsxElement()
		slots := [...]uint32{
			c.node(d.OpeningElement),
			c.list(d.Children),
			c.node(d.ClosingElement),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJsxSelfClosingElement:
		d := n.AsJsxSelfClosingElement()
		slots := [...]uint32{
			c.node(d.TagName),
			c.list(d.TypeArguments),
			c.node(d.Attributes),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJsxOpeningElement:
		d := n.AsJsxOpeningElement()
		slots := [...]uint32{
			c.node(d.TagName),
			c.list(d.TypeArguments),
			c.node(d.Attributes),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJsxClosingElement:
		d := n.AsJsxClosingElement()
		slots := [...]uint32{
			c.node(d.TagName),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJsxFragment:
		d := n.AsJsxFragment()
		slots := [...]uint32{
			c.node(d.OpeningFragment),
			c.list(d.Children),
			c.node(d.ClosingFragment),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJsxAttribute:
		d := n.AsJsxAttribute()
		slots := [...]uint32{
			c.node(d.Name()),
			c.node(d.Initializer),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJsxAttributes:
		d := n.AsJsxAttributes()
		slots := [...]uint32{
			c.list(d.Properties),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJsxSpreadAttribute:
		d := n.AsJsxSpreadAttribute()
		slots := [...]uint32{
			c.node(d.Expression),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJsxExpression:
		d := n.AsJsxExpression()
		slots := [...]uint32{
			c.node(d.DotDotDotToken),
			c.node(d.Expression),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJsxNamespacedName:
		d := n.AsJsxNamespacedName()
		slots := [...]uint32{
			c.node(d.Namespace),
			c.node(d.Name()),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindCaseClause, ast.KindDefaultClause:
		d := n.AsCaseOrDefaultClause()
		slots := [...]uint32{
			c.node(d.Expression),
			c.list(d.Statements),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindHeritageClause:
		d := n.AsHeritageClause()
		slots := [...]uint32{
			c.list(d.Types),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindCatchClause:
		d := n.AsCatchClause()
		slots := [...]uint32{
			c.node(d.VariableDeclaration),
			c.node(d.Block),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindImportAttributes:
		d := n.AsImportAttributes()
		slots := [...]uint32{
			c.list(d.Attributes),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindImportAttribute:
		d := n.AsImportAttribute()
		slots := [...]uint32{
			c.node(d.Name()),
			c.node(d.Value),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindPropertyAssignment:
		d := n.AsPropertyAssignment()
		slots := [...]uint32{
			c.modifiers(d.Modifiers()),
			c.node(d.Name()),
			c.node(d.PostfixToken),
			c.node(d.Type),
			c.node(d.Initializer),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindShorthandPropertyAssignment:
		d := n.AsShorthandPropertyAssignment()
		slots := [...]uint32{
			c.modifiers(d.Modifiers()),
			c.node(d.Name()),
			c.node(d.PostfixToken),
			c.node(d.Type),
			c.node(d.EqualsToken),
			c.node(d.ObjectAssignmentInitializer),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindSpreadAssignment:
		d := n.AsSpreadAssignment()
		slots := [...]uint32{
			c.node(d.Expression),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindEnumMember:
		d := n.AsEnumMember()
		slots := [...]uint32{
			c.node(d.Name()),
			c.node(d.Initializer),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindSourceFile:
		d := n.AsSourceFile()
		slots := [...]uint32{
			c.list(d.Statements),
			c.node(d.EndOfFileToken),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJSDocTypeExpression:
		d := n.AsJSDocTypeExpression()
		slots := [...]uint32{
			c.node(d.Type),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJSDocNameReference:
		d := n.AsJSDocNameReference()
		slots := [...]uint32{
			c.node(d.Name()),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJSDocNullableType:
		d := n.AsJSDocNullableType()
		slots := [...]uint32{
			c.node(d.Type),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJSDocNonNullableType:
		d := n.AsJSDocNonNullableType()
		slots := [...]uint32{
			c.node(d.Type),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJSDocOptionalType:
		d := n.AsJSDocOptionalType()
		slots := [...]uint32{
			c.node(d.Type),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJSDocVariadicType:
		d := n.AsJSDocVariadicType()
		slots := [...]uint32{
			c.node(d.Type),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJSDoc:
		d := n.AsJSDoc()
		slots := [...]uint32{
			c.list(d.Comment),
			c.list(d.Tags),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJSDocTypeLiteral:
		d := n.AsJSDocTypeLiteral()
		slots := [...]uint32{
			c.raw(d.JSDocPropertyTags),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJSDocSignature:
		d := n.AsJSDocSignature()
		slots := [...]uint32{
			c.list(d.TypeParameters),
			c.list(d.Parameters),
			c.node(d.Type),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJSDocLink:
		d := n.AsJSDocLink()
		slots := [...]uint32{
			c.node(d.Name()),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJSDocLinkCode:
		d := n.AsJSDocLinkCode()
		slots := [...]uint32{
			c.node(d.Name()),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJSDocLinkPlain:
		d := n.AsJSDocLinkPlain()
		slots := [...]uint32{
			c.node(d.Name()),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJSDocUnknownTag:
		d := n.AsJSDocUnknownTag()
		slots := [...]uint32{
			c.node(d.TagName),
			c.list(d.Comment),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJSDocAugmentsTag:
		d := n.AsJSDocAugmentsTag()
		slots := [...]uint32{
			c.node(d.TagName),
			c.node(d.ClassName),
			c.list(d.Comment),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJSDocImplementsTag:
		d := n.AsJSDocImplementsTag()
		slots := [...]uint32{
			c.node(d.TagName),
			c.node(d.ClassName),
			c.list(d.Comment),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJSDocDeprecatedTag:
		d := n.AsJSDocDeprecatedTag()
		slots := [...]uint32{
			c.node(d.TagName),
			c.list(d.Comment),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJSDocPublicTag:
		d := n.AsJSDocPublicTag()
		slots := [...]uint32{
			c.node(d.TagName),
			c.list(d.Comment),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJSDocPrivateTag:
		d := n.AsJSDocPrivateTag()
		slots := [...]uint32{
			c.node(d.TagName),
			c.list(d.Comment),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJSDocProtectedTag:
		d := n.AsJSDocProtectedTag()
		slots := [...]uint32{
			c.node(d.TagName),
			c.list(d.Comment),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJSDocReadonlyTag:
		d := n.AsJSDocReadonlyTag()
		slots := [...]uint32{
			c.node(d.TagName),
			c.list(d.Comment),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJSDocOverrideTag:
		d := n.AsJSDocOverrideTag()
		slots := [...]uint32{
			c.node(d.TagName),
			c.list(d.Comment),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJSDocCallbackTag:
		d := n.AsJSDocCallbackTag()
		slots := [...]uint32{
			c.node(d.TagName),
			c.node(d.TypeExpression),
			c.node(d.Name()),
			c.list(d.Comment),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJSDocOverloadTag:
		d := n.AsJSDocOverloadTag()
		slots := [...]uint32{
			c.node(d.TagName),
			c.node(d.TypeExpression),
			c.list(d.Comment),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJSDocParameterTag, ast.KindJSDocPropertyTag:
		d := n.AsJSDocParameterOrPropertyTag()
		slots := [...]uint32{
			c.node(d.TagName),
			c.node(d.Name()),
			c.node(d.TypeExpression),
			c.list(d.Comment),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJSDocReturnTag:
		d := n.AsJSDocReturnTag()
		slots := [...]uint32{
			c.node(d.TagName),
			c.node(d.TypeExpression),
			c.list(d.Comment),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJSDocThisTag:
		d := n.AsJSDocThisTag()
		slots := [...]uint32{
			c.node(d.TagName),
			c.node(d.TypeExpression),
			c.list(d.Comment),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJSDocTypeTag:
		d := n.AsJSDocTypeTag()
		slots := [...]uint32{
			c.node(d.TagName),
			c.node(d.TypeExpression),
			c.list(d.Comment),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJSDocTemplateTag:
		d := n.AsJSDocTemplateTag()
		slots := [...]uint32{
			c.node(d.TagName),
			c.node(d.Constraint),
			c.list(d.TypeParameters),
			c.list(d.Comment),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJSDocTypedefTag:
		d := n.AsJSDocTypedefTag()
		slots := [...]uint32{
			c.node(d.TagName),
			c.node(d.TypeExpression),
			c.node(d.Name()),
			c.list(d.Comment),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJSDocSeeTag:
		d := n.AsJSDocSeeTag()
		slots := [...]uint32{
			c.node(d.TagName),
			c.node(d.NameExpression),
			c.list(d.Comment),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJSDocThrowsTag:
		d := n.AsJSDocThrowsTag()
		slots := [...]uint32{
			c.node(d.TagName),
			c.node(d.TypeExpression),
			c.list(d.Comment),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJSDocSatisfiesTag:
		d := n.AsJSDocSatisfiesTag()
		slots := [...]uint32{
			c.node(d.TagName),
			c.node(d.TypeExpression),
			c.list(d.Comment),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindJSDocImportTag:
		d := n.AsJSDocImportTag()
		slots := [...]uint32{
			c.node(d.TagName),
			c.node(d.ImportClause),
			c.node(d.ModuleSpecifier),
			c.node(d.Attributes),
			c.list(d.Comment),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindSyntaxList:
		d := n.AsSyntaxList()
		slots := [...]uint32{
			c.raw(d.Children),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindPartiallyEmittedExpression:
		d := n.AsPartiallyEmittedExpression()
		slots := [...]uint32{
			c.node(d.Expression),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	case ast.KindSyntheticReferenceExpression:
		d := n.AsSyntheticReferenceExpression()
		slots := [...]uint32{
			c.node(d.Expression),
			c.node(d.ThisArg),
		}
		return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, slots[:]))
	}
	return uint32(c.b.Node(n.Kind, n.Flags, n.ModifierFlags(), pos, end, nil))
}
