// Code generated by tools/scripts/tsc/generate-go-ast.ts. DO NOT EDIT.

package binder

import "github.com/microsoft/TypeScript/tsc/internal/ast"

func (b *Binder) bindFunctionLikeChildrenGenerated(ref ast.NodeRef, kind ast.Kind) {
	s := b.store
	switch kind {
	case ast.KindFunctionDeclaration:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindListRef(s.ListSlotAt(ref, 1), kind)
		b.bindListRef(s.ListSlotAt(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 3), kind)
		b.bindChildRef(s.ChildRef(ref, 4), kind)
	case ast.KindCallSignature:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindConstructSignature:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindConstructor:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 1), kind)
		b.bindListRef(s.ListSlotAt(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
	case ast.KindGetAccessor:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 1), kind)
		b.bindListRef(s.ListSlotAt(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 3), kind)
	case ast.KindSetAccessor:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 1), kind)
		b.bindListRef(s.ListSlotAt(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 3), kind)
	case ast.KindIndexSignature:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindMethodSignature:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindListRef(s.ListSlotAt(ref, 1), kind)
		b.bindListRef(s.ListSlotAt(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
	case ast.KindMethodDeclaration:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
		b.bindListRef(s.ListSlotAt(ref, 1), kind)
		b.bindListRef(s.ListSlotAt(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 3), kind)
		b.bindChildRef(s.ChildRef(ref, 4), kind)
		b.bindChildRef(s.ChildRef(ref, 5), kind)
	case ast.KindClassStaticBlockDeclaration:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindArrowFunction:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 1), kind)
		b.bindListRef(s.ListSlotAt(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 3), kind)
	case ast.KindFunctionExpression:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindListRef(s.ListSlotAt(ref, 1), kind)
		b.bindListRef(s.ListSlotAt(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 3), kind)
		b.bindChildRef(s.ChildRef(ref, 4), kind)
	case ast.KindFunctionType:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindConstructorType:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 1), kind)
		b.bindListRef(s.ListSlotAt(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	}
}

func (b *Binder) functionLikeBodyRefGenerated(ref ast.NodeRef, kind ast.Kind) ast.NodeRef {
	s := b.store
	switch kind {
	case ast.KindFunctionDeclaration:
		return s.ChildRef(ref, 4)
	case ast.KindConstructor:
		return s.ChildRef(ref, 2)
	case ast.KindGetAccessor:
		return s.ChildRef(ref, 3)
	case ast.KindSetAccessor:
		return s.ChildRef(ref, 3)
	case ast.KindMethodDeclaration:
		return s.ChildRef(ref, 5)
	case ast.KindClassStaticBlockDeclaration:
		return s.ChildRef(ref, 0)
	case ast.KindArrowFunction:
		return s.ChildRef(ref, 3)
	case ast.KindFunctionExpression:
		return s.ChildRef(ref, 4)
	}
	return 0
}

func (b *Binder) bindFunctionsFirstChildrenGenerated(ref ast.NodeRef, kind ast.Kind) {
	s := b.store
	switch kind {
	case ast.KindBlock:
		b.bindEachStatementFunctionsFirstRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindModuleBlock:
		b.bindEachStatementFunctionsFirstRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindSourceFile:
		b.bindEachStatementFunctionsFirstRef(s.ListSlotAt(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	}
}

func (b *Binder) nameRefGenerated(ref ast.NodeRef, kind ast.Kind) ast.NodeRef {
	s := b.store
	switch kind {
	case ast.KindVariableDeclaration:
		return s.ChildRef(ref, 0)
	case ast.KindParameter:
		return s.ChildRef(ref, 1)
	case ast.KindBindingElement:
		return s.ChildRef(ref, 2)
	case ast.KindFunctionDeclaration:
		return s.ChildRef(ref, 1)
	case ast.KindClassDeclaration:
		return s.ChildRef(ref, 0)
	case ast.KindClassExpression:
		return s.ChildRef(ref, 0)
	case ast.KindInterfaceDeclaration:
		return s.ChildRef(ref, 0)
	case ast.KindTypeAliasDeclaration, ast.KindJSTypeAliasDeclaration:
		return s.ChildRef(ref, 0)
	case ast.KindEnumMember:
		return s.ChildRef(ref, 0)
	case ast.KindEnumDeclaration:
		return s.ChildRef(ref, 0)
	case ast.KindNamespaceImport:
		return s.ChildRef(ref, 0)
	case ast.KindNamespaceExportDeclaration:
		return s.ChildRef(ref, 0)
	case ast.KindNamespaceExport:
		return s.ChildRef(ref, 0)
	case ast.KindExportSpecifier:
		return s.ChildRef(ref, 1)
	case ast.KindGetAccessor:
		return s.ChildRef(ref, 0)
	case ast.KindSetAccessor:
		return s.ChildRef(ref, 0)
	case ast.KindMethodSignature:
		return s.ChildRef(ref, 0)
	case ast.KindMethodDeclaration:
		return s.ChildRef(ref, 1)
	case ast.KindPropertySignature:
		return s.ChildRef(ref, 0)
	case ast.KindPropertyDeclaration:
		return s.ChildRef(ref, 0)
	case ast.KindFunctionExpression:
		return s.ChildRef(ref, 1)
	case ast.KindPropertyAccessExpression:
		return s.ChildRef(ref, 2)
	case ast.KindMetaProperty:
		return s.ChildRef(ref, 0)
	case ast.KindPropertyAssignment:
		return s.ChildRef(ref, 0)
	case ast.KindShorthandPropertyAssignment:
		return s.ChildRef(ref, 0)
	case ast.KindImportAttribute:
		return s.ChildRef(ref, 0)
	case ast.KindNamedTupleMember:
		return s.ChildRef(ref, 1)
	case ast.KindJsxNamespacedName:
		return s.ChildRef(ref, 1)
	case ast.KindJsxAttribute:
		return s.ChildRef(ref, 0)
	case ast.KindJSDocCallbackTag:
		return s.ChildRef(ref, 2)
	case ast.KindJSDocTypedefTag:
		return s.ChildRef(ref, 2)
	case ast.KindJSDocNameReference:
		return s.ChildRef(ref, 0)
	case ast.KindModuleDeclaration:
		return s.ChildRef(ref, 0)
	case ast.KindImportEqualsDeclaration:
		return s.ChildRef(ref, 0)
	case ast.KindImportClause:
		return s.ChildRef(ref, 0)
	case ast.KindImportSpecifier:
		return s.ChildRef(ref, 1)
	case ast.KindJSDocLink:
		return s.ChildRef(ref, 0)
	case ast.KindJSDocLinkPlain:
		return s.ChildRef(ref, 0)
	case ast.KindJSDocLinkCode:
		return s.ChildRef(ref, 0)
	case ast.KindTypeParameter:
		return s.ChildRef(ref, 0)
	case ast.KindJSDocParameterTag, ast.KindJSDocPropertyTag:
		return s.ChildRef(ref, 1)
	}
	return 0
}

func (b *Binder) modifiersRefGenerated(ref ast.NodeRef, kind ast.Kind) ast.ListRef {
	s := b.store
	switch kind {
	case ast.KindVariableStatement:
		return s.ListSlotAt(ref, 0)
	case ast.KindParameter:
		return s.ListSlotAt(ref, 0)
	case ast.KindMissingDeclaration:
		return s.ListSlotAt(ref, 0)
	case ast.KindFunctionDeclaration:
		return s.ListSlotAt(ref, 0)
	case ast.KindClassDeclaration:
		return s.ListSlotAt(ref, 0)
	case ast.KindClassExpression:
		return s.ListSlotAt(ref, 0)
	case ast.KindInterfaceDeclaration:
		return s.ListSlotAt(ref, 0)
	case ast.KindTypeAliasDeclaration, ast.KindJSTypeAliasDeclaration:
		return s.ListSlotAt(ref, 0)
	case ast.KindEnumDeclaration:
		return s.ListSlotAt(ref, 0)
	case ast.KindImportDeclaration, ast.KindJSImportDeclaration:
		return s.ListSlotAt(ref, 0)
	case ast.KindExportAssignment:
		return s.ListSlotAt(ref, 0)
	case ast.KindNamespaceExportDeclaration:
		return s.ListSlotAt(ref, 0)
	case ast.KindConstructor:
		return s.ListSlotAt(ref, 0)
	case ast.KindGetAccessor:
		return s.ListSlotAt(ref, 0)
	case ast.KindSetAccessor:
		return s.ListSlotAt(ref, 0)
	case ast.KindIndexSignature:
		return s.ListSlotAt(ref, 0)
	case ast.KindMethodSignature:
		return s.ListSlotAt(ref, 0)
	case ast.KindMethodDeclaration:
		return s.ListSlotAt(ref, 0)
	case ast.KindPropertySignature:
		return s.ListSlotAt(ref, 0)
	case ast.KindPropertyDeclaration:
		return s.ListSlotAt(ref, 0)
	case ast.KindClassStaticBlockDeclaration:
		return s.ListSlotAt(ref, 0)
	case ast.KindBinaryExpression:
		return s.ListSlotAt(ref, 0)
	case ast.KindArrowFunction:
		return s.ListSlotAt(ref, 0)
	case ast.KindFunctionExpression:
		return s.ListSlotAt(ref, 0)
	case ast.KindPropertyAssignment:
		return s.ListSlotAt(ref, 0)
	case ast.KindShorthandPropertyAssignment:
		return s.ListSlotAt(ref, 0)
	case ast.KindConstructorType:
		return s.ListSlotAt(ref, 0)
	case ast.KindModuleDeclaration:
		return s.ListSlotAt(ref, 0)
	case ast.KindImportEqualsDeclaration:
		return s.ListSlotAt(ref, 0)
	case ast.KindExportDeclaration:
		return s.ListSlotAt(ref, 0)
	case ast.KindTypeParameter:
		return s.ListSlotAt(ref, 0)
	}
	return 0
}

func (b *Binder) asteriskTokenRefGenerated(ref ast.NodeRef, kind ast.Kind) ast.NodeRef {
	s := b.store
	switch kind {
	case ast.KindFunctionDeclaration:
		return s.ChildRef(ref, 0)
	case ast.KindMethodDeclaration:
		return s.ChildRef(ref, 0)
	case ast.KindYieldExpression:
		return s.ChildRef(ref, 0)
	case ast.KindFunctionExpression:
		return s.ChildRef(ref, 0)
	}
	return 0
}
