// Code generated by tools/scripts/tsc/generate-go-ast.ts. DO NOT EDIT.

package binder

import "github.com/microsoft/TypeScript/tsc/internal/ast"

func (b *Binder) forEachBindChildGenerated(ref ast.NodeRef, kind ast.Kind) {
	s := b.store
	switch kind {
	case ast.KindQualifiedName:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
	case ast.KindComputedPropertyName:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindDecorator:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindIfStatement:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
	case ast.KindDoStatement:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
	case ast.KindWhileStatement:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
	case ast.KindForStatement:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 3), kind)
	case ast.KindForInStatement, ast.KindForOfStatement:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 3), kind)
	case ast.KindBreakStatement:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindContinueStatement:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindReturnStatement:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindWithStatement:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
	case ast.KindSwitchStatement:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
	case ast.KindCaseBlock:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindCaseClause, ast.KindDefaultClause:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindThrowStatement:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindTryStatement:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
	case ast.KindCatchClause:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
	case ast.KindLabeledStatement:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
	case ast.KindExpressionStatement:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindBlock:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindVariableStatement:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindVariableDeclaration:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 3), kind)
	case ast.KindVariableDeclarationList:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindObjectBindingPattern, ast.KindArrayBindingPattern:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindParameter:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 3), kind)
		b.bindChildRef(s.ChildRef(ref, 4), kind)
	case ast.KindBindingElement:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 3), kind)
	case ast.KindMissingDeclaration:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindFunctionDeclaration:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindListRef(s.ListSlotAt(ref, 1), kind)
		b.bindListRef(s.ListSlotAt(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 3), kind)
		b.bindChildRef(s.ChildRef(ref, 4), kind)
	case ast.KindClassDeclaration:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 1), kind)
		b.bindListRef(s.ListSlotAt(ref, 2), kind)
		b.bindListRef(s.ListSlotAt(ref, 3), kind)
	case ast.KindClassExpression:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 1), kind)
		b.bindListRef(s.ListSlotAt(ref, 2), kind)
		b.bindListRef(s.ListSlotAt(ref, 3), kind)
	case ast.KindHeritageClause:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindInterfaceDeclaration:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 1), kind)
		b.bindListRef(s.ListSlotAt(ref, 2), kind)
		b.bindListRef(s.ListSlotAt(ref, 3), kind)
	case ast.KindTypeAliasDeclaration, ast.KindJSTypeAliasDeclaration:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
	case ast.KindEnumMember:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
	case ast.KindEnumDeclaration:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 1), kind)
	case ast.KindModuleBlock:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindImportDeclaration, ast.KindJSImportDeclaration:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
	case ast.KindExternalModuleReference:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindNamespaceImport:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindNamedImports:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindExportAssignment:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
	case ast.KindNamespaceExportDeclaration:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindNamespaceExport:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindNamedExports:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindExportSpecifier:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
	case ast.KindCallSignature:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindConstructSignature:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindConstructor:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 1), kind)
		b.bindListRef(s.ListSlotAt(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
	case ast.KindGetAccessor:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 1), kind)
		b.bindListRef(s.ListSlotAt(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 3), kind)
	case ast.KindSetAccessor:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 1), kind)
		b.bindListRef(s.ListSlotAt(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 3), kind)
	case ast.KindIndexSignature:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindMethodSignature:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindListRef(s.ListSlotAt(ref, 1), kind)
		b.bindListRef(s.ListSlotAt(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
	case ast.KindMethodDeclaration:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
		b.bindListRef(s.ListSlotAt(ref, 1), kind)
		b.bindListRef(s.ListSlotAt(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 3), kind)
		b.bindChildRef(s.ChildRef(ref, 4), kind)
		b.bindChildRef(s.ChildRef(ref, 5), kind)
	case ast.KindPropertySignature:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 3), kind)
	case ast.KindPropertyDeclaration:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 3), kind)
	case ast.KindClassStaticBlockDeclaration:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindBinaryExpression:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 3), kind)
	case ast.KindPrefixUnaryExpression:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindPostfixUnaryExpression:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindYieldExpression:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
	case ast.KindArrowFunction:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 1), kind)
		b.bindListRef(s.ListSlotAt(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 3), kind)
	case ast.KindFunctionExpression:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindListRef(s.ListSlotAt(ref, 1), kind)
		b.bindListRef(s.ListSlotAt(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 3), kind)
		b.bindChildRef(s.ChildRef(ref, 4), kind)
	case ast.KindAsExpression:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
	case ast.KindSatisfiesExpression:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
	case ast.KindConditionalExpression:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 3), kind)
		b.bindChildRef(s.ChildRef(ref, 4), kind)
	case ast.KindPropertyAccessExpression:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
	case ast.KindElementAccessExpression:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
	case ast.KindCallExpression:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 1), kind)
	case ast.KindNewExpression:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 1), kind)
	case ast.KindMetaProperty:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindNonNullExpression:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindSpreadElement:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindTemplateExpression:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindTemplateSpan:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
	case ast.KindTaggedTemplateExpression:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
	case ast.KindParenthesizedExpression:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindArrayLiteralExpression:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindObjectLiteralExpression:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindSpreadAssignment:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindPropertyAssignment:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 3), kind)
	case ast.KindShorthandPropertyAssignment:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 3), kind)
		b.bindChildRef(s.ChildRef(ref, 4), kind)
	case ast.KindDeleteExpression:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindTypeOfExpression:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindVoidExpression:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindAwaitExpression:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindTypeAssertionExpression:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
	case ast.KindUnionType:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindIntersectionType:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindConditionalType:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 3), kind)
	case ast.KindTypeOperator:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindInferType:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindArrayType:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindIndexedAccessType:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
	case ast.KindTypeReference:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindExpressionWithTypeArguments:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindLiteralType:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindTypePredicate:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
	case ast.KindImportAttribute:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
	case ast.KindImportAttributes:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindTypeQuery:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindMappedType:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 3), kind)
		b.bindChildRef(s.ChildRef(ref, 4), kind)
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindTypeLiteral:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindTupleType:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindNamedTupleMember:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 3), kind)
	case ast.KindOptionalType:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindRestType:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindParenthesizedType:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindFunctionType:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindConstructorType:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 1), kind)
		b.bindListRef(s.ListSlotAt(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindTemplateLiteralType:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindTemplateLiteralTypeSpan:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
	case ast.KindSyntheticExpression:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindPartiallyEmittedExpression:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindJsxElement:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
	case ast.KindJsxAttributes:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindJsxNamespacedName:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
	case ast.KindJsxOpeningElement:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
	case ast.KindJsxSelfClosingElement:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
	case ast.KindJsxFragment:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
	case ast.KindJsxAttribute:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
	case ast.KindJsxSpreadAttribute:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindJsxClosingElement:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindJsxExpression:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
	case ast.KindSyntaxList:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindJSDoc:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 1), kind)
	case ast.KindJSDocTypeExpression:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindJSDocNonNullableType:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindJSDocNullableType:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindJSDocVariadicType:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindJSDocOptionalType:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindJSDocTypeTag:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindJSDocUnknownTag:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindJSDocTemplateTag:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 1), kind)
	case ast.KindJSDocReturnTag:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindJSDocPublicTag:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindJSDocPrivateTag:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindJSDocProtectedTag:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindJSDocReadonlyTag:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindJSDocOverrideTag:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindJSDocDeprecatedTag:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindJSDocSeeTag:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindJSDocImplementsTag:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindJSDocAugmentsTag:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindJSDocSatisfiesTag:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindJSDocThrowsTag:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindJSDocThisTag:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindJSDocImportTag:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 3), kind)
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindJSDocCallbackTag:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindJSDocOverloadTag:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindJSDocTypedefTag:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindJSDocSignature:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindListRef(s.ListSlotAt(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindJSDocNameReference:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindSourceFile:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindModuleDeclaration:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
	case ast.KindImportEqualsDeclaration:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
	case ast.KindExportDeclaration:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
	case ast.KindImportType:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindImportClause:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
	case ast.KindImportSpecifier:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
	case ast.KindJSDocLink:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindJSDocLinkPlain:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindJSDocLinkCode:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	case ast.KindTypeParameter:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
		b.bindChildRef(s.ChildRef(ref, 3), kind)
	case ast.KindSyntheticReferenceExpression:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
	case ast.KindJSDocTypeLiteral:
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindJSDocParameterTag, ast.KindJSDocPropertyTag:
		b.bindChildRef(s.ChildRef(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 1), kind)
		b.bindChildRef(s.ChildRef(ref, 2), kind)
		b.bindListRef(s.ListSlotAt(ref, 0), kind)
	default:
		b.bindChildrenOf(ref, kind)
	}
}

func (b *Binder) functionLikeBodyRefGenerated(ref ast.NodeRef, kind ast.Kind) ast.NodeRef {
	s := b.store
	switch kind {
	case ast.KindFunctionDeclaration:
		return s.ChildRef(ref, 4)
	case ast.KindConstructor:
		return s.ChildRef(ref, 2)
	case ast.KindGetAccessor:
		return s.ChildRef(ref, 3)
	case ast.KindSetAccessor:
		return s.ChildRef(ref, 3)
	case ast.KindMethodDeclaration:
		return s.ChildRef(ref, 5)
	case ast.KindClassStaticBlockDeclaration:
		return s.ChildRef(ref, 0)
	case ast.KindArrowFunction:
		return s.ChildRef(ref, 3)
	case ast.KindFunctionExpression:
		return s.ChildRef(ref, 4)
	}
	return 0
}

func (b *Binder) bindFunctionsFirstChildrenGenerated(ref ast.NodeRef, kind ast.Kind) {
	s := b.store
	switch kind {
	case ast.KindBlock:
		b.bindEachStatementFunctionsFirstRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindModuleBlock:
		b.bindEachStatementFunctionsFirstRef(s.ListSlotAt(ref, 0), kind)
	case ast.KindSourceFile:
		b.bindEachStatementFunctionsFirstRef(s.ListSlotAt(ref, 0), kind)
		b.bindChildRef(s.ChildRef(ref, 0), kind)
	}
}

func (b *Binder) nameRefGenerated(ref ast.NodeRef, kind ast.Kind) ast.NodeRef {
	s := b.store
	switch kind {
	case ast.KindVariableDeclaration:
		return s.ChildRef(ref, 0)
	case ast.KindParameter:
		return s.ChildRef(ref, 1)
	case ast.KindBindingElement:
		return s.ChildRef(ref, 2)
	case ast.KindFunctionDeclaration:
		return s.ChildRef(ref, 1)
	case ast.KindClassDeclaration:
		return s.ChildRef(ref, 0)
	case ast.KindClassExpression:
		return s.ChildRef(ref, 0)
	case ast.KindInterfaceDeclaration:
		return s.ChildRef(ref, 0)
	case ast.KindTypeAliasDeclaration, ast.KindJSTypeAliasDeclaration:
		return s.ChildRef(ref, 0)
	case ast.KindEnumMember:
		return s.ChildRef(ref, 0)
	case ast.KindEnumDeclaration:
		return s.ChildRef(ref, 0)
	case ast.KindNamespaceImport:
		return s.ChildRef(ref, 0)
	case ast.KindNamespaceExportDeclaration:
		return s.ChildRef(ref, 0)
	case ast.KindNamespaceExport:
		return s.ChildRef(ref, 0)
	case ast.KindExportSpecifier:
		return s.ChildRef(ref, 1)
	case ast.KindGetAccessor:
		return s.ChildRef(ref, 0)
	case ast.KindSetAccessor:
		return s.ChildRef(ref, 0)
	case ast.KindMethodSignature:
		return s.ChildRef(ref, 0)
	case ast.KindMethodDeclaration:
		return s.ChildRef(ref, 1)
	case ast.KindPropertySignature:
		return s.ChildRef(ref, 0)
	case ast.KindPropertyDeclaration:
		return s.ChildRef(ref, 0)
	case ast.KindFunctionExpression:
		return s.ChildRef(ref, 1)
	case ast.KindPropertyAccessExpression:
		return s.ChildRef(ref, 2)
	case ast.KindMetaProperty:
		return s.ChildRef(ref, 0)
	case ast.KindPropertyAssignment:
		return s.ChildRef(ref, 0)
	case ast.KindShorthandPropertyAssignment:
		return s.ChildRef(ref, 0)
	case ast.KindImportAttribute:
		return s.ChildRef(ref, 0)
	case ast.KindNamedTupleMember:
		return s.ChildRef(ref, 1)
	case ast.KindJsxNamespacedName:
		return s.ChildRef(ref, 1)
	case ast.KindJsxAttribute:
		return s.ChildRef(ref, 0)
	case ast.KindJSDocCallbackTag:
		return s.ChildRef(ref, 2)
	case ast.KindJSDocTypedefTag:
		return s.ChildRef(ref, 2)
	case ast.KindJSDocNameReference:
		return s.ChildRef(ref, 0)
	case ast.KindModuleDeclaration:
		return s.ChildRef(ref, 0)
	case ast.KindImportEqualsDeclaration:
		return s.ChildRef(ref, 0)
	case ast.KindImportClause:
		return s.ChildRef(ref, 0)
	case ast.KindImportSpecifier:
		return s.ChildRef(ref, 1)
	case ast.KindJSDocLink:
		return s.ChildRef(ref, 0)
	case ast.KindJSDocLinkPlain:
		return s.ChildRef(ref, 0)
	case ast.KindJSDocLinkCode:
		return s.ChildRef(ref, 0)
	case ast.KindTypeParameter:
		return s.ChildRef(ref, 0)
	case ast.KindJSDocParameterTag, ast.KindJSDocPropertyTag:
		return s.ChildRef(ref, 1)
	}
	return 0
}

func (b *Binder) modifiersRefGenerated(ref ast.NodeRef, kind ast.Kind) ast.ListRef {
	s := b.store
	switch kind {
	case ast.KindVariableStatement:
		return s.ListSlotAt(ref, 0)
	case ast.KindParameter:
		return s.ListSlotAt(ref, 0)
	case ast.KindMissingDeclaration:
		return s.ListSlotAt(ref, 0)
	case ast.KindFunctionDeclaration:
		return s.ListSlotAt(ref, 0)
	case ast.KindClassDeclaration:
		return s.ListSlotAt(ref, 0)
	case ast.KindClassExpression:
		return s.ListSlotAt(ref, 0)
	case ast.KindInterfaceDeclaration:
		return s.ListSlotAt(ref, 0)
	case ast.KindTypeAliasDeclaration, ast.KindJSTypeAliasDeclaration:
		return s.ListSlotAt(ref, 0)
	case ast.KindEnumDeclaration:
		return s.ListSlotAt(ref, 0)
	case ast.KindImportDeclaration, ast.KindJSImportDeclaration:
		return s.ListSlotAt(ref, 0)
	case ast.KindExportAssignment:
		return s.ListSlotAt(ref, 0)
	case ast.KindNamespaceExportDeclaration:
		return s.ListSlotAt(ref, 0)
	case ast.KindConstructor:
		return s.ListSlotAt(ref, 0)
	case ast.KindGetAccessor:
		return s.ListSlotAt(ref, 0)
	case ast.KindSetAccessor:
		return s.ListSlotAt(ref, 0)
	case ast.KindIndexSignature:
		return s.ListSlotAt(ref, 0)
	case ast.KindMethodSignature:
		return s.ListSlotAt(ref, 0)
	case ast.KindMethodDeclaration:
		return s.ListSlotAt(ref, 0)
	case ast.KindPropertySignature:
		return s.ListSlotAt(ref, 0)
	case ast.KindPropertyDeclaration:
		return s.ListSlotAt(ref, 0)
	case ast.KindClassStaticBlockDeclaration:
		return s.ListSlotAt(ref, 0)
	case ast.KindBinaryExpression:
		return s.ListSlotAt(ref, 0)
	case ast.KindArrowFunction:
		return s.ListSlotAt(ref, 0)
	case ast.KindFunctionExpression:
		return s.ListSlotAt(ref, 0)
	case ast.KindPropertyAssignment:
		return s.ListSlotAt(ref, 0)
	case ast.KindShorthandPropertyAssignment:
		return s.ListSlotAt(ref, 0)
	case ast.KindConstructorType:
		return s.ListSlotAt(ref, 0)
	case ast.KindModuleDeclaration:
		return s.ListSlotAt(ref, 0)
	case ast.KindImportEqualsDeclaration:
		return s.ListSlotAt(ref, 0)
	case ast.KindExportDeclaration:
		return s.ListSlotAt(ref, 0)
	case ast.KindTypeParameter:
		return s.ListSlotAt(ref, 0)
	}
	return 0
}

func (b *Binder) asteriskTokenRefGenerated(ref ast.NodeRef, kind ast.Kind) ast.NodeRef {
	s := b.store
	switch kind {
	case ast.KindFunctionDeclaration:
		return s.ChildRef(ref, 0)
	case ast.KindMethodDeclaration:
		return s.ChildRef(ref, 0)
	case ast.KindYieldExpression:
		return s.ChildRef(ref, 0)
	case ast.KindFunctionExpression:
		return s.ChildRef(ref, 0)
	}
	return 0
}

func (b *Binder) initializerRefGenerated(ref ast.NodeRef, kind ast.Kind) ast.NodeRef {
	s := b.store
	switch kind {
	case ast.KindForStatement:
		return s.ChildRef(ref, 0)
	case ast.KindForInStatement, ast.KindForOfStatement:
		return s.ChildRef(ref, 1)
	case ast.KindVariableDeclaration:
		return s.ChildRef(ref, 3)
	case ast.KindParameter:
		return s.ChildRef(ref, 4)
	case ast.KindBindingElement:
		return s.ChildRef(ref, 3)
	case ast.KindEnumMember:
		return s.ChildRef(ref, 1)
	case ast.KindPropertySignature:
		return s.ChildRef(ref, 3)
	case ast.KindPropertyDeclaration:
		return s.ChildRef(ref, 3)
	case ast.KindPropertyAssignment:
		return s.ChildRef(ref, 3)
	case ast.KindJsxAttribute:
		return s.ChildRef(ref, 1)
	}
	return 0
}

func (b *Binder) typeRefGenerated(ref ast.NodeRef, kind ast.Kind) ast.NodeRef {
	s := b.store
	switch kind {
	case ast.KindVariableDeclaration:
		return s.ChildRef(ref, 2)
	case ast.KindParameter:
		return s.ChildRef(ref, 3)
	case ast.KindFunctionDeclaration:
		return s.ChildRef(ref, 2)
	case ast.KindTypeAliasDeclaration, ast.KindJSTypeAliasDeclaration:
		return s.ChildRef(ref, 1)
	case ast.KindExportAssignment:
		return s.ChildRef(ref, 0)
	case ast.KindCallSignature:
		return s.ChildRef(ref, 0)
	case ast.KindConstructSignature:
		return s.ChildRef(ref, 0)
	case ast.KindConstructor:
		return s.ChildRef(ref, 0)
	case ast.KindGetAccessor:
		return s.ChildRef(ref, 1)
	case ast.KindSetAccessor:
		return s.ChildRef(ref, 1)
	case ast.KindIndexSignature:
		return s.ChildRef(ref, 0)
	case ast.KindMethodSignature:
		return s.ChildRef(ref, 2)
	case ast.KindMethodDeclaration:
		return s.ChildRef(ref, 3)
	case ast.KindPropertySignature:
		return s.ChildRef(ref, 2)
	case ast.KindPropertyDeclaration:
		return s.ChildRef(ref, 2)
	case ast.KindBinaryExpression:
		return s.ChildRef(ref, 1)
	case ast.KindArrowFunction:
		return s.ChildRef(ref, 0)
	case ast.KindFunctionExpression:
		return s.ChildRef(ref, 2)
	case ast.KindAsExpression:
		return s.ChildRef(ref, 1)
	case ast.KindSatisfiesExpression:
		return s.ChildRef(ref, 1)
	case ast.KindPropertyAssignment:
		return s.ChildRef(ref, 2)
	case ast.KindShorthandPropertyAssignment:
		return s.ChildRef(ref, 2)
	case ast.KindTypeAssertionExpression:
		return s.ChildRef(ref, 0)
	case ast.KindTypeOperator:
		return s.ChildRef(ref, 0)
	case ast.KindTypePredicate:
		return s.ChildRef(ref, 2)
	case ast.KindMappedType:
		return s.ChildRef(ref, 4)
	case ast.KindNamedTupleMember:
		return s.ChildRef(ref, 3)
	case ast.KindOptionalType:
		return s.ChildRef(ref, 0)
	case ast.KindRestType:
		return s.ChildRef(ref, 0)
	case ast.KindParenthesizedType:
		return s.ChildRef(ref, 0)
	case ast.KindFunctionType:
		return s.ChildRef(ref, 0)
	case ast.KindConstructorType:
		return s.ChildRef(ref, 0)
	case ast.KindTemplateLiteralTypeSpan:
		return s.ChildRef(ref, 0)
	case ast.KindJSDocTypeExpression:
		return s.ChildRef(ref, 0)
	case ast.KindJSDocNonNullableType:
		return s.ChildRef(ref, 0)
	case ast.KindJSDocNullableType:
		return s.ChildRef(ref, 0)
	case ast.KindJSDocVariadicType:
		return s.ChildRef(ref, 0)
	case ast.KindJSDocOptionalType:
		return s.ChildRef(ref, 0)
	case ast.KindJSDocSignature:
		return s.ChildRef(ref, 0)
	}
	return 0
}

func (b *Binder) expressionRefGenerated(ref ast.NodeRef, kind ast.Kind) ast.NodeRef {
	s := b.store
	switch kind {
	case ast.KindComputedPropertyName:
		return s.ChildRef(ref, 0)
	case ast.KindDecorator:
		return s.ChildRef(ref, 0)
	case ast.KindIfStatement:
		return s.ChildRef(ref, 0)
	case ast.KindDoStatement:
		return s.ChildRef(ref, 1)
	case ast.KindWhileStatement:
		return s.ChildRef(ref, 0)
	case ast.KindForInStatement, ast.KindForOfStatement:
		return s.ChildRef(ref, 2)
	case ast.KindReturnStatement:
		return s.ChildRef(ref, 0)
	case ast.KindWithStatement:
		return s.ChildRef(ref, 0)
	case ast.KindSwitchStatement:
		return s.ChildRef(ref, 0)
	case ast.KindCaseClause, ast.KindDefaultClause:
		return s.ChildRef(ref, 0)
	case ast.KindThrowStatement:
		return s.ChildRef(ref, 0)
	case ast.KindExpressionStatement:
		return s.ChildRef(ref, 0)
	case ast.KindExternalModuleReference:
		return s.ChildRef(ref, 0)
	case ast.KindExportAssignment:
		return s.ChildRef(ref, 1)
	case ast.KindYieldExpression:
		return s.ChildRef(ref, 1)
	case ast.KindAsExpression:
		return s.ChildRef(ref, 0)
	case ast.KindSatisfiesExpression:
		return s.ChildRef(ref, 0)
	case ast.KindPropertyAccessExpression:
		return s.ChildRef(ref, 0)
	case ast.KindElementAccessExpression:
		return s.ChildRef(ref, 0)
	case ast.KindCallExpression:
		return s.ChildRef(ref, 0)
	case ast.KindNewExpression:
		return s.ChildRef(ref, 0)
	case ast.KindNonNullExpression:
		return s.ChildRef(ref, 0)
	case ast.KindSpreadElement:
		return s.ChildRef(ref, 0)
	case ast.KindTemplateSpan:
		return s.ChildRef(ref, 0)
	case ast.KindParenthesizedExpression:
		return s.ChildRef(ref, 0)
	case ast.KindSpreadAssignment:
		return s.ChildRef(ref, 0)
	case ast.KindDeleteExpression:
		return s.ChildRef(ref, 0)
	case ast.KindTypeOfExpression:
		return s.ChildRef(ref, 0)
	case ast.KindVoidExpression:
		return s.ChildRef(ref, 0)
	case ast.KindAwaitExpression:
		return s.ChildRef(ref, 0)
	case ast.KindTypeAssertionExpression:
		return s.ChildRef(ref, 1)
	case ast.KindExpressionWithTypeArguments:
		return s.ChildRef(ref, 0)
	case ast.KindPartiallyEmittedExpression:
		return s.ChildRef(ref, 0)
	case ast.KindJsxSpreadAttribute:
		return s.ChildRef(ref, 0)
	case ast.KindJsxExpression:
		return s.ChildRef(ref, 1)
	case ast.KindTypeParameter:
		return s.ChildRef(ref, 2)
	case ast.KindSyntheticReferenceExpression:
		return s.ChildRef(ref, 0)
	}
	return 0
}

func (b *Binder) questionTokenRefGenerated(ref ast.NodeRef, kind ast.Kind) ast.NodeRef {
	s := b.store
	switch kind {
	case ast.KindParameter:
		return s.ChildRef(ref, 2)
	case ast.KindConditionalExpression:
		return s.ChildRef(ref, 1)
	case ast.KindMappedType:
		return s.ChildRef(ref, 3)
	case ast.KindNamedTupleMember:
		return s.ChildRef(ref, 2)
	}
	return 0
}

func (b *Binder) postfixTokenRefGenerated(ref ast.NodeRef, kind ast.Kind) ast.NodeRef {
	s := b.store
	switch kind {
	case ast.KindMethodSignature:
		return s.ChildRef(ref, 1)
	case ast.KindMethodDeclaration:
		return s.ChildRef(ref, 2)
	case ast.KindPropertySignature:
		return s.ChildRef(ref, 1)
	case ast.KindPropertyDeclaration:
		return s.ChildRef(ref, 1)
	case ast.KindPropertyAssignment:
		return s.ChildRef(ref, 1)
	case ast.KindShorthandPropertyAssignment:
		return s.ChildRef(ref, 1)
	}
	return 0
}

func (b *Binder) bodyRefGenerated(ref ast.NodeRef, kind ast.Kind) ast.NodeRef {
	s := b.store
	switch kind {
	case ast.KindFunctionDeclaration:
		return s.ChildRef(ref, 4)
	case ast.KindConstructor:
		return s.ChildRef(ref, 2)
	case ast.KindGetAccessor:
		return s.ChildRef(ref, 3)
	case ast.KindSetAccessor:
		return s.ChildRef(ref, 3)
	case ast.KindMethodDeclaration:
		return s.ChildRef(ref, 5)
	case ast.KindClassStaticBlockDeclaration:
		return s.ChildRef(ref, 0)
	case ast.KindArrowFunction:
		return s.ChildRef(ref, 3)
	case ast.KindFunctionExpression:
		return s.ChildRef(ref, 4)
	case ast.KindModuleDeclaration:
		return s.ChildRef(ref, 1)
	}
	return 0
}

func (b *Binder) exportClauseRefGenerated(ref ast.NodeRef, kind ast.Kind) ast.NodeRef {
	s := b.store
	switch kind {
	case ast.KindExportDeclaration:
		return s.ChildRef(ref, 0)
	}
	return 0
}

func (b *Binder) argumentsRefGenerated(ref ast.NodeRef, kind ast.Kind) ast.ListRef {
	s := b.store
	switch kind {
	case ast.KindCallExpression:
		return s.ListSlotAt(ref, 1)
	case ast.KindNewExpression:
		return s.ListSlotAt(ref, 1)
	}
	return 0
}

func (b *Binder) parametersRefGenerated(ref ast.NodeRef, kind ast.Kind) ast.ListRef {
	s := b.store
	switch kind {
	case ast.KindFunctionDeclaration:
		return s.ListSlotAt(ref, 2)
	case ast.KindCallSignature:
		return s.ListSlotAt(ref, 1)
	case ast.KindConstructSignature:
		return s.ListSlotAt(ref, 1)
	case ast.KindConstructor:
		return s.ListSlotAt(ref, 2)
	case ast.KindGetAccessor:
		return s.ListSlotAt(ref, 2)
	case ast.KindSetAccessor:
		return s.ListSlotAt(ref, 2)
	case ast.KindIndexSignature:
		return s.ListSlotAt(ref, 1)
	case ast.KindMethodSignature:
		return s.ListSlotAt(ref, 2)
	case ast.KindMethodDeclaration:
		return s.ListSlotAt(ref, 2)
	case ast.KindArrowFunction:
		return s.ListSlotAt(ref, 2)
	case ast.KindFunctionExpression:
		return s.ListSlotAt(ref, 2)
	case ast.KindFunctionType:
		return s.ListSlotAt(ref, 1)
	case ast.KindConstructorType:
		return s.ListSlotAt(ref, 2)
	case ast.KindJSDocSignature:
		return s.ListSlotAt(ref, 1)
	}
	return 0
}

func (b *Binder) statementsRefGenerated(ref ast.NodeRef, kind ast.Kind) ast.ListRef {
	s := b.store
	switch kind {
	case ast.KindCaseClause, ast.KindDefaultClause:
		return s.ListSlotAt(ref, 0)
	case ast.KindBlock:
		return s.ListSlotAt(ref, 0)
	case ast.KindModuleBlock:
		return s.ListSlotAt(ref, 0)
	case ast.KindSourceFile:
		return s.ListSlotAt(ref, 0)
	}
	return 0
}

func (b *Binder) caseBlockClausesRefGenerated(ref ast.NodeRef, kind ast.Kind) ast.ListRef {
	if kind == ast.KindCaseBlock {
		return b.store.ListSlotAt(ref, 0)
	}
	return 0
}

func (b *Binder) caseBlockRefGenerated(ref ast.NodeRef, kind ast.Kind) ast.NodeRef {
	if kind == ast.KindSwitchStatement {
		return b.store.ChildRef(ref, 1)
	}
	return 0
}

func (b *Binder) isExportEqualsRefGenerated(ref ast.NodeRef, kind ast.Kind) bool {
	return kind == ast.KindExportAssignment && b.store.UintValueAt(ref, 0) != 0
}
