package printer

import (
	"fmt"
	"github.com/microsoft/TypeScript/tsc/internal/ast"
	"github.com/microsoft/TypeScript/tsc/internal/collections"
	"github.com/microsoft/TypeScript/tsc/internal/core"
	"github.com/microsoft/TypeScript/tsc/internal/debug"
)

type tempFlags int

const (
	tempFlagsAuto      tempFlags = 0x00000000
	tempFlagsCountMask tempFlags = 0x0FFFFFFF
	tempFlags_i        tempFlags = 0x10000000
)

type NameGenerator struct {
	Context                            *EmitContext
	IsFileLevelUniqueNameInCurrentFile func(string, bool) bool
	GetTextOfNode                      func( // Flags enum to track count of temp variables and a few dedicated names
		// No preferred name
		// Temp variable counter
		// Use/preference flag for '_i'
		// callback for Printer.isFileLevelUniqueNameInCurrentFile
		// callback for Printer.getTextOfNode
		// Map of generated names for specific nodes
		// Map of generated private names for specific nodes
		// Map of generated names for temp and loop variables
		// NOTE: Used to match Strada, but should be moved to nameGenerationScope after port is complete.
		// The next nameGenerationScope in the stack
		// TempFlags for the current name generation scope.
		// TempFlags for the current name generation scope.
		// Names reserved in nested name generation scopes.
		// generatedNames         collections.Set[string] // NOTE: generated names should be scoped after Strada port is complete.
		// Gets the TempFlags to use in the current nameGenerationScope for the given key
		// Sets the TempFlags to use in the current nameGenerationScope for the given key
		// NOTE: Matches Strada, but is incorrect.
		// (*scope).generatedNames.Add(name) // TODO: generated names should be scoped after Strada port is complete.
		// Generate the text for a generated identifier or private identifier
		// Node names generate unique names based on their original node
		// and are cached based on that node's id.
		// Auto, Loop, and Unique names are cached based on their unique autoGenerateId.
		/*checkFn*/ /*privateName*/ /*prefix*/ /*suffix*/ /*reservedInNestedScopes*/ /*reservedInNestedScopes*/ /* ModuleDeclaration | EnumDeclaration */ // Use module/enum name itself if it is unique, otherwise make a unique variation
		/*checkFn*/ /*optimistic*/ /*scoped*/ /*privateName*/ /*prefix*/ /*suffix*/ /* ImportDeclaration | ExportDeclaration */ /*checkFn*/ /*optimistic*/ /*scoped*/ /*privateName*/ /*prefix*/ /*suffix*/ /*checkFn*/ /*optimistic*/ /*scoped*/ /*privateName*/ /*prefix*/ /*suffix*/ /*checkFn*/ /*optimistic*/ /*scoped*/ /*privateName*/ /*prefix*/ /*suffix*/ /* MethodDeclaration | AccessorDeclaration */ /*reservedInNestedScopes*/ /*privateName*/ // Return the next available name in the pattern _a ... _z, _0, _1, ...
		// TempFlags._i may be used to express a preference for that dedicated name.
		// Note that names generated by makeTempVariableName and makeUniqueName will never conflict.
		// Generate a key to use to acquire a TempFlags counter based on the fixed portions of the generated name.
		/*base*/ /*temp*/ // Skip over 'i' and 'n'
		/*temp*/ // Generate a name that is unique within the current file and doesn't conflict with any names
		// in global scope. The name is formed by adding an '_n' suffix to the specified base name,
		// where n is a positive integer. Note that names generated by makeTempVariableName and
		// makeUniqueName are guaranteed to never conflict.
		// If `optimistic` is set, the first instance will use 'baseName' verbatim instead of 'baseName_1'
		/*temp*/ // Find the first unique 'name_n', where n is a positive integer
		/*temp*/ /*optimistic*/ /*scoped*/ /*privateName*/ /*prefix*/ /*suffix*/ // We conservatively include alias symbols to cover cases where they're emitted as locals
		// NOTE: The following matches Strada, but is incorrect.
		// TODO: generated names should be scoped after Strada port is complete.
		////if *scope != nil {
		////	if (*scope).generatedNames.Has(name) {
		////		return true
		////	}
		////}
		ast.Handle) string
	nodeIdToGeneratedName          map[ast.GlobalRef]string
	nodeIdToGeneratedPrivateName   map[ast.GlobalRef]string
	autoGeneratedIdToGeneratedName map[AutoGenerateId]string
	nameGenerationScope            *nameGenerationScope
	privateNameGenerationScope     *nameGenerationScope
	generatedNames                 collections.Set[string]
}
type nameGenerationScope struct {
	next                   *nameGenerationScope
	tempFlags              tempFlags
	formattedNameTempFlags map[string]tempFlags
	reservedNames          collections.Set[string]
}

func (g *NameGenerator) PushScope(reuseTempVariableScope bool) {
	g.privateNameGenerationScope = &nameGenerationScope{next: g.privateNameGenerationScope}
	if !reuseTempVariableScope {
		g.nameGenerationScope = &nameGenerationScope{next: g.nameGenerationScope}
	}
}
func (g *NameGenerator) PopScope(reuseTempVariableScope bool) {
	if g.privateNameGenerationScope != nil {
		g.privateNameGenerationScope = g.privateNameGenerationScope.next
	}
	if !reuseTempVariableScope && g.nameGenerationScope != nil {
		g.nameGenerationScope = g.nameGenerationScope.next
	}
}
func (g *NameGenerator) getScope(privateName bool) **nameGenerationScope {
	return core.IfElse(privateName, &g.privateNameGenerationScope, &g.nameGenerationScope)
}
func (g *NameGenerator) getTempFlags(privateName bool) tempFlags {
	scope := g.getScope(privateName)
	if *scope != nil {
		return (*scope).tempFlags
	}
	return tempFlagsAuto
}
func (g *NameGenerator) setTempFlags(privateName bool, flags tempFlags) {
	scope := g.getScope(privateName)
	if *scope == nil {
		*scope = &nameGenerationScope{}
	}
	(*scope).tempFlags = flags
}

func (g *NameGenerator) getTempFlagsForFormattedName(privateName bool, formattedNameKey string) tempFlags {
	scope := g.getScope(privateName)
	if *scope != nil {
		if flags, ok := (*scope).formattedNameTempFlags[formattedNameKey]; ok {
			return flags
		}
	}
	return tempFlagsAuto
}

func (g *NameGenerator) setTempFlagsForFormattedName(privateName bool, formattedNameKey string, flags tempFlags) {
	scope := g.getScope(privateName)
	if *scope == nil {
		*scope = &nameGenerationScope{}
	}
	if (*scope).formattedNameTempFlags == nil {
		(*scope).formattedNameTempFlags = make(map[string]tempFlags)
	}
	(*scope).formattedNameTempFlags[formattedNameKey] = flags
}
func (g *NameGenerator) reserveName(name string, privateName bool, scoped bool, temp bool) {
	scope := g.getScope(privateName)
	if *scope == nil {
		*scope = &nameGenerationScope{}
	}
	if privateName || scoped {
		(*scope).reservedNames.Add(name)
	} else if !temp {
		g.generatedNames.Add(name)
	}
}

func (g *NameGenerator) GenerateName(name ast.Handle) string {
	if g.Context != nil {
		if autoGenerate := g.Context.GetAutoGenerateInfo(name); autoGenerate != nil {
			if autoGenerate.Flags.IsNode() {
				return g.generateNameForNodeCached(g.Context.GetNodeForGeneratedName(name), ast.IsPrivateIdentifier(name), autoGenerate.Flags, autoGenerate.Prefix, autoGenerate.Suffix)
			} else {
				if autoGeneratedName, ok := g.autoGeneratedIdToGeneratedName[autoGenerate.Id]; ok {
					return autoGeneratedName
				}
				if g.autoGeneratedIdToGeneratedName == nil {
					g.autoGeneratedIdToGeneratedName = make(map[AutoGenerateId]string)
				}
				autoGeneratedName := g.makeName(name)
				g.autoGeneratedIdToGeneratedName[autoGenerate.Id] = autoGeneratedName
				return autoGeneratedName
			}
		}
	}
	return g.GetTextOfNode(name)
}
func (g *NameGenerator) generateNameForNodeCached(node ast.Handle, privateName bool, flags GeneratedIdentifierFlags, prefix string, suffix string) string {
	nodeId := node.Global()
	if g.Context != nil {
		nodeId = g.Context.NodeIdentity(node)
	}
	cache := core.IfElse(privateName, &g.nodeIdToGeneratedPrivateName, &g.nodeIdToGeneratedName)
	if *cache == nil {
		*cache = make(map[ast.GlobalRef]string)
	}
	if name, ok := (*cache)[nodeId]; ok {
		return name
	}
	name := g.generateNameForNode(node, privateName, flags, prefix, suffix)
	(*cache)[nodeId] = name
	return name
}
func (g *NameGenerator) generateNameForNode(node ast.Handle, privateName bool, flags GeneratedIdentifierFlags, prefix string, suffix string) string {
	switch node.Kind {
	case ast.KindIdentifier, ast.KindPrivateIdentifier:
		return g.makeUniqueName(g.GetTextOfNode(node), nil, flags.IsOptimistic(), flags.IsReservedInNestedScopes(), privateName, prefix, suffix)
	case ast.KindModuleDeclaration, ast.KindEnumDeclaration:
		if privateName || len(prefix) > 0 || len(suffix) > 0 {
			panic("Generated name for a module or enum cannot be private and may have neither a prefix nor suffix")
		}
		return g.generateNameForModuleOrEnum(node)
	case ast.KindImportDeclaration, ast.KindJSImportDeclaration, ast.KindExportDeclaration:
		if privateName || len(prefix) > 0 || len(suffix) > 0 {
			panic("Generated name for an import or export cannot be private and may have neither a prefix nor suffix")
		}
		return g.generateNameForImportOrExportDeclaration(node)
	case ast.KindFunctionDeclaration, ast.KindClassDeclaration:
		if privateName || len(prefix) > 0 || len(suffix) > 0 {
			panic("Generated name for a class or function declaration cannot be private and may have neither a prefix nor suffix")
		}
		name := node.Name()
		if !name.IsNil() && !(g.Context == nil && g.Context.HasAutoGenerateInfo(name)) {
			return g.generateNameForNode(name, false, flags, "", "")
		}
		return g.generateNameForExportDefault()
	case ast.KindExportAssignment:
		if privateName || len(prefix) > 0 || len(suffix) > 0 {
			panic("Generated name for an export assignment cannot be private and may have neither a prefix nor suffix")
		}
		return g.generateNameForExportDefault()
	case ast.KindClassExpression:
		if privateName || len(prefix) > 0 || len(suffix) > 0 {
			panic("Generated name for a class expression cannot be private and may have neither a prefix nor suffix")
		}
		return g.generateNameForClassExpression()
	case ast.KindMethodDeclaration, ast.KindGetAccessor, ast.KindSetAccessor:
		return g.generateNameForMethodOrAccessor(node, privateName, prefix, suffix)
	case ast.KindComputedPropertyName:
		return g.makeTempVariableName(tempFlagsAuto, true, privateName, prefix, suffix)
	default:
		return g.makeTempVariableName(tempFlagsAuto, false, privateName, prefix, suffix)
	}
}
func (g *NameGenerator) generateNameForModuleOrEnum(node ast.Handle) string {
	name := g.GetTextOfNode(node.Name())
	if isUniqueLocalName(name, node) {
		return name
	} else {
		return g.makeUniqueName(name, nil, false, false, false, "", "")
	}
}
func (g *NameGenerator) generateNameForImportOrExportDeclaration(node ast.Handle) string {
	expr := ast.GetExternalModuleName(node)
	baseName := "module"
	if ast.IsStringLiteral(expr) {
		baseName = makeIdentifierFromModuleName(expr.Text())
	}
	return g.makeUniqueName(baseName, nil, false, false, false, "", "")
}
func (g *NameGenerator) generateNameForExportDefault() string {
	return g.makeUniqueName("default", nil, false, false, false, "", "")
}
func (g *NameGenerator) generateNameForClassExpression() string {
	return g.makeUniqueName("class", nil, false, false, false, "", "")
}
func (g *NameGenerator) generateNameForMethodOrAccessor(node ast.Handle, privateName bool, prefix string, suffix string) string {
	if ast.IsIdentifier(node.Name()) {
		return g.generateNameForNodeCached(node.Name(), privateName, GeneratedIdentifierFlagsNone, prefix, suffix)
	}
	return g.makeTempVariableName(tempFlagsAuto, false, privateName, prefix, suffix)
}
func (g *NameGenerator) makeName(name ast.Handle) string {
	if g.Context != nil {
		if autoGenerate := g.Context.GetAutoGenerateInfo(name); autoGenerate != nil {
			switch autoGenerate.Flags.Kind() {
			case GeneratedIdentifierFlagsAuto:
				return g.makeTempVariableName(tempFlagsAuto, autoGenerate.Flags.IsReservedInNestedScopes(), ast.IsPrivateIdentifier(name), autoGenerate.Prefix, autoGenerate.Suffix)
			case GeneratedIdentifierFlagsLoop:
				debug.Assert(ast.IsIdentifier(name))
				return g.makeTempVariableName(tempFlags_i, autoGenerate.Flags.IsReservedInNestedScopes(), false, autoGenerate.Prefix, autoGenerate.Suffix)
			case GeneratedIdentifierFlagsUnique:
				return g.makeUniqueName(name.Text(), core.IfElse(autoGenerate.Flags.IsFileLevel(), g.IsFileLevelUniqueNameInCurrentFile, nil), autoGenerate.Flags.IsOptimistic(), autoGenerate.Flags.IsReservedInNestedScopes(), ast.IsPrivateIdentifier(name), autoGenerate.Prefix, autoGenerate.Suffix)
			}
		}
	}
	return g.GetTextOfNode(name)
}

func (g *NameGenerator) makeTempVariableName(flags tempFlags, reservedInNestedScopes bool, privateName bool, prefix string, suffix string) string {
	var tempFlags tempFlags
	var key string
	simple := len(prefix) == 0 && len(suffix) == 0
	if simple {
		tempFlags = g.getTempFlags(privateName)
	} else {
		key = FormatGeneratedName(privateName, prefix, "", suffix)
		if privateName {
			key = ensureLeadingHash(key)
		}
		tempFlags = g.getTempFlagsForFormattedName(privateName, key)
	}
	if flags != 0 && tempFlags&flags == 0 {
		fullName := FormatGeneratedName(privateName, prefix, "_i", suffix)
		if g.isUniqueName(fullName, privateName) {
			tempFlags |= flags
			g.reserveName(fullName, privateName, reservedInNestedScopes, true)
			if simple {
				g.setTempFlags(privateName, tempFlags)
			} else {
				g.setTempFlagsForFormattedName(privateName, key, tempFlags)
			}
			return fullName
		}
	}
	for {
		count := tempFlags & tempFlagsCountMask
		tempFlags++
		if count != 8 && count != 13 {
			var name string
			if count < 26 {
				name = fmt.Sprintf("_%c", 'a'+byte(count))
			} else {
				name = fmt.Sprintf("_%d", count-26)
			}
			fullName := FormatGeneratedName(privateName, prefix, name, suffix)
			if g.isUniqueName(fullName, privateName) {
				g.reserveName(fullName, privateName, reservedInNestedScopes, true)
				if simple {
					g.setTempFlags(privateName, tempFlags)
				} else {
					g.setTempFlagsForFormattedName(privateName, key, tempFlags)
				}
				return fullName
			}
		}
	}
}

func (g *NameGenerator) makeUniqueName(baseName string, checkFn func(name string, privateName bool) bool, optimistic bool, scoped bool, privateName bool, prefix string, suffix string) string {
	baseName = removeLeadingHash(baseName)
	if optimistic {
		fullName := FormatGeneratedName(privateName, prefix, baseName, suffix)
		if g.checkUniqueName(fullName, privateName, checkFn) {
			g.reserveName(fullName, privateName, scoped, false)
			return fullName
		}
	}
	if len(baseName) > 0 && baseName[len(baseName)-1] != '_' {
		baseName += "_"
	}
	i := 1
	for {
		fullName := FormatGeneratedName(privateName, prefix, fmt.Sprintf("%s%d", baseName, i), suffix)
		if g.checkUniqueName(fullName, privateName, checkFn) {
			g.reserveName(fullName, privateName, scoped, false)
			return fullName
		}
		i++
	}
}
func (g *NameGenerator) MakeFileLevelOptimisticUniqueName(name string) string {
	return g.makeUniqueName(name, g.IsFileLevelUniqueNameInCurrentFile, true, false, false, "", "")
}
func (g *NameGenerator) checkUniqueName(name string, privateName bool, checkFn func(name string, privateName bool) bool) bool {
	if checkFn != nil {
		return checkFn(name, privateName)
	} else {
		return g.isUniqueName(name, privateName)
	}
}
func nextContainer(node ast.Handle) ast.Handle {
	return node.NextContainer()
}
func isUniqueLocalName(name string, container ast.Handle) bool {
	node := container
	for !node.IsNil() && ast.IsNodeDescendantOf(node, container) && ast.IsLocalsContainer(node) {
		locals := node.Locals()
		if locals != nil {
			if local, ok := locals[name]; ok && local.Flags&(ast.SymbolFlagsValue|ast.SymbolFlagsExportValue|ast.SymbolFlagsAlias) != 0 {
				return false
			}
		}
		node = nextContainer(node)
	}
	return true
}
func (g *NameGenerator) isUniqueName(name string, privateName bool) bool {
	return (g.IsFileLevelUniqueNameInCurrentFile == nil || g.IsFileLevelUniqueNameInCurrentFile(name, privateName)) && !g.isReservedName(name, privateName)
}
func (g *NameGenerator) isReservedName(name string, privateName bool) bool {
	scope := g.getScope(privateName)
	if g.generatedNames.Has(name) {
		return true
	}
	for *scope != nil {
		if (*scope).reservedNames.Has(name) {
			return true
		}
		scope = &(*scope).next
	}
	return false
}
