// Code generated by tools/scripts/tsc/generate-go-ast.ts. DO NOT EDIT.

package ast

func expandStored(f *NodeFactory, h Handle) *Node {
	if h.Ref() == 0 {
		return nil
	}
	switch h.Kind() {
	case KindIdentifier:
		n := f.NewIdentifier(h.StringValue(valueSlotIdentifierText))
		applyStoreHeader(n, h)
		return n
	case KindPrivateIdentifier:
		n := f.NewPrivateIdentifier(h.StringValue(valueSlotPrivateIdentifierText))
		applyStoreHeader(n, h)
		return n
	case KindQualifiedName:
		n := f.NewQualifiedName(expandStored(f, h.Child(slotQualifiedNameLeft)), expandStored(f, h.Child(slotQualifiedNameRight)))
		applyStoreHeader(n, h)
		return n
	case KindComputedPropertyName:
		n := f.NewComputedPropertyName(expandStored(f, h.Child(slotComputedPropertyNameExpression)))
		applyStoreHeader(n, h)
		return n
	case KindDecorator:
		n := f.NewDecorator(expandStored(f, h.Child(slotDecoratorExpression)))
		applyStoreHeader(n, h)
		return n
	case KindEmptyStatement:
		n := f.NewEmptyStatement()
		applyStoreHeader(n, h)
		return n
	case KindIfStatement:
		n := f.NewIfStatement(expandStored(f, h.Child(slotIfStatementExpression)), expandStored(f, h.Child(slotIfStatementThenStatement)), expandStored(f, h.Child(slotIfStatementElseStatement)))
		applyStoreHeader(n, h)
		return n
	case KindDoStatement:
		n := f.NewDoStatement(expandStored(f, h.Child(slotDoStatementStatement)), expandStored(f, h.Child(slotDoStatementExpression)))
		applyStoreHeader(n, h)
		return n
	case KindWhileStatement:
		n := f.NewWhileStatement(expandStored(f, h.Child(slotWhileStatementExpression)), expandStored(f, h.Child(slotWhileStatementStatement)))
		applyStoreHeader(n, h)
		return n
	case KindForStatement:
		n := f.NewForStatement(expandStored(f, h.Child(slotForStatementInitializer)), expandStored(f, h.Child(slotForStatementCondition)), expandStored(f, h.Child(slotForStatementIncrementor)), expandStored(f, h.Child(slotForStatementStatement)))
		applyStoreHeader(n, h)
		return n
	case KindForInStatement, KindForOfStatement:
		n := f.NewForInOrOfStatement(h.Kind(), expandStored(f, h.Child(slotForInOrOfStatementAwaitModifier)), expandStored(f, h.Child(slotForInOrOfStatementInitializer)), expandStored(f, h.Child(slotForInOrOfStatementExpression)), expandStored(f, h.Child(slotForInOrOfStatementStatement)))
		applyStoreHeader(n, h)
		return n
	case KindBreakStatement:
		n := f.NewBreakStatement(expandStored(f, h.Child(slotBreakStatementLabel)))
		applyStoreHeader(n, h)
		return n
	case KindContinueStatement:
		n := f.NewContinueStatement(expandStored(f, h.Child(slotContinueStatementLabel)))
		applyStoreHeader(n, h)
		return n
	case KindReturnStatement:
		n := f.NewReturnStatement(expandStored(f, h.Child(slotReturnStatementExpression)))
		applyStoreHeader(n, h)
		return n
	case KindWithStatement:
		n := f.NewWithStatement(expandStored(f, h.Child(slotWithStatementExpression)), expandStored(f, h.Child(slotWithStatementStatement)))
		applyStoreHeader(n, h)
		return n
	case KindSwitchStatement:
		n := f.NewSwitchStatement(expandStored(f, h.Child(slotSwitchStatementExpression)), expandStored(f, h.Child(slotSwitchStatementCaseBlock)))
		applyStoreHeader(n, h)
		return n
	case KindCaseBlock:
		n := f.NewCaseBlock(expandNodeList(f, h.Store(), h.ListSlot(listSlotCaseBlockClauses)))
		applyStoreHeader(n, h)
		return n
	case KindCaseClause, KindDefaultClause:
		n := f.NewCaseOrDefaultClause(h.Kind(), expandStored(f, h.Child(slotCaseOrDefaultClauseExpression)), expandNodeList(f, h.Store(), h.ListSlot(listSlotCaseOrDefaultClauseStatements)))
		applyStoreHeader(n, h)
		return n
	case KindThrowStatement:
		n := f.NewThrowStatement(expandStored(f, h.Child(slotThrowStatementExpression)))
		applyStoreHeader(n, h)
		return n
	case KindTryStatement:
		n := f.NewTryStatement(expandStored(f, h.Child(slotTryStatementTryBlock)), expandStored(f, h.Child(slotTryStatementCatchClause)), expandStored(f, h.Child(slotTryStatementFinallyBlock)))
		applyStoreHeader(n, h)
		return n
	case KindCatchClause:
		n := f.NewCatchClause(expandStored(f, h.Child(slotCatchClauseVariableDeclaration)), expandStored(f, h.Child(slotCatchClauseBlock)))
		applyStoreHeader(n, h)
		return n
	case KindDebuggerStatement:
		n := f.NewDebuggerStatement()
		applyStoreHeader(n, h)
		return n
	case KindLabeledStatement:
		n := f.NewLabeledStatement(expandStored(f, h.Child(slotLabeledStatementLabel)), expandStored(f, h.Child(slotLabeledStatementStatement)))
		applyStoreHeader(n, h)
		return n
	case KindExpressionStatement:
		n := f.NewExpressionStatement(expandStored(f, h.Child(slotExpressionStatementExpression)))
		applyStoreHeader(n, h)
		return n
	case KindBlock:
		n := f.NewBlock(expandNodeList(f, h.Store(), h.ListSlot(listSlotBlockStatements)), h.UintValue(valueSlotBlockMultiLine) != 0)
		applyStoreHeader(n, h)
		return n
	case KindVariableStatement:
		n := f.NewVariableStatement(expandModifierList(f, h.Store(), h.ListSlot(listSlotVariableStatementModifiers)), expandStored(f, h.Child(slotVariableStatementDeclarationList)))
		applyStoreHeader(n, h)
		return n
	case KindVariableDeclaration:
		n := f.NewVariableDeclaration(expandStored(f, h.Child(slotVariableDeclarationName)), expandStored(f, h.Child(slotVariableDeclarationExclamationToken)), expandStored(f, h.Child(slotVariableDeclarationType)), expandStored(f, h.Child(slotVariableDeclarationInitializer)))
		applyStoreHeader(n, h)
		return n
	case KindVariableDeclarationList:
		n := f.NewVariableDeclarationList(expandNodeList(f, h.Store(), h.ListSlot(listSlotVariableDeclarationListDeclarations)), h.Flags())
		applyStoreHeader(n, h)
		return n
	case KindObjectBindingPattern, KindArrayBindingPattern:
		n := f.NewBindingPattern(h.Kind(), expandNodeList(f, h.Store(), h.ListSlot(listSlotBindingPatternElements)))
		applyStoreHeader(n, h)
		return n
	case KindParameter:
		n := f.NewParameterDeclaration(expandModifierList(f, h.Store(), h.ListSlot(listSlotParameterDeclarationModifiers)), expandStored(f, h.Child(slotParameterDeclarationDotDotDotToken)), expandStored(f, h.Child(slotParameterDeclarationName)), expandStored(f, h.Child(slotParameterDeclarationQuestionToken)), expandStored(f, h.Child(slotParameterDeclarationType)), expandStored(f, h.Child(slotParameterDeclarationInitializer)))
		applyStoreHeader(n, h)
		return n
	case KindBindingElement:
		n := f.NewBindingElement(expandStored(f, h.Child(slotBindingElementDotDotDotToken)), expandStored(f, h.Child(slotBindingElementPropertyName)), expandStored(f, h.Child(slotBindingElementName)), expandStored(f, h.Child(slotBindingElementInitializer)))
		applyStoreHeader(n, h)
		return n
	case KindMissingDeclaration:
		n := f.NewMissingDeclaration(expandModifierList(f, h.Store(), h.ListSlot(listSlotMissingDeclarationModifiers)))
		applyStoreHeader(n, h)
		return n
	case KindFunctionDeclaration:
		n := f.NewFunctionDeclaration(expandModifierList(f, h.Store(), h.ListSlot(listSlotFunctionDeclarationModifiers)), expandStored(f, h.Child(slotFunctionDeclarationAsteriskToken)), expandStored(f, h.Child(slotFunctionDeclarationName)), expandNodeList(f, h.Store(), h.ListSlot(listSlotFunctionDeclarationTypeParameters)), expandNodeList(f, h.Store(), h.ListSlot(listSlotFunctionDeclarationParameters)), expandStored(f, h.Child(slotFunctionDeclarationType)), expandStored(f, h.Child(slotFunctionDeclarationFullSignature)), expandStored(f, h.Child(slotFunctionDeclarationBody)))
		applyStoreHeader(n, h)
		return n
	case KindClassDeclaration:
		n := f.NewClassDeclaration(expandModifierList(f, h.Store(), h.ListSlot(listSlotClassDeclarationModifiers)), expandStored(f, h.Child(slotClassDeclarationName)), expandNodeList(f, h.Store(), h.ListSlot(listSlotClassDeclarationTypeParameters)), expandNodeList(f, h.Store(), h.ListSlot(listSlotClassDeclarationHeritageClauses)), expandNodeList(f, h.Store(), h.ListSlot(listSlotClassDeclarationMembers)))
		applyStoreHeader(n, h)
		return n
	case KindClassExpression:
		n := f.NewClassExpression(expandModifierList(f, h.Store(), h.ListSlot(listSlotClassExpressionModifiers)), expandStored(f, h.Child(slotClassExpressionName)), expandNodeList(f, h.Store(), h.ListSlot(listSlotClassExpressionTypeParameters)), expandNodeList(f, h.Store(), h.ListSlot(listSlotClassExpressionHeritageClauses)), expandNodeList(f, h.Store(), h.ListSlot(listSlotClassExpressionMembers)))
		applyStoreHeader(n, h)
		return n
	case KindHeritageClause:
		n := f.NewHeritageClause(Kind(h.UintValue(valueSlotHeritageClauseToken)), expandNodeList(f, h.Store(), h.ListSlot(listSlotHeritageClauseTypes)))
		applyStoreHeader(n, h)
		return n
	case KindInterfaceDeclaration:
		n := f.NewInterfaceDeclaration(expandModifierList(f, h.Store(), h.ListSlot(listSlotInterfaceDeclarationModifiers)), expandStored(f, h.Child(slotInterfaceDeclarationName)), expandNodeList(f, h.Store(), h.ListSlot(listSlotInterfaceDeclarationTypeParameters)), expandNodeList(f, h.Store(), h.ListSlot(listSlotInterfaceDeclarationHeritageClauses)), expandNodeList(f, h.Store(), h.ListSlot(listSlotInterfaceDeclarationMembers)))
		applyStoreHeader(n, h)
		return n
	case KindTypeAliasDeclaration, KindJSTypeAliasDeclaration:
		n := f.NewTypeAliasDeclaration(expandModifierList(f, h.Store(), h.ListSlot(listSlotTypeAliasDeclarationModifiers)), expandStored(f, h.Child(slotTypeAliasDeclarationName)), expandNodeList(f, h.Store(), h.ListSlot(listSlotTypeAliasDeclarationTypeParameters)), expandStored(f, h.Child(slotTypeAliasDeclarationType)))
		applyStoreHeader(n, h)
		return n
	case KindEnumMember:
		n := f.NewEnumMember(expandStored(f, h.Child(slotEnumMemberName)), expandStored(f, h.Child(slotEnumMemberInitializer)))
		applyStoreHeader(n, h)
		return n
	case KindEnumDeclaration:
		n := f.NewEnumDeclaration(expandModifierList(f, h.Store(), h.ListSlot(listSlotEnumDeclarationModifiers)), expandStored(f, h.Child(slotEnumDeclarationName)), expandNodeList(f, h.Store(), h.ListSlot(listSlotEnumDeclarationMembers)))
		applyStoreHeader(n, h)
		return n
	case KindModuleBlock:
		n := f.NewModuleBlock(expandNodeList(f, h.Store(), h.ListSlot(listSlotModuleBlockStatements)))
		applyStoreHeader(n, h)
		return n
	case KindNotEmittedStatement:
		n := f.NewNotEmittedStatement()
		applyStoreHeader(n, h)
		return n
	case KindNotEmittedTypeElement:
		n := f.NewNotEmittedTypeElement()
		applyStoreHeader(n, h)
		return n
	case KindImportDeclaration, KindJSImportDeclaration:
		n := f.NewImportDeclaration(expandModifierList(f, h.Store(), h.ListSlot(listSlotImportDeclarationModifiers)), expandStored(f, h.Child(slotImportDeclarationImportClause)), expandStored(f, h.Child(slotImportDeclarationModuleSpecifier)), expandStored(f, h.Child(slotImportDeclarationAttributes)))
		applyStoreHeader(n, h)
		return n
	case KindExternalModuleReference:
		n := f.NewExternalModuleReference(expandStored(f, h.Child(slotExternalModuleReferenceExpression)))
		applyStoreHeader(n, h)
		return n
	case KindNamespaceImport:
		n := f.NewNamespaceImport(expandStored(f, h.Child(slotNamespaceImportName)))
		applyStoreHeader(n, h)
		return n
	case KindNamedImports:
		n := f.NewNamedImports(expandNodeList(f, h.Store(), h.ListSlot(listSlotNamedImportsElements)))
		applyStoreHeader(n, h)
		return n
	case KindExportAssignment:
		n := f.NewExportAssignment(expandModifierList(f, h.Store(), h.ListSlot(listSlotExportAssignmentModifiers)), h.UintValue(valueSlotExportAssignmentIsExportEquals) != 0, expandStored(f, h.Child(slotExportAssignmentType)), expandStored(f, h.Child(slotExportAssignmentExpression)))
		applyStoreHeader(n, h)
		return n
	case KindNamespaceExportDeclaration:
		n := f.NewNamespaceExportDeclaration(expandModifierList(f, h.Store(), h.ListSlot(listSlotNamespaceExportDeclarationModifiers)), expandStored(f, h.Child(slotNamespaceExportDeclarationName)))
		applyStoreHeader(n, h)
		return n
	case KindNamespaceExport:
		n := f.NewNamespaceExport(expandStored(f, h.Child(slotNamespaceExportName)))
		applyStoreHeader(n, h)
		return n
	case KindNamedExports:
		n := f.NewNamedExports(expandNodeList(f, h.Store(), h.ListSlot(listSlotNamedExportsElements)))
		applyStoreHeader(n, h)
		return n
	case KindExportSpecifier:
		n := f.NewExportSpecifier(h.UintValue(valueSlotExportSpecifierIsTypeOnly) != 0, expandStored(f, h.Child(slotExportSpecifierPropertyName)), expandStored(f, h.Child(slotExportSpecifierName)))
		applyStoreHeader(n, h)
		return n
	case KindCallSignature:
		n := f.NewCallSignatureDeclaration(expandNodeList(f, h.Store(), h.ListSlot(listSlotCallSignatureDeclarationTypeParameters)), expandNodeList(f, h.Store(), h.ListSlot(listSlotCallSignatureDeclarationParameters)), expandStored(f, h.Child(slotCallSignatureDeclarationType)))
		applyStoreHeader(n, h)
		return n
	case KindConstructSignature:
		n := f.NewConstructSignatureDeclaration(expandNodeList(f, h.Store(), h.ListSlot(listSlotConstructSignatureDeclarationTypeParameters)), expandNodeList(f, h.Store(), h.ListSlot(listSlotConstructSignatureDeclarationParameters)), expandStored(f, h.Child(slotConstructSignatureDeclarationType)))
		applyStoreHeader(n, h)
		return n
	case KindConstructor:
		n := f.NewConstructorDeclaration(expandModifierList(f, h.Store(), h.ListSlot(listSlotConstructorDeclarationModifiers)), expandNodeList(f, h.Store(), h.ListSlot(listSlotConstructorDeclarationTypeParameters)), expandNodeList(f, h.Store(), h.ListSlot(listSlotConstructorDeclarationParameters)), expandStored(f, h.Child(slotConstructorDeclarationType)), expandStored(f, h.Child(slotConstructorDeclarationFullSignature)), expandStored(f, h.Child(slotConstructorDeclarationBody)))
		applyStoreHeader(n, h)
		return n
	case KindGetAccessor:
		n := f.NewGetAccessorDeclaration(expandModifierList(f, h.Store(), h.ListSlot(listSlotGetAccessorDeclarationModifiers)), expandStored(f, h.Child(slotGetAccessorDeclarationName)), expandNodeList(f, h.Store(), h.ListSlot(listSlotGetAccessorDeclarationTypeParameters)), expandNodeList(f, h.Store(), h.ListSlot(listSlotGetAccessorDeclarationParameters)), expandStored(f, h.Child(slotGetAccessorDeclarationType)), expandStored(f, h.Child(slotGetAccessorDeclarationFullSignature)), expandStored(f, h.Child(slotGetAccessorDeclarationBody)))
		applyStoreHeader(n, h)
		return n
	case KindSetAccessor:
		n := f.NewSetAccessorDeclaration(expandModifierList(f, h.Store(), h.ListSlot(listSlotSetAccessorDeclarationModifiers)), expandStored(f, h.Child(slotSetAccessorDeclarationName)), expandNodeList(f, h.Store(), h.ListSlot(listSlotSetAccessorDeclarationTypeParameters)), expandNodeList(f, h.Store(), h.ListSlot(listSlotSetAccessorDeclarationParameters)), expandStored(f, h.Child(slotSetAccessorDeclarationType)), expandStored(f, h.Child(slotSetAccessorDeclarationFullSignature)), expandStored(f, h.Child(slotSetAccessorDeclarationBody)))
		applyStoreHeader(n, h)
		return n
	case KindIndexSignature:
		n := f.NewIndexSignatureDeclaration(expandModifierList(f, h.Store(), h.ListSlot(listSlotIndexSignatureDeclarationModifiers)), expandNodeList(f, h.Store(), h.ListSlot(listSlotIndexSignatureDeclarationParameters)), expandStored(f, h.Child(slotIndexSignatureDeclarationType)))
		applyStoreHeader(n, h)
		return n
	case KindMethodSignature:
		n := f.NewMethodSignatureDeclaration(expandModifierList(f, h.Store(), h.ListSlot(listSlotMethodSignatureDeclarationModifiers)), expandStored(f, h.Child(slotMethodSignatureDeclarationName)), expandStored(f, h.Child(slotMethodSignatureDeclarationPostfixToken)), expandNodeList(f, h.Store(), h.ListSlot(listSlotMethodSignatureDeclarationTypeParameters)), expandNodeList(f, h.Store(), h.ListSlot(listSlotMethodSignatureDeclarationParameters)), expandStored(f, h.Child(slotMethodSignatureDeclarationType)))
		applyStoreHeader(n, h)
		return n
	case KindMethodDeclaration:
		n := f.NewMethodDeclaration(expandModifierList(f, h.Store(), h.ListSlot(listSlotMethodDeclarationModifiers)), expandStored(f, h.Child(slotMethodDeclarationAsteriskToken)), expandStored(f, h.Child(slotMethodDeclarationName)), expandStored(f, h.Child(slotMethodDeclarationPostfixToken)), expandNodeList(f, h.Store(), h.ListSlot(listSlotMethodDeclarationTypeParameters)), expandNodeList(f, h.Store(), h.ListSlot(listSlotMethodDeclarationParameters)), expandStored(f, h.Child(slotMethodDeclarationType)), expandStored(f, h.Child(slotMethodDeclarationFullSignature)), expandStored(f, h.Child(slotMethodDeclarationBody)))
		applyStoreHeader(n, h)
		return n
	case KindPropertySignature:
		n := f.NewPropertySignatureDeclaration(expandModifierList(f, h.Store(), h.ListSlot(listSlotPropertySignatureDeclarationModifiers)), expandStored(f, h.Child(slotPropertySignatureDeclarationName)), expandStored(f, h.Child(slotPropertySignatureDeclarationPostfixToken)), expandStored(f, h.Child(slotPropertySignatureDeclarationType)), expandStored(f, h.Child(slotPropertySignatureDeclarationInitializer)))
		applyStoreHeader(n, h)
		return n
	case KindPropertyDeclaration:
		n := f.NewPropertyDeclaration(expandModifierList(f, h.Store(), h.ListSlot(listSlotPropertyDeclarationModifiers)), expandStored(f, h.Child(slotPropertyDeclarationName)), expandStored(f, h.Child(slotPropertyDeclarationPostfixToken)), expandStored(f, h.Child(slotPropertyDeclarationType)), expandStored(f, h.Child(slotPropertyDeclarationInitializer)))
		applyStoreHeader(n, h)
		return n
	case KindSemicolonClassElement:
		n := f.NewSemicolonClassElement()
		applyStoreHeader(n, h)
		return n
	case KindClassStaticBlockDeclaration:
		n := f.NewClassStaticBlockDeclaration(expandModifierList(f, h.Store(), h.ListSlot(listSlotClassStaticBlockDeclarationModifiers)), expandStored(f, h.Child(slotClassStaticBlockDeclarationBody)))
		applyStoreHeader(n, h)
		return n
	case KindOmittedExpression:
		n := f.NewOmittedExpression()
		applyStoreHeader(n, h)
		return n
	case KindNullKeyword, KindTrueKeyword, KindFalseKeyword, KindThisKeyword, KindSuperKeyword, KindImportKeyword:
		n := f.NewKeywordExpression(h.Kind())
		applyStoreHeader(n, h)
		return n
	case KindStringLiteral:
		n := f.NewStringLiteral(h.StringValue(valueSlotStringLiteralText), h.TokenFlags())
		applyStoreHeader(n, h)
		return n
	case KindNumericLiteral:
		n := f.NewNumericLiteral(h.StringValue(valueSlotNumericLiteralText), h.TokenFlags())
		applyStoreHeader(n, h)
		return n
	case KindBigIntLiteral:
		n := f.NewBigIntLiteral(h.StringValue(valueSlotBigIntLiteralText), h.TokenFlags())
		applyStoreHeader(n, h)
		return n
	case KindRegularExpressionLiteral:
		n := f.NewRegularExpressionLiteral(h.StringValue(valueSlotRegularExpressionLiteralText), h.TokenFlags())
		applyStoreHeader(n, h)
		return n
	case KindNoSubstitutionTemplateLiteral:
		n := f.NewNoSubstitutionTemplateLiteral(h.StringValue(valueSlotNoSubstitutionTemplateLiteralText), h.TokenFlags())
		applyStoreHeader(n, h)
		return n
	case KindBinaryExpression:
		n := f.NewBinaryExpression(expandModifierList(f, h.Store(), h.ListSlot(listSlotBinaryExpressionModifiers)), expandStored(f, h.Child(slotBinaryExpressionLeft)), expandStored(f, h.Child(slotBinaryExpressionType)), expandStored(f, h.Child(slotBinaryExpressionOperatorToken)), expandStored(f, h.Child(slotBinaryExpressionRight)))
		applyStoreHeader(n, h)
		return n
	case KindPrefixUnaryExpression:
		n := f.NewPrefixUnaryExpression(Kind(h.UintValue(valueSlotPrefixUnaryExpressionOperator)), expandStored(f, h.Child(slotPrefixUnaryExpressionOperand)))
		applyStoreHeader(n, h)
		return n
	case KindPostfixUnaryExpression:
		n := f.NewPostfixUnaryExpression(expandStored(f, h.Child(slotPostfixUnaryExpressionOperand)), Kind(h.UintValue(valueSlotPostfixUnaryExpressionOperator)))
		applyStoreHeader(n, h)
		return n
	case KindYieldExpression:
		n := f.NewYieldExpression(expandStored(f, h.Child(slotYieldExpressionAsteriskToken)), expandStored(f, h.Child(slotYieldExpressionExpression)))
		applyStoreHeader(n, h)
		return n
	case KindArrowFunction:
		n := f.NewArrowFunction(expandModifierList(f, h.Store(), h.ListSlot(listSlotArrowFunctionModifiers)), expandNodeList(f, h.Store(), h.ListSlot(listSlotArrowFunctionTypeParameters)), expandNodeList(f, h.Store(), h.ListSlot(listSlotArrowFunctionParameters)), expandStored(f, h.Child(slotArrowFunctionType)), expandStored(f, h.Child(slotArrowFunctionFullSignature)), expandStored(f, h.Child(slotArrowFunctionEqualsGreaterThanToken)), expandStored(f, h.Child(slotArrowFunctionBody)))
		applyStoreHeader(n, h)
		return n
	case KindFunctionExpression:
		n := f.NewFunctionExpression(expandModifierList(f, h.Store(), h.ListSlot(listSlotFunctionExpressionModifiers)), expandStored(f, h.Child(slotFunctionExpressionAsteriskToken)), expandStored(f, h.Child(slotFunctionExpressionName)), expandNodeList(f, h.Store(), h.ListSlot(listSlotFunctionExpressionTypeParameters)), expandNodeList(f, h.Store(), h.ListSlot(listSlotFunctionExpressionParameters)), expandStored(f, h.Child(slotFunctionExpressionType)), expandStored(f, h.Child(slotFunctionExpressionFullSignature)), expandStored(f, h.Child(slotFunctionExpressionBody)))
		applyStoreHeader(n, h)
		return n
	case KindAsExpression:
		n := f.NewAsExpression(expandStored(f, h.Child(slotAsExpressionExpression)), expandStored(f, h.Child(slotAsExpressionType)))
		applyStoreHeader(n, h)
		return n
	case KindSatisfiesExpression:
		n := f.NewSatisfiesExpression(expandStored(f, h.Child(slotSatisfiesExpressionExpression)), expandStored(f, h.Child(slotSatisfiesExpressionType)))
		applyStoreHeader(n, h)
		return n
	case KindConditionalExpression:
		n := f.NewConditionalExpression(expandStored(f, h.Child(slotConditionalExpressionCondition)), expandStored(f, h.Child(slotConditionalExpressionQuestionToken)), expandStored(f, h.Child(slotConditionalExpressionWhenTrue)), expandStored(f, h.Child(slotConditionalExpressionColonToken)), expandStored(f, h.Child(slotConditionalExpressionWhenFalse)))
		applyStoreHeader(n, h)
		return n
	case KindPropertyAccessExpression:
		n := f.NewPropertyAccessExpression(expandStored(f, h.Child(slotPropertyAccessExpressionExpression)), expandStored(f, h.Child(slotPropertyAccessExpressionQuestionDotToken)), expandStored(f, h.Child(slotPropertyAccessExpressionName)), h.Flags())
		applyStoreHeader(n, h)
		return n
	case KindElementAccessExpression:
		n := f.NewElementAccessExpression(expandStored(f, h.Child(slotElementAccessExpressionExpression)), expandStored(f, h.Child(slotElementAccessExpressionQuestionDotToken)), expandStored(f, h.Child(slotElementAccessExpressionArgumentExpression)), h.Flags())
		applyStoreHeader(n, h)
		return n
	case KindCallExpression:
		n := f.NewCallExpression(expandStored(f, h.Child(slotCallExpressionExpression)), expandStored(f, h.Child(slotCallExpressionQuestionDotToken)), expandNodeList(f, h.Store(), h.ListSlot(listSlotCallExpressionTypeArguments)), expandNodeList(f, h.Store(), h.ListSlot(listSlotCallExpressionArguments)), h.Flags())
		applyStoreHeader(n, h)
		return n
	case KindNewExpression:
		n := f.NewNewExpression(expandStored(f, h.Child(slotNewExpressionExpression)), expandNodeList(f, h.Store(), h.ListSlot(listSlotNewExpressionTypeArguments)), expandNodeList(f, h.Store(), h.ListSlot(listSlotNewExpressionArguments)))
		applyStoreHeader(n, h)
		return n
	case KindMetaProperty:
		n := f.NewMetaProperty(Kind(h.UintValue(valueSlotMetaPropertyKeywordToken)), expandStored(f, h.Child(slotMetaPropertyName)))
		applyStoreHeader(n, h)
		return n
	case KindNonNullExpression:
		n := f.NewNonNullExpression(expandStored(f, h.Child(slotNonNullExpressionExpression)), h.Flags())
		applyStoreHeader(n, h)
		return n
	case KindSpreadElement:
		n := f.NewSpreadElement(expandStored(f, h.Child(slotSpreadElementExpression)))
		applyStoreHeader(n, h)
		return n
	case KindTemplateExpression:
		n := f.NewTemplateExpression(expandStored(f, h.Child(slotTemplateExpressionHead)), expandNodeList(f, h.Store(), h.ListSlot(listSlotTemplateExpressionTemplateSpans)))
		applyStoreHeader(n, h)
		return n
	case KindTemplateSpan:
		n := f.NewTemplateSpan(expandStored(f, h.Child(slotTemplateSpanExpression)), expandStored(f, h.Child(slotTemplateSpanLiteral)))
		applyStoreHeader(n, h)
		return n
	case KindTaggedTemplateExpression:
		n := f.NewTaggedTemplateExpression(expandStored(f, h.Child(slotTaggedTemplateExpressionTag)), expandStored(f, h.Child(slotTaggedTemplateExpressionQuestionDotToken)), expandNodeList(f, h.Store(), h.ListSlot(listSlotTaggedTemplateExpressionTypeArguments)), expandStored(f, h.Child(slotTaggedTemplateExpressionTemplate)), h.Flags())
		applyStoreHeader(n, h)
		return n
	case KindParenthesizedExpression:
		n := f.NewParenthesizedExpression(expandStored(f, h.Child(slotParenthesizedExpressionExpression)))
		applyStoreHeader(n, h)
		return n
	case KindArrayLiteralExpression:
		n := f.NewArrayLiteralExpression(expandNodeList(f, h.Store(), h.ListSlot(listSlotArrayLiteralExpressionElements)), h.UintValue(valueSlotArrayLiteralExpressionMultiLine) != 0)
		applyStoreHeader(n, h)
		return n
	case KindObjectLiteralExpression:
		n := f.NewObjectLiteralExpression(expandNodeList(f, h.Store(), h.ListSlot(listSlotObjectLiteralExpressionProperties)), h.UintValue(valueSlotObjectLiteralExpressionMultiLine) != 0)
		applyStoreHeader(n, h)
		return n
	case KindSpreadAssignment:
		n := f.NewSpreadAssignment(expandStored(f, h.Child(slotSpreadAssignmentExpression)))
		applyStoreHeader(n, h)
		return n
	case KindPropertyAssignment:
		n := f.NewPropertyAssignment(expandModifierList(f, h.Store(), h.ListSlot(listSlotPropertyAssignmentModifiers)), expandStored(f, h.Child(slotPropertyAssignmentName)), expandStored(f, h.Child(slotPropertyAssignmentPostfixToken)), expandStored(f, h.Child(slotPropertyAssignmentType)), expandStored(f, h.Child(slotPropertyAssignmentInitializer)))
		applyStoreHeader(n, h)
		return n
	case KindShorthandPropertyAssignment:
		n := f.NewShorthandPropertyAssignment(expandModifierList(f, h.Store(), h.ListSlot(listSlotShorthandPropertyAssignmentModifiers)), expandStored(f, h.Child(slotShorthandPropertyAssignmentName)), expandStored(f, h.Child(slotShorthandPropertyAssignmentPostfixToken)), expandStored(f, h.Child(slotShorthandPropertyAssignmentType)), expandStored(f, h.Child(slotShorthandPropertyAssignmentEqualsToken)), expandStored(f, h.Child(slotShorthandPropertyAssignmentObjectAssignmentInitializer)))
		applyStoreHeader(n, h)
		return n
	case KindDeleteExpression:
		n := f.NewDeleteExpression(expandStored(f, h.Child(slotDeleteExpressionExpression)))
		applyStoreHeader(n, h)
		return n
	case KindTypeOfExpression:
		n := f.NewTypeOfExpression(expandStored(f, h.Child(slotTypeOfExpressionExpression)))
		applyStoreHeader(n, h)
		return n
	case KindVoidExpression:
		n := f.NewVoidExpression(expandStored(f, h.Child(slotVoidExpressionExpression)))
		applyStoreHeader(n, h)
		return n
	case KindAwaitExpression:
		n := f.NewAwaitExpression(expandStored(f, h.Child(slotAwaitExpressionExpression)))
		applyStoreHeader(n, h)
		return n
	case KindTypeAssertionExpression:
		n := f.NewTypeAssertion(expandStored(f, h.Child(slotTypeAssertionType)), expandStored(f, h.Child(slotTypeAssertionExpression)))
		applyStoreHeader(n, h)
		return n
	case KindAnyKeyword, KindBigIntKeyword, KindBooleanKeyword, KindIntrinsicKeyword, KindNeverKeyword, KindNumberKeyword, KindObjectKeyword, KindStringKeyword, KindSymbolKeyword, KindUndefinedKeyword, KindUnknownKeyword, KindVoidKeyword:
		n := f.NewKeywordTypeNode(h.Kind())
		applyStoreHeader(n, h)
		return n
	case KindUnionType:
		n := f.NewUnionTypeNode(expandNodeList(f, h.Store(), h.ListSlot(listSlotUnionTypeNodeTypes)))
		applyStoreHeader(n, h)
		return n
	case KindIntersectionType:
		n := f.NewIntersectionTypeNode(expandNodeList(f, h.Store(), h.ListSlot(listSlotIntersectionTypeNodeTypes)))
		applyStoreHeader(n, h)
		return n
	case KindConditionalType:
		n := f.NewConditionalTypeNode(expandStored(f, h.Child(slotConditionalTypeNodeCheckType)), expandStored(f, h.Child(slotConditionalTypeNodeExtendsType)), expandStored(f, h.Child(slotConditionalTypeNodeTrueType)), expandStored(f, h.Child(slotConditionalTypeNodeFalseType)))
		applyStoreHeader(n, h)
		return n
	case KindTypeOperator:
		n := f.NewTypeOperatorNode(Kind(h.UintValue(valueSlotTypeOperatorNodeOperator)), expandStored(f, h.Child(slotTypeOperatorNodeType)))
		applyStoreHeader(n, h)
		return n
	case KindInferType:
		n := f.NewInferTypeNode(expandStored(f, h.Child(slotInferTypeNodeTypeParameter)))
		applyStoreHeader(n, h)
		return n
	case KindArrayType:
		n := f.NewArrayTypeNode(expandStored(f, h.Child(slotArrayTypeNodeElementType)))
		applyStoreHeader(n, h)
		return n
	case KindIndexedAccessType:
		n := f.NewIndexedAccessTypeNode(expandStored(f, h.Child(slotIndexedAccessTypeNodeObjectType)), expandStored(f, h.Child(slotIndexedAccessTypeNodeIndexType)))
		applyStoreHeader(n, h)
		return n
	case KindTypeReference:
		n := f.NewTypeReferenceNode(expandStored(f, h.Child(slotTypeReferenceNodeTypeName)), expandNodeList(f, h.Store(), h.ListSlot(listSlotTypeReferenceNodeTypeArguments)))
		applyStoreHeader(n, h)
		return n
	case KindExpressionWithTypeArguments:
		n := f.NewExpressionWithTypeArguments(expandStored(f, h.Child(slotExpressionWithTypeArgumentsExpression)), expandNodeList(f, h.Store(), h.ListSlot(listSlotExpressionWithTypeArgumentsTypeArguments)))
		applyStoreHeader(n, h)
		return n
	case KindLiteralType:
		n := f.NewLiteralTypeNode(expandStored(f, h.Child(slotLiteralTypeNodeLiteral)))
		applyStoreHeader(n, h)
		return n
	case KindThisType:
		n := f.NewThisTypeNode()
		applyStoreHeader(n, h)
		return n
	case KindTypePredicate:
		n := f.NewTypePredicateNode(expandStored(f, h.Child(slotTypePredicateNodeAssertsModifier)), expandStored(f, h.Child(slotTypePredicateNodeParameterName)), expandStored(f, h.Child(slotTypePredicateNodeType)))
		applyStoreHeader(n, h)
		return n
	case KindImportAttribute:
		n := f.NewImportAttribute(expandStored(f, h.Child(slotImportAttributeName)), expandStored(f, h.Child(slotImportAttributeValue)))
		applyStoreHeader(n, h)
		return n
	case KindImportAttributes:
		n := f.NewImportAttributes(Kind(h.UintValue(valueSlotImportAttributesToken)), expandNodeList(f, h.Store(), h.ListSlot(listSlotImportAttributesAttributes)), h.UintValue(valueSlotImportAttributesMultiLine) != 0)
		applyStoreHeader(n, h)
		return n
	case KindTypeQuery:
		n := f.NewTypeQueryNode(expandStored(f, h.Child(slotTypeQueryNodeExprName)), expandNodeList(f, h.Store(), h.ListSlot(listSlotTypeQueryNodeTypeArguments)))
		applyStoreHeader(n, h)
		return n
	case KindMappedType:
		n := f.NewMappedTypeNode(expandStored(f, h.Child(slotMappedTypeNodeReadonlyToken)), expandStored(f, h.Child(slotMappedTypeNodeTypeParameter)), expandStored(f, h.Child(slotMappedTypeNodeNameType)), expandStored(f, h.Child(slotMappedTypeNodeQuestionToken)), expandStored(f, h.Child(slotMappedTypeNodeType)), expandNodeList(f, h.Store(), h.ListSlot(listSlotMappedTypeNodeMembers)))
		applyStoreHeader(n, h)
		return n
	case KindTypeLiteral:
		n := f.NewTypeLiteralNode(expandNodeList(f, h.Store(), h.ListSlot(listSlotTypeLiteralNodeMembers)))
		applyStoreHeader(n, h)
		return n
	case KindTupleType:
		n := f.NewTupleTypeNode(expandNodeList(f, h.Store(), h.ListSlot(listSlotTupleTypeNodeElements)))
		applyStoreHeader(n, h)
		return n
	case KindNamedTupleMember:
		n := f.NewNamedTupleMember(expandStored(f, h.Child(slotNamedTupleMemberDotDotDotToken)), expandStored(f, h.Child(slotNamedTupleMemberName)), expandStored(f, h.Child(slotNamedTupleMemberQuestionToken)), expandStored(f, h.Child(slotNamedTupleMemberType)))
		applyStoreHeader(n, h)
		return n
	case KindOptionalType:
		n := f.NewOptionalTypeNode(expandStored(f, h.Child(slotOptionalTypeNodeType)))
		applyStoreHeader(n, h)
		return n
	case KindRestType:
		n := f.NewRestTypeNode(expandStored(f, h.Child(slotRestTypeNodeType)))
		applyStoreHeader(n, h)
		return n
	case KindParenthesizedType:
		n := f.NewParenthesizedTypeNode(expandStored(f, h.Child(slotParenthesizedTypeNodeType)))
		applyStoreHeader(n, h)
		return n
	case KindFunctionType:
		n := f.NewFunctionTypeNode(expandNodeList(f, h.Store(), h.ListSlot(listSlotFunctionTypeNodeTypeParameters)), expandNodeList(f, h.Store(), h.ListSlot(listSlotFunctionTypeNodeParameters)), expandStored(f, h.Child(slotFunctionTypeNodeType)))
		applyStoreHeader(n, h)
		return n
	case KindConstructorType:
		n := f.NewConstructorTypeNode(expandModifierList(f, h.Store(), h.ListSlot(listSlotConstructorTypeNodeModifiers)), expandNodeList(f, h.Store(), h.ListSlot(listSlotConstructorTypeNodeTypeParameters)), expandNodeList(f, h.Store(), h.ListSlot(listSlotConstructorTypeNodeParameters)), expandStored(f, h.Child(slotConstructorTypeNodeType)))
		applyStoreHeader(n, h)
		return n
	case KindTemplateHead:
		n := f.NewTemplateHead(h.StringValue(valueSlotTemplateHeadText), h.StringValue(valueSlotTemplateHeadRawText), h.TokenFlags())
		applyStoreHeader(n, h)
		return n
	case KindTemplateMiddle:
		n := f.NewTemplateMiddle(h.StringValue(valueSlotTemplateMiddleText), h.StringValue(valueSlotTemplateMiddleRawText), h.TokenFlags())
		applyStoreHeader(n, h)
		return n
	case KindTemplateTail:
		n := f.NewTemplateTail(h.StringValue(valueSlotTemplateTailText), h.StringValue(valueSlotTemplateTailRawText), h.TokenFlags())
		applyStoreHeader(n, h)
		return n
	case KindTemplateLiteralType:
		n := f.NewTemplateLiteralTypeNode(expandStored(f, h.Child(slotTemplateLiteralTypeNodeHead)), expandNodeList(f, h.Store(), h.ListSlot(listSlotTemplateLiteralTypeNodeTemplateSpans)))
		applyStoreHeader(n, h)
		return n
	case KindTemplateLiteralTypeSpan:
		n := f.NewTemplateLiteralTypeSpan(expandStored(f, h.Child(slotTemplateLiteralTypeSpanType)), expandStored(f, h.Child(slotTemplateLiteralTypeSpanLiteral)))
		applyStoreHeader(n, h)
		return n
	case KindSyntheticExpression:
		n := f.NewSyntheticExpression(storeObjectValue[any](h, valueSlotSyntheticExpressionType), h.UintValue(valueSlotSyntheticExpressionIsSpread) != 0, expandStored(f, h.Child(slotSyntheticExpressionTupleNameSource)))
		applyStoreHeader(n, h)
		return n
	case KindPartiallyEmittedExpression:
		n := f.NewPartiallyEmittedExpression(expandStored(f, h.Child(slotPartiallyEmittedExpressionExpression)))
		applyStoreHeader(n, h)
		return n
	case KindJsxElement:
		n := f.NewJsxElement(expandStored(f, h.Child(slotJsxElementOpeningElement)), expandNodeList(f, h.Store(), h.ListSlot(listSlotJsxElementChildren)), expandStored(f, h.Child(slotJsxElementClosingElement)))
		applyStoreHeader(n, h)
		return n
	case KindJsxAttributes:
		n := f.NewJsxAttributes(expandNodeList(f, h.Store(), h.ListSlot(listSlotJsxAttributesProperties)))
		applyStoreHeader(n, h)
		return n
	case KindJsxNamespacedName:
		n := f.NewJsxNamespacedName(expandStored(f, h.Child(slotJsxNamespacedNameNamespace)), expandStored(f, h.Child(slotJsxNamespacedNameName)))
		applyStoreHeader(n, h)
		return n
	case KindJsxOpeningElement:
		n := f.NewJsxOpeningElement(expandStored(f, h.Child(slotJsxOpeningElementTagName)), expandNodeList(f, h.Store(), h.ListSlot(listSlotJsxOpeningElementTypeArguments)), expandStored(f, h.Child(slotJsxOpeningElementAttributes)))
		applyStoreHeader(n, h)
		return n
	case KindJsxSelfClosingElement:
		n := f.NewJsxSelfClosingElement(expandStored(f, h.Child(slotJsxSelfClosingElementTagName)), expandNodeList(f, h.Store(), h.ListSlot(listSlotJsxSelfClosingElementTypeArguments)), expandStored(f, h.Child(slotJsxSelfClosingElementAttributes)))
		applyStoreHeader(n, h)
		return n
	case KindJsxFragment:
		n := f.NewJsxFragment(expandStored(f, h.Child(slotJsxFragmentOpeningFragment)), expandNodeList(f, h.Store(), h.ListSlot(listSlotJsxFragmentChildren)), expandStored(f, h.Child(slotJsxFragmentClosingFragment)))
		applyStoreHeader(n, h)
		return n
	case KindJsxOpeningFragment:
		n := f.NewJsxOpeningFragment()
		applyStoreHeader(n, h)
		return n
	case KindJsxClosingFragment:
		n := f.NewJsxClosingFragment()
		applyStoreHeader(n, h)
		return n
	case KindJsxAttribute:
		n := f.NewJsxAttribute(expandStored(f, h.Child(slotJsxAttributeName)), expandStored(f, h.Child(slotJsxAttributeInitializer)))
		applyStoreHeader(n, h)
		return n
	case KindJsxSpreadAttribute:
		n := f.NewJsxSpreadAttribute(expandStored(f, h.Child(slotJsxSpreadAttributeExpression)))
		applyStoreHeader(n, h)
		return n
	case KindJsxClosingElement:
		n := f.NewJsxClosingElement(expandStored(f, h.Child(slotJsxClosingElementTagName)))
		applyStoreHeader(n, h)
		return n
	case KindJsxExpression:
		n := f.NewJsxExpression(expandStored(f, h.Child(slotJsxExpressionDotDotDotToken)), expandStored(f, h.Child(slotJsxExpressionExpression)))
		applyStoreHeader(n, h)
		return n
	case KindJsxText:
		n := f.NewJsxText(h.StringValue(valueSlotJsxTextText), h.UintValue(valueSlotJsxTextContainsOnlyTriviaWhiteSpaces) != 0)
		applyStoreHeader(n, h)
		return n
	case KindSyntaxList:
		n := f.NewSyntaxList(expandRawList(f, h.Store(), h.ListSlot(listSlotSyntaxListChildren)))
		applyStoreHeader(n, h)
		return n
	case KindJSDoc:
		n := f.NewJSDoc(expandNodeList(f, h.Store(), h.ListSlot(listSlotJSDocComment)), expandNodeList(f, h.Store(), h.ListSlot(listSlotJSDocTags)))
		applyStoreHeader(n, h)
		return n
	case KindJSDocTypeExpression:
		n := f.NewJSDocTypeExpression(expandStored(f, h.Child(slotJSDocTypeExpressionType)))
		applyStoreHeader(n, h)
		return n
	case KindJSDocNonNullableType:
		n := f.NewJSDocNonNullableType(expandStored(f, h.Child(slotJSDocNonNullableTypeType)))
		applyStoreHeader(n, h)
		return n
	case KindJSDocNullableType:
		n := f.NewJSDocNullableType(expandStored(f, h.Child(slotJSDocNullableTypeType)))
		applyStoreHeader(n, h)
		return n
	case KindJSDocAllType:
		n := f.NewJSDocAllType()
		applyStoreHeader(n, h)
		return n
	case KindJSDocVariadicType:
		n := f.NewJSDocVariadicType(expandStored(f, h.Child(slotJSDocVariadicTypeType)))
		applyStoreHeader(n, h)
		return n
	case KindJSDocOptionalType:
		n := f.NewJSDocOptionalType(expandStored(f, h.Child(slotJSDocOptionalTypeType)))
		applyStoreHeader(n, h)
		return n
	case KindJSDocTypeTag:
		n := f.NewJSDocTypeTag(expandStored(f, h.Child(slotJSDocTypeTagTagName)), expandStored(f, h.Child(slotJSDocTypeTagTypeExpression)), expandNodeList(f, h.Store(), h.ListSlot(listSlotJSDocTypeTagComment)))
		applyStoreHeader(n, h)
		return n
	case KindJSDocUnknownTag:
		n := f.NewJSDocUnknownTag(expandStored(f, h.Child(slotJSDocUnknownTagTagName)), expandNodeList(f, h.Store(), h.ListSlot(listSlotJSDocUnknownTagComment)))
		applyStoreHeader(n, h)
		return n
	case KindJSDocTemplateTag:
		n := f.NewJSDocTemplateTag(expandStored(f, h.Child(slotJSDocTemplateTagTagName)), expandStored(f, h.Child(slotJSDocTemplateTagConstraint)), expandNodeList(f, h.Store(), h.ListSlot(listSlotJSDocTemplateTagTypeParameters)), expandNodeList(f, h.Store(), h.ListSlot(listSlotJSDocTemplateTagComment)))
		applyStoreHeader(n, h)
		return n
	case KindJSDocReturnTag:
		n := f.NewJSDocReturnTag(expandStored(f, h.Child(slotJSDocReturnTagTagName)), expandStored(f, h.Child(slotJSDocReturnTagTypeExpression)), expandNodeList(f, h.Store(), h.ListSlot(listSlotJSDocReturnTagComment)))
		applyStoreHeader(n, h)
		return n
	case KindJSDocPublicTag:
		n := f.NewJSDocPublicTag(expandStored(f, h.Child(slotJSDocPublicTagTagName)), expandNodeList(f, h.Store(), h.ListSlot(listSlotJSDocPublicTagComment)))
		applyStoreHeader(n, h)
		return n
	case KindJSDocPrivateTag:
		n := f.NewJSDocPrivateTag(expandStored(f, h.Child(slotJSDocPrivateTagTagName)), expandNodeList(f, h.Store(), h.ListSlot(listSlotJSDocPrivateTagComment)))
		applyStoreHeader(n, h)
		return n
	case KindJSDocProtectedTag:
		n := f.NewJSDocProtectedTag(expandStored(f, h.Child(slotJSDocProtectedTagTagName)), expandNodeList(f, h.Store(), h.ListSlot(listSlotJSDocProtectedTagComment)))
		applyStoreHeader(n, h)
		return n
	case KindJSDocReadonlyTag:
		n := f.NewJSDocReadonlyTag(expandStored(f, h.Child(slotJSDocReadonlyTagTagName)), expandNodeList(f, h.Store(), h.ListSlot(listSlotJSDocReadonlyTagComment)))
		applyStoreHeader(n, h)
		return n
	case KindJSDocOverrideTag:
		n := f.NewJSDocOverrideTag(expandStored(f, h.Child(slotJSDocOverrideTagTagName)), expandNodeList(f, h.Store(), h.ListSlot(listSlotJSDocOverrideTagComment)))
		applyStoreHeader(n, h)
		return n
	case KindJSDocDeprecatedTag:
		n := f.NewJSDocDeprecatedTag(expandStored(f, h.Child(slotJSDocDeprecatedTagTagName)), expandNodeList(f, h.Store(), h.ListSlot(listSlotJSDocDeprecatedTagComment)))
		applyStoreHeader(n, h)
		return n
	case KindJSDocSeeTag:
		n := f.NewJSDocSeeTag(expandStored(f, h.Child(slotJSDocSeeTagTagName)), expandStored(f, h.Child(slotJSDocSeeTagNameExpression)), expandNodeList(f, h.Store(), h.ListSlot(listSlotJSDocSeeTagComment)))
		applyStoreHeader(n, h)
		return n
	case KindJSDocImplementsTag:
		n := f.NewJSDocImplementsTag(expandStored(f, h.Child(slotJSDocImplementsTagTagName)), expandStored(f, h.Child(slotJSDocImplementsTagClassName)), expandNodeList(f, h.Store(), h.ListSlot(listSlotJSDocImplementsTagComment)))
		applyStoreHeader(n, h)
		return n
	case KindJSDocAugmentsTag:
		n := f.NewJSDocAugmentsTag(expandStored(f, h.Child(slotJSDocAugmentsTagTagName)), expandStored(f, h.Child(slotJSDocAugmentsTagClassName)), expandNodeList(f, h.Store(), h.ListSlot(listSlotJSDocAugmentsTagComment)))
		applyStoreHeader(n, h)
		return n
	case KindJSDocSatisfiesTag:
		n := f.NewJSDocSatisfiesTag(expandStored(f, h.Child(slotJSDocSatisfiesTagTagName)), expandStored(f, h.Child(slotJSDocSatisfiesTagTypeExpression)), expandNodeList(f, h.Store(), h.ListSlot(listSlotJSDocSatisfiesTagComment)))
		applyStoreHeader(n, h)
		return n
	case KindJSDocThrowsTag:
		n := f.NewJSDocThrowsTag(expandStored(f, h.Child(slotJSDocThrowsTagTagName)), expandStored(f, h.Child(slotJSDocThrowsTagTypeExpression)), expandNodeList(f, h.Store(), h.ListSlot(listSlotJSDocThrowsTagComment)))
		applyStoreHeader(n, h)
		return n
	case KindJSDocThisTag:
		n := f.NewJSDocThisTag(expandStored(f, h.Child(slotJSDocThisTagTagName)), expandStored(f, h.Child(slotJSDocThisTagTypeExpression)), expandNodeList(f, h.Store(), h.ListSlot(listSlotJSDocThisTagComment)))
		applyStoreHeader(n, h)
		return n
	case KindJSDocImportTag:
		n := f.NewJSDocImportTag(expandStored(f, h.Child(slotJSDocImportTagTagName)), expandStored(f, h.Child(slotJSDocImportTagImportClause)), expandStored(f, h.Child(slotJSDocImportTagModuleSpecifier)), expandStored(f, h.Child(slotJSDocImportTagAttributes)), expandNodeList(f, h.Store(), h.ListSlot(listSlotJSDocImportTagComment)))
		applyStoreHeader(n, h)
		return n
	case KindJSDocCallbackTag:
		n := f.NewJSDocCallbackTag(expandStored(f, h.Child(slotJSDocCallbackTagTagName)), expandStored(f, h.Child(slotJSDocCallbackTagTypeExpression)), expandStored(f, h.Child(slotJSDocCallbackTagName)), expandNodeList(f, h.Store(), h.ListSlot(listSlotJSDocCallbackTagComment)))
		applyStoreHeader(n, h)
		return n
	case KindJSDocOverloadTag:
		n := f.NewJSDocOverloadTag(expandStored(f, h.Child(slotJSDocOverloadTagTagName)), expandStored(f, h.Child(slotJSDocOverloadTagTypeExpression)), expandNodeList(f, h.Store(), h.ListSlot(listSlotJSDocOverloadTagComment)))
		applyStoreHeader(n, h)
		return n
	case KindJSDocTypedefTag:
		n := f.NewJSDocTypedefTag(expandStored(f, h.Child(slotJSDocTypedefTagTagName)), expandStored(f, h.Child(slotJSDocTypedefTagTypeExpression)), expandStored(f, h.Child(slotJSDocTypedefTagName)), expandNodeList(f, h.Store(), h.ListSlot(listSlotJSDocTypedefTagComment)))
		applyStoreHeader(n, h)
		return n
	case KindJSDocSignature:
		n := f.NewJSDocSignature(expandNodeList(f, h.Store(), h.ListSlot(listSlotJSDocSignatureTypeParameters)), expandNodeList(f, h.Store(), h.ListSlot(listSlotJSDocSignatureParameters)), expandStored(f, h.Child(slotJSDocSignatureType)))
		applyStoreHeader(n, h)
		return n
	case KindJSDocNameReference:
		n := f.NewJSDocNameReference(expandStored(f, h.Child(slotJSDocNameReferenceName)))
		applyStoreHeader(n, h)
		return n
	case KindModuleDeclaration:
		n := f.NewModuleDeclaration(expandModifierList(f, h.Store(), h.ListSlot(listSlotModuleDeclarationModifiers)), Kind(h.UintValue(valueSlotModuleDeclarationKeyword)), expandStored(f, h.Child(slotModuleDeclarationName)), expandStored(f, h.Child(slotModuleDeclarationBody)))
		applyStoreHeader(n, h)
		return n
	case KindImportEqualsDeclaration:
		n := f.NewImportEqualsDeclaration(expandModifierList(f, h.Store(), h.ListSlot(listSlotImportEqualsDeclarationModifiers)), h.UintValue(valueSlotImportEqualsDeclarationIsTypeOnly) != 0, expandStored(f, h.Child(slotImportEqualsDeclarationName)), expandStored(f, h.Child(slotImportEqualsDeclarationModuleReference)))
		applyStoreHeader(n, h)
		return n
	case KindExportDeclaration:
		n := f.NewExportDeclaration(expandModifierList(f, h.Store(), h.ListSlot(listSlotExportDeclarationModifiers)), h.UintValue(valueSlotExportDeclarationIsTypeOnly) != 0, expandStored(f, h.Child(slotExportDeclarationExportClause)), expandStored(f, h.Child(slotExportDeclarationModuleSpecifier)), expandStored(f, h.Child(slotExportDeclarationAttributes)))
		applyStoreHeader(n, h)
		return n
	case KindImportType:
		n := f.NewImportTypeNode(h.UintValue(valueSlotImportTypeNodeIsTypeOf) != 0, expandStored(f, h.Child(slotImportTypeNodeArgument)), expandStored(f, h.Child(slotImportTypeNodeAttributes)), expandStored(f, h.Child(slotImportTypeNodeQualifier)), expandNodeList(f, h.Store(), h.ListSlot(listSlotImportTypeNodeTypeArguments)))
		applyStoreHeader(n, h)
		return n
	case KindImportClause:
		n := f.NewImportClause(ImportPhaseModifierSyntaxKind(h.UintValue(valueSlotImportClausePhaseModifier)), expandStored(f, h.Child(slotImportClauseName)), expandStored(f, h.Child(slotImportClauseNamedBindings)))
		applyStoreHeader(n, h)
		return n
	case KindImportSpecifier:
		n := f.NewImportSpecifier(h.UintValue(valueSlotImportSpecifierIsTypeOnly) != 0, expandStored(f, h.Child(slotImportSpecifierPropertyName)), expandStored(f, h.Child(slotImportSpecifierName)))
		applyStoreHeader(n, h)
		return n
	case KindJSDocText:
		n := f.NewJSDocText(storeObjectValue[[]string](h, valueSlotJSDocTextText))
		applyStoreHeader(n, h)
		return n
	case KindJSDocLink:
		n := f.NewJSDocLink(expandStored(f, h.Child(slotJSDocLinkName)), storeObjectValue[[]string](h, valueSlotJSDocLinkText))
		applyStoreHeader(n, h)
		return n
	case KindJSDocLinkPlain:
		n := f.NewJSDocLinkPlain(expandStored(f, h.Child(slotJSDocLinkPlainName)), storeObjectValue[[]string](h, valueSlotJSDocLinkPlainText))
		applyStoreHeader(n, h)
		return n
	case KindJSDocLinkCode:
		n := f.NewJSDocLinkCode(expandStored(f, h.Child(slotJSDocLinkCodeName)), storeObjectValue[[]string](h, valueSlotJSDocLinkCodeText))
		applyStoreHeader(n, h)
		return n
	case KindTypeParameter:
		n := f.NewTypeParameterDeclaration(expandModifierList(f, h.Store(), h.ListSlot(listSlotTypeParameterDeclarationModifiers)), expandStored(f, h.Child(slotTypeParameterDeclarationName)), expandStored(f, h.Child(slotTypeParameterDeclarationConstraint)), expandStored(f, h.Child(slotTypeParameterDeclarationExpression)), expandStored(f, h.Child(slotTypeParameterDeclarationDefaultType)))
		applyStoreHeader(n, h)
		return n
	case KindSyntheticReferenceExpression:
		n := f.NewSyntheticReferenceExpression(expandStored(f, h.Child(slotSyntheticReferenceExpressionExpression)), expandStored(f, h.Child(slotSyntheticReferenceExpressionThisArg)))
		applyStoreHeader(n, h)
		return n
	case KindJSDocTypeLiteral:
		n := f.NewJSDocTypeLiteral(expandRawList(f, h.Store(), h.ListSlot(listSlotJSDocTypeLiteralJSDocPropertyTags)), h.UintValue(valueSlotJSDocTypeLiteralIsArrayType) != 0)
		applyStoreHeader(n, h)
		return n
	case KindJSDocParameterTag, KindJSDocPropertyTag:
		n := f.NewJSDocParameterOrPropertyTag(h.Kind(), expandStored(f, h.Child(slotJSDocParameterOrPropertyTagTagName)), expandStored(f, h.Child(slotJSDocParameterOrPropertyTagName)), h.UintValue(valueSlotJSDocParameterOrPropertyTagIsBracketed) != 0, expandStored(f, h.Child(slotJSDocParameterOrPropertyTagTypeExpression)), h.UintValue(valueSlotJSDocParameterOrPropertyTagIsNameFirst) != 0, expandNodeList(f, h.Store(), h.ListSlot(listSlotJSDocParameterOrPropertyTagComment)))
		applyStoreHeader(n, h)
		return n
	default:
		if IsTokenKind(h.Kind()) {
			n := f.NewToken(h.Kind())
			applyStoreHeader(n, h)
			return n
		}
		panic("ast: no Store expander for " + h.Kind().String())
	}
}
