// Code generated by tools/scripts/tsc/generate-go-ast.ts. DO NOT EDIT.

package ast

func (node Handle) forEachChildSchema(v StoreVisitor) bool {
	switch node.Kind {
	case KindQualifiedName:
		if child := node.QualifiedNameLeft(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.QualifiedNameRight(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindComputedPropertyName:
		if child := node.ComputedPropertyNameExpression(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindDecorator:
		if child := node.DecoratorExpression(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindIfStatement:
		if child := node.IfStatementExpression(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.IfStatementThenStatement(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.IfStatementElseStatement(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindDoStatement:
		if child := node.DoStatementStatement(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.DoStatementExpression(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindWhileStatement:
		if child := node.WhileStatementExpression(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.WhileStatementStatement(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindForStatement:
		if child := node.ForStatementInitializer(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.ForStatementCondition(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.ForStatementIncrementor(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.ForStatementStatement(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindForInStatement, KindForOfStatement:
		if child := node.ForInOrOfStatementAwaitModifier(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.ForInOrOfStatementInitializer(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.ForInOrOfStatementExpression(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.ForInOrOfStatementStatement(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindBreakStatement:
		if child := node.BreakStatementLabel(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindContinueStatement:
		if child := node.ContinueStatementLabel(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindReturnStatement:
		if child := node.ReturnStatementExpression(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindWithStatement:
		if child := node.WithStatementExpression(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.WithStatementStatement(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindSwitchStatement:
		if child := node.SwitchStatementExpression(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.SwitchStatementCaseBlock(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindCaseBlock:
		if node.forEachChildList(node.CaseBlockClauses(), v) {
			return true
		}
		return false
	case KindCaseClause, KindDefaultClause:
		if child := node.CaseOrDefaultClauseExpression(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.CaseOrDefaultClauseStatements(), v) {
			return true
		}
		return false
	case KindThrowStatement:
		if child := node.ThrowStatementExpression(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindTryStatement:
		if child := node.TryStatementTryBlock(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.TryStatementCatchClause(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.TryStatementFinallyBlock(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindCatchClause:
		if child := node.CatchClauseVariableDeclaration(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.CatchClauseBlock(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindLabeledStatement:
		if child := node.LabeledStatementLabel(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.LabeledStatementStatement(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindExpressionStatement:
		if child := node.ExpressionStatementExpression(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindBlock:
		if node.forEachChildList(node.BlockStatements(), v) {
			return true
		}
		return false
	case KindVariableStatement:
		if node.forEachChildList(node.VariableStatementModifiers(), v) {
			return true
		}
		if child := node.VariableStatementDeclarationList(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindVariableDeclaration:
		if child := node.VariableDeclarationName(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.VariableDeclarationExclamationToken(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.VariableDeclarationType(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.VariableDeclarationInitializer(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindVariableDeclarationList:
		if node.forEachChildList(node.VariableDeclarationListDeclarations(), v) {
			return true
		}
		return false
	case KindObjectBindingPattern, KindArrayBindingPattern:
		if node.forEachChildList(node.BindingPatternElements(), v) {
			return true
		}
		return false
	case KindParameter:
		if node.forEachChildList(node.ParameterDeclarationModifiers(), v) {
			return true
		}
		if child := node.ParameterDeclarationDotDotDotToken(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.ParameterDeclarationName(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.ParameterDeclarationQuestionToken(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.ParameterDeclarationType(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.ParameterDeclarationInitializer(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindBindingElement:
		if child := node.BindingElementDotDotDotToken(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.BindingElementPropertyName(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.BindingElementName(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.BindingElementInitializer(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindMissingDeclaration:
		if node.forEachChildList(node.MissingDeclarationModifiers(), v) {
			return true
		}
		return false
	case KindFunctionDeclaration:
		if node.forEachChildList(node.FunctionDeclarationModifiers(), v) {
			return true
		}
		if child := node.FunctionDeclarationAsteriskToken(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.FunctionDeclarationName(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.FunctionDeclarationTypeParameters(), v) {
			return true
		}
		if node.forEachChildList(node.FunctionDeclarationParameters(), v) {
			return true
		}
		if child := node.FunctionDeclarationType(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.FunctionDeclarationFullSignature(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.FunctionDeclarationBody(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindClassDeclaration:
		if node.forEachChildList(node.ClassDeclarationModifiers(), v) {
			return true
		}
		if child := node.ClassDeclarationName(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.ClassDeclarationTypeParameters(), v) {
			return true
		}
		if node.forEachChildList(node.ClassDeclarationHeritageClauses(), v) {
			return true
		}
		if node.forEachChildList(node.ClassDeclarationMembers(), v) {
			return true
		}
		return false
	case KindClassExpression:
		if node.forEachChildList(node.ClassExpressionModifiers(), v) {
			return true
		}
		if child := node.ClassExpressionName(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.ClassExpressionTypeParameters(), v) {
			return true
		}
		if node.forEachChildList(node.ClassExpressionHeritageClauses(), v) {
			return true
		}
		if node.forEachChildList(node.ClassExpressionMembers(), v) {
			return true
		}
		return false
	case KindHeritageClause:
		if node.forEachChildList(node.HeritageClauseTypes(), v) {
			return true
		}
		return false
	case KindInterfaceDeclaration:
		if node.forEachChildList(node.InterfaceDeclarationModifiers(), v) {
			return true
		}
		if child := node.InterfaceDeclarationName(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.InterfaceDeclarationTypeParameters(), v) {
			return true
		}
		if node.forEachChildList(node.InterfaceDeclarationHeritageClauses(), v) {
			return true
		}
		if node.forEachChildList(node.InterfaceDeclarationMembers(), v) {
			return true
		}
		return false
	case KindTypeAliasDeclaration, KindJSTypeAliasDeclaration:
		if node.forEachChildList(node.TypeAliasDeclarationModifiers(), v) {
			return true
		}
		if child := node.TypeAliasDeclarationName(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.TypeAliasDeclarationTypeParameters(), v) {
			return true
		}
		if child := node.TypeAliasDeclarationType(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindEnumMember:
		if child := node.EnumMemberName(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.EnumMemberInitializer(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindEnumDeclaration:
		if node.forEachChildList(node.EnumDeclarationModifiers(), v) {
			return true
		}
		if child := node.EnumDeclarationName(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.EnumDeclarationMembers(), v) {
			return true
		}
		return false
	case KindModuleBlock:
		if node.forEachChildList(node.ModuleBlockStatements(), v) {
			return true
		}
		return false
	case KindImportDeclaration, KindJSImportDeclaration:
		if node.forEachChildList(node.ImportDeclarationModifiers(), v) {
			return true
		}
		if child := node.ImportDeclarationImportClause(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.ImportDeclarationModuleSpecifier(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.ImportDeclarationAttributes(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindExternalModuleReference:
		if child := node.ExternalModuleReferenceExpression(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindNamespaceImport:
		if child := node.NamespaceImportName(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindNamedImports:
		if node.forEachChildList(node.NamedImportsElements(), v) {
			return true
		}
		return false
	case KindExportAssignment:
		if node.forEachChildList(node.ExportAssignmentModifiers(), v) {
			return true
		}
		if child := node.ExportAssignmentType(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.ExportAssignmentExpression(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindNamespaceExportDeclaration:
		if node.forEachChildList(node.NamespaceExportDeclarationModifiers(), v) {
			return true
		}
		if child := node.NamespaceExportDeclarationName(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindNamespaceExport:
		if child := node.NamespaceExportName(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindNamedExports:
		if node.forEachChildList(node.NamedExportsElements(), v) {
			return true
		}
		return false
	case KindExportSpecifier:
		if child := node.ExportSpecifierPropertyName(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.ExportSpecifierName(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindCallSignature:
		if node.forEachChildList(node.CallSignatureDeclarationTypeParameters(), v) {
			return true
		}
		if node.forEachChildList(node.CallSignatureDeclarationParameters(), v) {
			return true
		}
		if child := node.CallSignatureDeclarationType(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindConstructSignature:
		if node.forEachChildList(node.ConstructSignatureDeclarationTypeParameters(), v) {
			return true
		}
		if node.forEachChildList(node.ConstructSignatureDeclarationParameters(), v) {
			return true
		}
		if child := node.ConstructSignatureDeclarationType(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindConstructor:
		if node.forEachChildList(node.ConstructorDeclarationModifiers(), v) {
			return true
		}
		if node.forEachChildList(node.ConstructorDeclarationTypeParameters(), v) {
			return true
		}
		if node.forEachChildList(node.ConstructorDeclarationParameters(), v) {
			return true
		}
		if child := node.ConstructorDeclarationType(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.ConstructorDeclarationFullSignature(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.ConstructorDeclarationBody(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindGetAccessor:
		if node.forEachChildList(node.GetAccessorDeclarationModifiers(), v) {
			return true
		}
		if child := node.GetAccessorDeclarationName(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.GetAccessorDeclarationTypeParameters(), v) {
			return true
		}
		if node.forEachChildList(node.GetAccessorDeclarationParameters(), v) {
			return true
		}
		if child := node.GetAccessorDeclarationType(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.GetAccessorDeclarationFullSignature(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.GetAccessorDeclarationBody(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindSetAccessor:
		if node.forEachChildList(node.SetAccessorDeclarationModifiers(), v) {
			return true
		}
		if child := node.SetAccessorDeclarationName(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.SetAccessorDeclarationTypeParameters(), v) {
			return true
		}
		if node.forEachChildList(node.SetAccessorDeclarationParameters(), v) {
			return true
		}
		if child := node.SetAccessorDeclarationType(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.SetAccessorDeclarationFullSignature(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.SetAccessorDeclarationBody(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindIndexSignature:
		if node.forEachChildList(node.IndexSignatureDeclarationModifiers(), v) {
			return true
		}
		if node.forEachChildList(node.IndexSignatureDeclarationParameters(), v) {
			return true
		}
		if child := node.IndexSignatureDeclarationType(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindMethodSignature:
		if node.forEachChildList(node.MethodSignatureDeclarationModifiers(), v) {
			return true
		}
		if child := node.MethodSignatureDeclarationName(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.MethodSignatureDeclarationPostfixToken(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.MethodSignatureDeclarationTypeParameters(), v) {
			return true
		}
		if node.forEachChildList(node.MethodSignatureDeclarationParameters(), v) {
			return true
		}
		if child := node.MethodSignatureDeclarationType(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindMethodDeclaration:
		if node.forEachChildList(node.MethodDeclarationModifiers(), v) {
			return true
		}
		if child := node.MethodDeclarationAsteriskToken(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.MethodDeclarationName(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.MethodDeclarationPostfixToken(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.MethodDeclarationTypeParameters(), v) {
			return true
		}
		if node.forEachChildList(node.MethodDeclarationParameters(), v) {
			return true
		}
		if child := node.MethodDeclarationType(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.MethodDeclarationFullSignature(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.MethodDeclarationBody(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindPropertySignature:
		if node.forEachChildList(node.PropertySignatureDeclarationModifiers(), v) {
			return true
		}
		if child := node.PropertySignatureDeclarationName(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.PropertySignatureDeclarationPostfixToken(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.PropertySignatureDeclarationType(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.PropertySignatureDeclarationInitializer(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindPropertyDeclaration:
		if node.forEachChildList(node.PropertyDeclarationModifiers(), v) {
			return true
		}
		if child := node.PropertyDeclarationName(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.PropertyDeclarationPostfixToken(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.PropertyDeclarationType(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.PropertyDeclarationInitializer(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindClassStaticBlockDeclaration:
		if node.forEachChildList(node.ClassStaticBlockDeclarationModifiers(), v) {
			return true
		}
		if child := node.ClassStaticBlockDeclarationBody(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindBinaryExpression:
		if node.forEachChildList(node.BinaryExpressionModifiers(), v) {
			return true
		}
		if child := node.BinaryExpressionLeft(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.BinaryExpressionType(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.BinaryExpressionOperatorToken(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.BinaryExpressionRight(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindPrefixUnaryExpression:
		if child := node.PrefixUnaryExpressionOperand(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindPostfixUnaryExpression:
		if child := node.PostfixUnaryExpressionOperand(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindYieldExpression:
		if child := node.YieldExpressionAsteriskToken(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.YieldExpressionExpression(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindArrowFunction:
		if node.forEachChildList(node.ArrowFunctionModifiers(), v) {
			return true
		}
		if node.forEachChildList(node.ArrowFunctionTypeParameters(), v) {
			return true
		}
		if node.forEachChildList(node.ArrowFunctionParameters(), v) {
			return true
		}
		if child := node.ArrowFunctionType(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.ArrowFunctionFullSignature(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.ArrowFunctionEqualsGreaterThanToken(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.ArrowFunctionBody(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindFunctionExpression:
		if node.forEachChildList(node.FunctionExpressionModifiers(), v) {
			return true
		}
		if child := node.FunctionExpressionAsteriskToken(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.FunctionExpressionName(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.FunctionExpressionTypeParameters(), v) {
			return true
		}
		if node.forEachChildList(node.FunctionExpressionParameters(), v) {
			return true
		}
		if child := node.FunctionExpressionType(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.FunctionExpressionFullSignature(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.FunctionExpressionBody(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindAsExpression:
		if child := node.AsExpressionExpression(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.AsExpressionType(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindSatisfiesExpression:
		if child := node.SatisfiesExpressionExpression(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.SatisfiesExpressionType(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindConditionalExpression:
		if child := node.ConditionalExpressionCondition(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.ConditionalExpressionQuestionToken(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.ConditionalExpressionWhenTrue(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.ConditionalExpressionColonToken(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.ConditionalExpressionWhenFalse(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindPropertyAccessExpression:
		if child := node.PropertyAccessExpressionExpression(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.PropertyAccessExpressionQuestionDotToken(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.PropertyAccessExpressionName(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindElementAccessExpression:
		if child := node.ElementAccessExpressionExpression(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.ElementAccessExpressionQuestionDotToken(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.ElementAccessExpressionArgumentExpression(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindCallExpression:
		if child := node.CallExpressionExpression(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.CallExpressionQuestionDotToken(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.CallExpressionTypeArguments(), v) {
			return true
		}
		if node.forEachChildList(node.CallExpressionArguments(), v) {
			return true
		}
		return false
	case KindNewExpression:
		if child := node.NewExpressionExpression(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.NewExpressionTypeArguments(), v) {
			return true
		}
		if node.forEachChildList(node.NewExpressionArguments(), v) {
			return true
		}
		return false
	case KindMetaProperty:
		if child := node.MetaPropertyName(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindNonNullExpression:
		if child := node.NonNullExpressionExpression(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindSpreadElement:
		if child := node.SpreadElementExpression(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindTemplateExpression:
		if child := node.TemplateExpressionHead(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.TemplateExpressionTemplateSpans(), v) {
			return true
		}
		return false
	case KindTemplateSpan:
		if child := node.TemplateSpanExpression(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.TemplateSpanLiteral(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindTaggedTemplateExpression:
		if child := node.TaggedTemplateExpressionTag(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.TaggedTemplateExpressionQuestionDotToken(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.TaggedTemplateExpressionTypeArguments(), v) {
			return true
		}
		if child := node.TaggedTemplateExpressionTemplate(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindParenthesizedExpression:
		if child := node.ParenthesizedExpressionExpression(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindArrayLiteralExpression:
		if node.forEachChildList(node.ArrayLiteralExpressionElements(), v) {
			return true
		}
		return false
	case KindObjectLiteralExpression:
		if node.forEachChildList(node.ObjectLiteralExpressionProperties(), v) {
			return true
		}
		return false
	case KindSpreadAssignment:
		if child := node.SpreadAssignmentExpression(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindPropertyAssignment:
		if node.forEachChildList(node.PropertyAssignmentModifiers(), v) {
			return true
		}
		if child := node.PropertyAssignmentName(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.PropertyAssignmentPostfixToken(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.PropertyAssignmentType(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.PropertyAssignmentInitializer(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindShorthandPropertyAssignment:
		if node.forEachChildList(node.ShorthandPropertyAssignmentModifiers(), v) {
			return true
		}
		if child := node.ShorthandPropertyAssignmentName(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.ShorthandPropertyAssignmentPostfixToken(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.ShorthandPropertyAssignmentType(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.ShorthandPropertyAssignmentEqualsToken(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.ShorthandPropertyAssignmentObjectAssignmentInitializer(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindDeleteExpression:
		if child := node.DeleteExpressionExpression(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindTypeOfExpression:
		if child := node.TypeOfExpressionExpression(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindVoidExpression:
		if child := node.VoidExpressionExpression(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindAwaitExpression:
		if child := node.AwaitExpressionExpression(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindTypeAssertionExpression:
		if child := node.TypeAssertionType(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.TypeAssertionExpression(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindUnionType:
		if node.forEachChildList(node.UnionTypeNodeTypes(), v) {
			return true
		}
		return false
	case KindIntersectionType:
		if node.forEachChildList(node.IntersectionTypeNodeTypes(), v) {
			return true
		}
		return false
	case KindConditionalType:
		if child := node.ConditionalTypeNodeCheckType(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.ConditionalTypeNodeExtendsType(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.ConditionalTypeNodeTrueType(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.ConditionalTypeNodeFalseType(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindTypeOperator:
		if child := node.TypeOperatorNodeType(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindInferType:
		if child := node.InferTypeNodeTypeParameter(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindArrayType:
		if child := node.ArrayTypeNodeElementType(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindIndexedAccessType:
		if child := node.IndexedAccessTypeNodeObjectType(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.IndexedAccessTypeNodeIndexType(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindTypeReference:
		if child := node.TypeReferenceNodeTypeName(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.TypeReferenceNodeTypeArguments(), v) {
			return true
		}
		return false
	case KindExpressionWithTypeArguments:
		if child := node.ExpressionWithTypeArgumentsExpression(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.ExpressionWithTypeArgumentsTypeArguments(), v) {
			return true
		}
		return false
	case KindLiteralType:
		if child := node.LiteralTypeNodeLiteral(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindTypePredicate:
		if child := node.TypePredicateNodeAssertsModifier(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.TypePredicateNodeParameterName(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.TypePredicateNodeType(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindImportAttribute:
		if child := node.ImportAttributeName(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.ImportAttributeValue(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindImportAttributes:
		if node.forEachChildList(node.ImportAttributesAttributes(), v) {
			return true
		}
		return false
	case KindTypeQuery:
		if child := node.TypeQueryNodeExprName(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.TypeQueryNodeTypeArguments(), v) {
			return true
		}
		return false
	case KindMappedType:
		if child := node.MappedTypeNodeReadonlyToken(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.MappedTypeNodeTypeParameter(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.MappedTypeNodeNameType(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.MappedTypeNodeQuestionToken(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.MappedTypeNodeType(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.MappedTypeNodeMembers(), v) {
			return true
		}
		return false
	case KindTypeLiteral:
		if node.forEachChildList(node.TypeLiteralNodeMembers(), v) {
			return true
		}
		return false
	case KindTupleType:
		if node.forEachChildList(node.TupleTypeNodeElements(), v) {
			return true
		}
		return false
	case KindNamedTupleMember:
		if child := node.NamedTupleMemberDotDotDotToken(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.NamedTupleMemberName(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.NamedTupleMemberQuestionToken(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.NamedTupleMemberType(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindOptionalType:
		if child := node.OptionalTypeNodeType(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindRestType:
		if child := node.RestTypeNodeType(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindParenthesizedType:
		if child := node.ParenthesizedTypeNodeType(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindFunctionType:
		if node.forEachChildList(node.FunctionTypeNodeTypeParameters(), v) {
			return true
		}
		if node.forEachChildList(node.FunctionTypeNodeParameters(), v) {
			return true
		}
		if child := node.FunctionTypeNodeType(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindConstructorType:
		if node.forEachChildList(node.ConstructorTypeNodeModifiers(), v) {
			return true
		}
		if node.forEachChildList(node.ConstructorTypeNodeTypeParameters(), v) {
			return true
		}
		if node.forEachChildList(node.ConstructorTypeNodeParameters(), v) {
			return true
		}
		if child := node.ConstructorTypeNodeType(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindTemplateLiteralType:
		if child := node.TemplateLiteralTypeNodeHead(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.TemplateLiteralTypeNodeTemplateSpans(), v) {
			return true
		}
		return false
	case KindTemplateLiteralTypeSpan:
		if child := node.TemplateLiteralTypeSpanType(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.TemplateLiteralTypeSpanLiteral(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindSyntheticExpression:
		if child := node.SyntheticExpressionTupleNameSource(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindPartiallyEmittedExpression:
		if child := node.PartiallyEmittedExpressionExpression(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindJsxElement:
		if child := node.JsxElementOpeningElement(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.JsxElementChildren(), v) {
			return true
		}
		if child := node.JsxElementClosingElement(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindJsxAttributes:
		if node.forEachChildList(node.JsxAttributesProperties(), v) {
			return true
		}
		return false
	case KindJsxNamespacedName:
		if child := node.JsxNamespacedNameNamespace(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.JsxNamespacedNameName(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindJsxOpeningElement:
		if child := node.JsxOpeningElementTagName(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.JsxOpeningElementTypeArguments(), v) {
			return true
		}
		if child := node.JsxOpeningElementAttributes(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindJsxSelfClosingElement:
		if child := node.JsxSelfClosingElementTagName(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.JsxSelfClosingElementTypeArguments(), v) {
			return true
		}
		if child := node.JsxSelfClosingElementAttributes(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindJsxFragment:
		if child := node.JsxFragmentOpeningFragment(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.JsxFragmentChildren(), v) {
			return true
		}
		if child := node.JsxFragmentClosingFragment(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindJsxAttribute:
		if child := node.JsxAttributeName(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.JsxAttributeInitializer(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindJsxSpreadAttribute:
		if child := node.JsxSpreadAttributeExpression(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindJsxClosingElement:
		if child := node.JsxClosingElementTagName(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindJsxExpression:
		if child := node.JsxExpressionDotDotDotToken(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.JsxExpressionExpression(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindSyntaxList:
		if node.forEachChildList(node.SyntaxListChildren(), v) {
			return true
		}
		return false
	case KindJSDoc:
		if node.forEachChildList(node.JSDocComment(), v) {
			return true
		}
		if node.forEachChildList(node.JSDocTags(), v) {
			return true
		}
		return false
	case KindJSDocTypeExpression:
		if child := node.JSDocTypeExpressionType(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindJSDocNonNullableType:
		if child := node.JSDocNonNullableTypeType(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindJSDocNullableType:
		if child := node.JSDocNullableTypeType(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindJSDocVariadicType:
		if child := node.JSDocVariadicTypeType(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindJSDocOptionalType:
		if child := node.JSDocOptionalTypeType(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindJSDocTypeTag:
		if child := node.JSDocTypeTagTagName(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.JSDocTypeTagTypeExpression(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.JSDocTypeTagComment(), v) {
			return true
		}
		return false
	case KindJSDocUnknownTag:
		if child := node.JSDocUnknownTagTagName(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.JSDocUnknownTagComment(), v) {
			return true
		}
		return false
	case KindJSDocTemplateTag:
		if child := node.JSDocTemplateTagTagName(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.JSDocTemplateTagConstraint(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.JSDocTemplateTagTypeParameters(), v) {
			return true
		}
		if node.forEachChildList(node.JSDocTemplateTagComment(), v) {
			return true
		}
		return false
	case KindJSDocReturnTag:
		if child := node.JSDocReturnTagTagName(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.JSDocReturnTagTypeExpression(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.JSDocReturnTagComment(), v) {
			return true
		}
		return false
	case KindJSDocPublicTag:
		if child := node.JSDocPublicTagTagName(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.JSDocPublicTagComment(), v) {
			return true
		}
		return false
	case KindJSDocPrivateTag:
		if child := node.JSDocPrivateTagTagName(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.JSDocPrivateTagComment(), v) {
			return true
		}
		return false
	case KindJSDocProtectedTag:
		if child := node.JSDocProtectedTagTagName(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.JSDocProtectedTagComment(), v) {
			return true
		}
		return false
	case KindJSDocReadonlyTag:
		if child := node.JSDocReadonlyTagTagName(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.JSDocReadonlyTagComment(), v) {
			return true
		}
		return false
	case KindJSDocOverrideTag:
		if child := node.JSDocOverrideTagTagName(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.JSDocOverrideTagComment(), v) {
			return true
		}
		return false
	case KindJSDocDeprecatedTag:
		if child := node.JSDocDeprecatedTagTagName(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.JSDocDeprecatedTagComment(), v) {
			return true
		}
		return false
	case KindJSDocSeeTag:
		if child := node.JSDocSeeTagTagName(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.JSDocSeeTagNameExpression(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.JSDocSeeTagComment(), v) {
			return true
		}
		return false
	case KindJSDocImplementsTag:
		if child := node.JSDocImplementsTagTagName(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.JSDocImplementsTagClassName(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.JSDocImplementsTagComment(), v) {
			return true
		}
		return false
	case KindJSDocAugmentsTag:
		if child := node.JSDocAugmentsTagTagName(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.JSDocAugmentsTagClassName(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.JSDocAugmentsTagComment(), v) {
			return true
		}
		return false
	case KindJSDocSatisfiesTag:
		if child := node.JSDocSatisfiesTagTagName(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.JSDocSatisfiesTagTypeExpression(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.JSDocSatisfiesTagComment(), v) {
			return true
		}
		return false
	case KindJSDocThrowsTag:
		if child := node.JSDocThrowsTagTagName(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.JSDocThrowsTagTypeExpression(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.JSDocThrowsTagComment(), v) {
			return true
		}
		return false
	case KindJSDocThisTag:
		if child := node.JSDocThisTagTagName(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.JSDocThisTagTypeExpression(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.JSDocThisTagComment(), v) {
			return true
		}
		return false
	case KindJSDocImportTag:
		if child := node.JSDocImportTagTagName(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.JSDocImportTagImportClause(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.JSDocImportTagModuleSpecifier(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.JSDocImportTagAttributes(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.JSDocImportTagComment(), v) {
			return true
		}
		return false
	case KindJSDocCallbackTag:
		if child := node.JSDocCallbackTagTagName(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.JSDocCallbackTagTypeExpression(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.JSDocCallbackTagName(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.JSDocCallbackTagComment(), v) {
			return true
		}
		return false
	case KindJSDocOverloadTag:
		if child := node.JSDocOverloadTagTagName(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.JSDocOverloadTagTypeExpression(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.JSDocOverloadTagComment(), v) {
			return true
		}
		return false
	case KindJSDocTypedefTag:
		if child := node.JSDocTypedefTagTagName(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.JSDocTypedefTagTypeExpression(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.JSDocTypedefTagName(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.JSDocTypedefTagComment(), v) {
			return true
		}
		return false
	case KindJSDocSignature:
		if node.forEachChildList(node.JSDocSignatureTypeParameters(), v) {
			return true
		}
		if node.forEachChildList(node.JSDocSignatureParameters(), v) {
			return true
		}
		if child := node.JSDocSignatureType(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindJSDocNameReference:
		if child := node.JSDocNameReferenceName(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindSourceFile:
		if node.forEachChildList(node.SourceFileStatements(), v) {
			return true
		}
		if child := node.SourceFileEndOfFileToken(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindModuleDeclaration:
		if node.forEachChildList(node.ModuleDeclarationModifiers(), v) {
			return true
		}
		if child := node.ModuleDeclarationName(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.ModuleDeclarationBody(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindImportEqualsDeclaration:
		if node.forEachChildList(node.ImportEqualsDeclarationModifiers(), v) {
			return true
		}
		if child := node.ImportEqualsDeclarationName(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.ImportEqualsDeclarationModuleReference(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindExportDeclaration:
		if node.forEachChildList(node.ExportDeclarationModifiers(), v) {
			return true
		}
		if child := node.ExportDeclarationExportClause(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.ExportDeclarationModuleSpecifier(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.ExportDeclarationAttributes(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindImportType:
		if child := node.ImportTypeNodeArgument(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.ImportTypeNodeAttributes(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.ImportTypeNodeQualifier(); !child.IsNil() && v(child) {
			return true
		}
		if node.forEachChildList(node.ImportTypeNodeTypeArguments(), v) {
			return true
		}
		return false
	case KindImportClause:
		if child := node.ImportClauseName(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.ImportClauseNamedBindings(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindImportSpecifier:
		if child := node.ImportSpecifierPropertyName(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.ImportSpecifierName(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindJSDocLink:
		if child := node.JSDocLinkName(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindJSDocLinkPlain:
		if child := node.JSDocLinkPlainName(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindJSDocLinkCode:
		if child := node.JSDocLinkCodeName(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindTypeParameter:
		if node.forEachChildList(node.TypeParameterDeclarationModifiers(), v) {
			return true
		}
		if child := node.TypeParameterDeclarationName(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.TypeParameterDeclarationConstraint(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.TypeParameterDeclarationExpression(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.TypeParameterDeclarationDefaultType(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindSyntheticReferenceExpression:
		if child := node.SyntheticReferenceExpressionExpression(); !child.IsNil() && v(child) {
			return true
		}
		if child := node.SyntheticReferenceExpressionThisArg(); !child.IsNil() && v(child) {
			return true
		}
		return false
	case KindJSDocTypeLiteral:
		if node.forEachChildList(node.JSDocTypeLiteralJSDocPropertyTags(), v) {
			return true
		}
		return false
	case KindJSDocParameterTag, KindJSDocPropertyTag:
		return node.forEachChildJSDocParameterOrPropertyTag(v)
	default:
		return false
	}
}
