// Code generated by tools/scripts/tsc/generate-encoder.ts. DO NOT EDIT.

package encoder

import (
	"fmt"

	"github.com/microsoft/TypeScript/tsc/internal/ast"
)

func getNodeDataType(node ast.Handle) uint32 {
	switch node.Kind {
	case ast.KindIdentifier,
		ast.KindPrivateIdentifier,
		ast.KindJsxText,
		ast.KindJSDocText,
		ast.KindJSDocLink,
		ast.KindJSDocLinkPlain,
		ast.KindJSDocLinkCode:
		return NodeDataTypeString
	case ast.KindStringLiteral,
		ast.KindNumericLiteral,
		ast.KindBigIntLiteral,
		ast.KindRegularExpressionLiteral,
		ast.KindNoSubstitutionTemplateLiteral,
		ast.KindTemplateHead,
		ast.KindTemplateMiddle,
		ast.KindTemplateTail,
		ast.KindSourceFile:
		return NodeDataTypeExtendedData
	default:
		return NodeDataTypeChildren
	}
}

func getChildrenPropertyMask(node ast.Handle) uint8 {
	switch node.Kind {
	case ast.KindQualifiedName:
		n := node
		return (boolToByte(!n.QualifiedNameLeft().IsNil()) << 0) | (boolToByte(!n.QualifiedNameRight().IsNil()) << 1)
	case ast.KindComputedPropertyName:
		n := node
		return (boolToByte(!n.ComputedPropertyNameExpression().IsNil()) << 0)
	case ast.KindDecorator:
		n := node
		return (boolToByte(!n.DecoratorExpression().IsNil()) << 0)
	case ast.KindIfStatement:
		n := node
		return (boolToByte(!n.IfStatementExpression().IsNil()) << 0) | (boolToByte(!n.IfStatementThenStatement().IsNil()) << 1) | (boolToByte(!n.IfStatementElseStatement().IsNil()) << 2)
	case ast.KindDoStatement:
		n := node
		return (boolToByte(!n.DoStatementStatement().IsNil()) << 0) | (boolToByte(!n.DoStatementExpression().IsNil()) << 1)
	case ast.KindWhileStatement:
		n := node
		return (boolToByte(!n.WhileStatementExpression().IsNil()) << 0) | (boolToByte(!n.WhileStatementStatement().IsNil()) << 1)
	case ast.KindForStatement:
		n := node
		return (boolToByte(!n.ForStatementInitializer().IsNil()) << 0) | (boolToByte(!n.ForStatementCondition().IsNil()) << 1) | (boolToByte(!n.ForStatementIncrementor().IsNil()) << 2) | (boolToByte(!n.ForStatementStatement().IsNil()) << 3)
	case ast.KindForInStatement, ast.KindForOfStatement:
		n := node
		return (boolToByte(!n.ForInOrOfStatementAwaitModifier().IsNil()) << 0) | (boolToByte(!n.ForInOrOfStatementInitializer().IsNil()) << 1) | (boolToByte(!n.ForInOrOfStatementExpression().IsNil()) << 2) | (boolToByte(!n.ForInOrOfStatementStatement().IsNil()) << 3)
	case ast.KindBreakStatement:
		n := node
		return (boolToByte(!n.BreakStatementLabel().IsNil()) << 0)
	case ast.KindContinueStatement:
		n := node
		return (boolToByte(!n.ContinueStatementLabel().IsNil()) << 0)
	case ast.KindReturnStatement:
		n := node
		return (boolToByte(!n.ReturnStatementExpression().IsNil()) << 0)
	case ast.KindWithStatement:
		n := node
		return (boolToByte(!n.WithStatementExpression().IsNil()) << 0) | (boolToByte(!n.WithStatementStatement().IsNil()) << 1)
	case ast.KindSwitchStatement:
		n := node
		return (boolToByte(!n.SwitchStatementExpression().IsNil()) << 0) | (boolToByte(!n.SwitchStatementCaseBlock().IsNil()) << 1)
	case ast.KindCaseBlock:
		n := node
		return (boolToByte(n.CaseBlockClauses() != 0) << 0)
	case ast.KindCaseClause, ast.KindDefaultClause:
		n := node
		return (boolToByte(!n.CaseOrDefaultClauseExpression().IsNil()) << 0) | (boolToByte(n.CaseOrDefaultClauseStatements() != 0) << 1)
	case ast.KindThrowStatement:
		n := node
		return (boolToByte(!n.ThrowStatementExpression().IsNil()) << 0)
	case ast.KindTryStatement:
		n := node
		return (boolToByte(!n.TryStatementTryBlock().IsNil()) << 0) | (boolToByte(!n.TryStatementCatchClause().IsNil()) << 1) | (boolToByte(!n.TryStatementFinallyBlock().IsNil()) << 2)
	case ast.KindCatchClause:
		n := node
		return (boolToByte(!n.CatchClauseVariableDeclaration().IsNil()) << 0) | (boolToByte(!n.CatchClauseBlock().IsNil()) << 1)
	case ast.KindLabeledStatement:
		n := node
		return (boolToByte(!n.LabeledStatementLabel().IsNil()) << 0) | (boolToByte(!n.LabeledStatementStatement().IsNil()) << 1)
	case ast.KindExpressionStatement:
		n := node
		return (boolToByte(!n.ExpressionStatementExpression().IsNil()) << 0)
	case ast.KindBlock:
		n := node
		return (boolToByte(n.BlockStatements() != 0) << 0)
	case ast.KindVariableStatement:
		n := node
		return (boolToByte(hasModifiers(n.Modifiers())) << 0) | (boolToByte(!n.VariableStatementDeclarationList().IsNil()) << 1)
	case ast.KindVariableDeclaration:
		n := node
		return (boolToByte(!n.VariableDeclarationName().IsNil()) << 0) | (boolToByte(!n.VariableDeclarationExclamationToken().IsNil()) << 1) | (boolToByte(!n.VariableDeclarationType().IsNil()) << 2) | (boolToByte(!n.VariableDeclarationInitializer().IsNil()) << 3)
	case ast.KindVariableDeclarationList:
		n := node
		return (boolToByte(n.VariableDeclarationListDeclarations() != 0) << 0)
	case ast.KindObjectBindingPattern, ast.KindArrayBindingPattern:
		n := node
		return (boolToByte(n.BindingPatternElements() != 0) << 0)
	case ast.KindParameter:
		n := node
		return (boolToByte(hasModifiers(n.Modifiers())) << 0) | (boolToByte(!n.ParameterDeclarationDotDotDotToken().IsNil()) << 1) | (boolToByte(!n.ParameterDeclarationName().IsNil()) << 2) | (boolToByte(!n.ParameterDeclarationQuestionToken().IsNil()) << 3) | (boolToByte(!n.ParameterDeclarationType().IsNil()) << 4) | (boolToByte(!n.ParameterDeclarationInitializer().IsNil()) << 5)
	case ast.KindBindingElement:
		n := node
		return (boolToByte(!n.BindingElementDotDotDotToken().IsNil()) << 0) | (boolToByte(!n.BindingElementPropertyName().IsNil()) << 1) | (boolToByte(!n.BindingElementName().IsNil()) << 2) | (boolToByte(!n.BindingElementInitializer().IsNil()) << 3)
	case ast.KindMissingDeclaration:
		n := node
		return (boolToByte(hasModifiers(n.Modifiers())) << 0)
	case ast.KindFunctionDeclaration:
		n := node
		return (boolToByte(hasModifiers(n.Modifiers())) << 0) | (boolToByte(!n.FunctionDeclarationAsteriskToken().IsNil()) << 1) | (boolToByte(!n.FunctionDeclarationName().IsNil()) << 2) | (boolToByte(n.FunctionDeclarationTypeParameters() != 0) << 3) | (boolToByte(n.FunctionDeclarationParameters() != 0) << 4) | (boolToByte(!n.FunctionDeclarationType().IsNil()) << 5) | (boolToByte(!n.FunctionDeclarationBody().IsNil()) << 6)
	case ast.KindClassDeclaration:
		n := node
		return (boolToByte(hasModifiers(n.Modifiers())) << 0) | (boolToByte(!n.ClassDeclarationName().IsNil()) << 1) | (boolToByte(n.ClassDeclarationTypeParameters() != 0) << 2) | (boolToByte(n.ClassDeclarationHeritageClauses() != 0) << 3) | (boolToByte(n.ClassDeclarationMembers() != 0) << 4)
	case ast.KindClassExpression:
		n := node
		return (boolToByte(hasModifiers(n.Modifiers())) << 0) | (boolToByte(!n.ClassExpressionName().IsNil()) << 1) | (boolToByte(n.ClassExpressionTypeParameters() != 0) << 2) | (boolToByte(n.ClassExpressionHeritageClauses() != 0) << 3) | (boolToByte(n.ClassExpressionMembers() != 0) << 4)
	case ast.KindHeritageClause:
		n := node
		return (boolToByte(n.HeritageClauseTypes() != 0) << 0)
	case ast.KindInterfaceDeclaration:
		n := node
		return (boolToByte(hasModifiers(n.Modifiers())) << 0) | (boolToByte(!n.InterfaceDeclarationName().IsNil()) << 1) | (boolToByte(n.InterfaceDeclarationTypeParameters() != 0) << 2) | (boolToByte(n.InterfaceDeclarationHeritageClauses() != 0) << 3) | (boolToByte(n.InterfaceDeclarationMembers() != 0) << 4)
	case ast.KindTypeAliasDeclaration, ast.KindJSTypeAliasDeclaration:
		n := node
		return (boolToByte(hasModifiers(n.Modifiers())) << 0) | (boolToByte(!n.TypeAliasDeclarationName().IsNil()) << 1) | (boolToByte(n.TypeAliasDeclarationTypeParameters() != 0) << 2) | (boolToByte(!n.TypeAliasDeclarationType().IsNil()) << 3)
	case ast.KindEnumMember:
		n := node
		return (boolToByte(!n.EnumMemberName().IsNil()) << 0) | (boolToByte(!n.EnumMemberInitializer().IsNil()) << 1)
	case ast.KindEnumDeclaration:
		n := node
		return (boolToByte(hasModifiers(n.Modifiers())) << 0) | (boolToByte(!n.EnumDeclarationName().IsNil()) << 1) | (boolToByte(n.EnumDeclarationMembers() != 0) << 2)
	case ast.KindModuleBlock:
		n := node
		return (boolToByte(n.ModuleBlockStatements() != 0) << 0)
	case ast.KindImportDeclaration, ast.KindJSImportDeclaration:
		n := node
		return (boolToByte(hasModifiers(n.Modifiers())) << 0) | (boolToByte(!n.ImportDeclarationImportClause().IsNil()) << 1) | (boolToByte(!n.ImportDeclarationModuleSpecifier().IsNil()) << 2) | (boolToByte(!n.ImportDeclarationAttributes().IsNil()) << 3)
	case ast.KindExternalModuleReference:
		n := node
		return (boolToByte(!n.ExternalModuleReferenceExpression().IsNil()) << 0)
	case ast.KindNamespaceImport:
		n := node
		return (boolToByte(!n.NamespaceImportName().IsNil()) << 0)
	case ast.KindNamedImports:
		n := node
		return (boolToByte(n.NamedImportsElements() != 0) << 0)
	case ast.KindExportAssignment:
		n := node
		return (boolToByte(hasModifiers(n.Modifiers())) << 0) | (boolToByte(!n.ExportAssignmentType().IsNil()) << 1) | (boolToByte(!n.ExportAssignmentExpression().IsNil()) << 2)
	case ast.KindNamespaceExportDeclaration:
		n := node
		return (boolToByte(hasModifiers(n.Modifiers())) << 0) | (boolToByte(!n.NamespaceExportDeclarationName().IsNil()) << 1)
	case ast.KindNamespaceExport:
		n := node
		return (boolToByte(!n.NamespaceExportName().IsNil()) << 0)
	case ast.KindNamedExports:
		n := node
		return (boolToByte(n.NamedExportsElements() != 0) << 0)
	case ast.KindExportSpecifier:
		n := node
		return (boolToByte(!n.ExportSpecifierPropertyName().IsNil()) << 0) | (boolToByte(!n.ExportSpecifierName().IsNil()) << 1)
	case ast.KindCallSignature:
		n := node
		return (boolToByte(n.CallSignatureDeclarationTypeParameters() != 0) << 0) | (boolToByte(n.CallSignatureDeclarationParameters() != 0) << 1) | (boolToByte(!n.CallSignatureDeclarationType().IsNil()) << 2)
	case ast.KindConstructSignature:
		n := node
		return (boolToByte(n.ConstructSignatureDeclarationTypeParameters() != 0) << 0) | (boolToByte(n.ConstructSignatureDeclarationParameters() != 0) << 1) | (boolToByte(!n.ConstructSignatureDeclarationType().IsNil()) << 2)
	case ast.KindConstructor:
		n := node
		return (boolToByte(hasModifiers(n.Modifiers())) << 0) | (boolToByte(n.ConstructorDeclarationTypeParameters() != 0) << 1) | (boolToByte(n.ConstructorDeclarationParameters() != 0) << 2) | (boolToByte(!n.ConstructorDeclarationType().IsNil()) << 3) | (boolToByte(!n.ConstructorDeclarationBody().IsNil()) << 4)
	case ast.KindGetAccessor:
		n := node
		return (boolToByte(hasModifiers(n.Modifiers())) << 0) | (boolToByte(!n.GetAccessorDeclarationName().IsNil()) << 1) | (boolToByte(n.GetAccessorDeclarationTypeParameters() != 0) << 2) | (boolToByte(n.GetAccessorDeclarationParameters() != 0) << 3) | (boolToByte(!n.GetAccessorDeclarationType().IsNil()) << 4) | (boolToByte(!n.GetAccessorDeclarationBody().IsNil()) << 5)
	case ast.KindSetAccessor:
		n := node
		return (boolToByte(hasModifiers(n.Modifiers())) << 0) | (boolToByte(!n.SetAccessorDeclarationName().IsNil()) << 1) | (boolToByte(n.SetAccessorDeclarationTypeParameters() != 0) << 2) | (boolToByte(n.SetAccessorDeclarationParameters() != 0) << 3) | (boolToByte(!n.SetAccessorDeclarationType().IsNil()) << 4) | (boolToByte(!n.SetAccessorDeclarationBody().IsNil()) << 5)
	case ast.KindIndexSignature:
		n := node
		return (boolToByte(hasModifiers(n.Modifiers())) << 0) | (boolToByte(n.IndexSignatureDeclarationParameters() != 0) << 1) | (boolToByte(!n.IndexSignatureDeclarationType().IsNil()) << 2)
	case ast.KindMethodSignature:
		n := node
		return (boolToByte(hasModifiers(n.Modifiers())) << 0) | (boolToByte(!n.MethodSignatureDeclarationName().IsNil()) << 1) | (boolToByte(!n.MethodSignatureDeclarationPostfixToken().IsNil()) << 2) | (boolToByte(n.MethodSignatureDeclarationTypeParameters() != 0) << 3) | (boolToByte(n.MethodSignatureDeclarationParameters() != 0) << 4) | (boolToByte(!n.MethodSignatureDeclarationType().IsNil()) << 5)
	case ast.KindMethodDeclaration:
		n := node
		return (boolToByte(hasModifiers(n.Modifiers())) << 0) | (boolToByte(!n.MethodDeclarationAsteriskToken().IsNil()) << 1) | (boolToByte(!n.MethodDeclarationName().IsNil()) << 2) | (boolToByte(!n.MethodDeclarationPostfixToken().IsNil()) << 3) | (boolToByte(n.MethodDeclarationTypeParameters() != 0) << 4) | (boolToByte(n.MethodDeclarationParameters() != 0) << 5) | (boolToByte(!n.MethodDeclarationType().IsNil()) << 6) | (boolToByte(!n.MethodDeclarationBody().IsNil()) << 7)
	case ast.KindPropertySignature:
		n := node
		return (boolToByte(hasModifiers(n.Modifiers())) << 0) | (boolToByte(!n.PropertySignatureDeclarationName().IsNil()) << 1) | (boolToByte(!n.PropertySignatureDeclarationPostfixToken().IsNil()) << 2) | (boolToByte(!n.PropertySignatureDeclarationType().IsNil()) << 3) | (boolToByte(!n.PropertySignatureDeclarationInitializer().IsNil()) << 4)
	case ast.KindPropertyDeclaration:
		n := node
		return (boolToByte(hasModifiers(n.Modifiers())) << 0) | (boolToByte(!n.PropertyDeclarationName().IsNil()) << 1) | (boolToByte(!n.PropertyDeclarationPostfixToken().IsNil()) << 2) | (boolToByte(!n.PropertyDeclarationType().IsNil()) << 3) | (boolToByte(!n.PropertyDeclarationInitializer().IsNil()) << 4)
	case ast.KindClassStaticBlockDeclaration:
		n := node
		return (boolToByte(hasModifiers(n.Modifiers())) << 0) | (boolToByte(!n.ClassStaticBlockDeclarationBody().IsNil()) << 1)
	case ast.KindBinaryExpression:
		n := node
		return (boolToByte(hasModifiers(n.Modifiers())) << 0) | (boolToByte(!n.BinaryExpressionLeft().IsNil()) << 1) | (boolToByte(!n.BinaryExpressionType().IsNil()) << 2) | (boolToByte(!n.BinaryExpressionOperatorToken().IsNil()) << 3) | (boolToByte(!n.BinaryExpressionRight().IsNil()) << 4)
	case ast.KindPrefixUnaryExpression:
		n := node
		return (boolToByte(!n.PrefixUnaryExpressionOperand().IsNil()) << 0)
	case ast.KindPostfixUnaryExpression:
		n := node
		return (boolToByte(!n.PostfixUnaryExpressionOperand().IsNil()) << 0)
	case ast.KindYieldExpression:
		n := node
		return (boolToByte(!n.YieldExpressionAsteriskToken().IsNil()) << 0) | (boolToByte(!n.YieldExpressionExpression().IsNil()) << 1)
	case ast.KindArrowFunction:
		n := node
		return (boolToByte(hasModifiers(n.Modifiers())) << 0) | (boolToByte(n.ArrowFunctionTypeParameters() != 0) << 1) | (boolToByte(n.ArrowFunctionParameters() != 0) << 2) | (boolToByte(!n.ArrowFunctionType().IsNil()) << 3) | (boolToByte(!n.ArrowFunctionEqualsGreaterThanToken().IsNil()) << 4) | (boolToByte(!n.ArrowFunctionBody().IsNil()) << 5)
	case ast.KindFunctionExpression:
		n := node
		return (boolToByte(hasModifiers(n.Modifiers())) << 0) | (boolToByte(!n.FunctionExpressionAsteriskToken().IsNil()) << 1) | (boolToByte(!n.FunctionExpressionName().IsNil()) << 2) | (boolToByte(n.FunctionExpressionTypeParameters() != 0) << 3) | (boolToByte(n.FunctionExpressionParameters() != 0) << 4) | (boolToByte(!n.FunctionExpressionType().IsNil()) << 5) | (boolToByte(!n.FunctionExpressionBody().IsNil()) << 6)
	case ast.KindAsExpression:
		n := node
		return (boolToByte(!n.AsExpressionExpression().IsNil()) << 0) | (boolToByte(!n.AsExpressionType().IsNil()) << 1)
	case ast.KindSatisfiesExpression:
		n := node
		return (boolToByte(!n.SatisfiesExpressionExpression().IsNil()) << 0) | (boolToByte(!n.SatisfiesExpressionType().IsNil()) << 1)
	case ast.KindConditionalExpression:
		n := node
		return (boolToByte(!n.ConditionalExpressionCondition().IsNil()) << 0) | (boolToByte(!n.ConditionalExpressionQuestionToken().IsNil()) << 1) | (boolToByte(!n.ConditionalExpressionWhenTrue().IsNil()) << 2) | (boolToByte(!n.ConditionalExpressionColonToken().IsNil()) << 3) | (boolToByte(!n.ConditionalExpressionWhenFalse().IsNil()) << 4)
	case ast.KindPropertyAccessExpression:
		n := node
		return (boolToByte(!n.PropertyAccessExpressionExpression().IsNil()) << 0) | (boolToByte(!n.PropertyAccessExpressionQuestionDotToken().IsNil()) << 1) | (boolToByte(!n.PropertyAccessExpressionName().IsNil()) << 2)
	case ast.KindElementAccessExpression:
		n := node
		return (boolToByte(!n.ElementAccessExpressionExpression().IsNil()) << 0) | (boolToByte(!n.ElementAccessExpressionQuestionDotToken().IsNil()) << 1) | (boolToByte(!n.ElementAccessExpressionArgumentExpression().IsNil()) << 2)
	case ast.KindCallExpression:
		n := node
		return (boolToByte(!n.CallExpressionExpression().IsNil()) << 0) | (boolToByte(!n.CallExpressionQuestionDotToken().IsNil()) << 1) | (boolToByte(n.CallExpressionTypeArguments() != 0) << 2) | (boolToByte(n.CallExpressionArguments() != 0) << 3)
	case ast.KindNewExpression:
		n := node
		return (boolToByte(!n.NewExpressionExpression().IsNil()) << 0) | (boolToByte(n.NewExpressionTypeArguments() != 0) << 1) | (boolToByte(n.NewExpressionArguments() != 0) << 2)
	case ast.KindMetaProperty:
		n := node
		return (boolToByte(!n.MetaPropertyName().IsNil()) << 0)
	case ast.KindNonNullExpression:
		n := node
		return (boolToByte(!n.NonNullExpressionExpression().IsNil()) << 0)
	case ast.KindSpreadElement:
		n := node
		return (boolToByte(!n.SpreadElementExpression().IsNil()) << 0)
	case ast.KindTemplateExpression:
		n := node
		return (boolToByte(!n.TemplateExpressionHead().IsNil()) << 0) | (boolToByte(n.TemplateExpressionTemplateSpans() != 0) << 1)
	case ast.KindTemplateSpan:
		n := node
		return (boolToByte(!n.TemplateSpanExpression().IsNil()) << 0) | (boolToByte(!n.TemplateSpanLiteral().IsNil()) << 1)
	case ast.KindTaggedTemplateExpression:
		n := node
		return (boolToByte(!n.TaggedTemplateExpressionTag().IsNil()) << 0) | (boolToByte(!n.TaggedTemplateExpressionQuestionDotToken().IsNil()) << 1) | (boolToByte(n.TaggedTemplateExpressionTypeArguments() != 0) << 2) | (boolToByte(!n.TaggedTemplateExpressionTemplate().IsNil()) << 3)
	case ast.KindParenthesizedExpression:
		n := node
		return (boolToByte(!n.ParenthesizedExpressionExpression().IsNil()) << 0)
	case ast.KindArrayLiteralExpression:
		n := node
		return (boolToByte(n.ArrayLiteralExpressionElements() != 0) << 0)
	case ast.KindObjectLiteralExpression:
		n := node
		return (boolToByte(n.ObjectLiteralExpressionProperties() != 0) << 0)
	case ast.KindSpreadAssignment:
		n := node
		return (boolToByte(!n.SpreadAssignmentExpression().IsNil()) << 0)
	case ast.KindPropertyAssignment:
		n := node
		return (boolToByte(hasModifiers(n.Modifiers())) << 0) | (boolToByte(!n.PropertyAssignmentName().IsNil()) << 1) | (boolToByte(!n.PropertyAssignmentPostfixToken().IsNil()) << 2) | (boolToByte(!n.PropertyAssignmentType().IsNil()) << 3) | (boolToByte(!n.PropertyAssignmentInitializer().IsNil()) << 4)
	case ast.KindShorthandPropertyAssignment:
		n := node
		return (boolToByte(hasModifiers(n.Modifiers())) << 0) | (boolToByte(!n.ShorthandPropertyAssignmentName().IsNil()) << 1) | (boolToByte(!n.ShorthandPropertyAssignmentPostfixToken().IsNil()) << 2) | (boolToByte(!n.ShorthandPropertyAssignmentType().IsNil()) << 3) | (boolToByte(!n.ShorthandPropertyAssignmentEqualsToken().IsNil()) << 4) | (boolToByte(!n.ShorthandPropertyAssignmentObjectAssignmentInitializer().IsNil()) << 5)
	case ast.KindDeleteExpression:
		n := node
		return (boolToByte(!n.DeleteExpressionExpression().IsNil()) << 0)
	case ast.KindTypeOfExpression:
		n := node
		return (boolToByte(!n.TypeOfExpressionExpression().IsNil()) << 0)
	case ast.KindVoidExpression:
		n := node
		return (boolToByte(!n.VoidExpressionExpression().IsNil()) << 0)
	case ast.KindAwaitExpression:
		n := node
		return (boolToByte(!n.AwaitExpressionExpression().IsNil()) << 0)
	case ast.KindTypeAssertionExpression:
		n := node
		return (boolToByte(!n.TypeAssertionType().IsNil()) << 0) | (boolToByte(!n.TypeAssertionExpression().IsNil()) << 1)
	case ast.KindUnionType:
		n := node
		return (boolToByte(n.UnionTypeNodeTypes() != 0) << 0)
	case ast.KindIntersectionType:
		n := node
		return (boolToByte(n.IntersectionTypeNodeTypes() != 0) << 0)
	case ast.KindConditionalType:
		n := node
		return (boolToByte(!n.ConditionalTypeNodeCheckType().IsNil()) << 0) | (boolToByte(!n.ConditionalTypeNodeExtendsType().IsNil()) << 1) | (boolToByte(!n.ConditionalTypeNodeTrueType().IsNil()) << 2) | (boolToByte(!n.ConditionalTypeNodeFalseType().IsNil()) << 3)
	case ast.KindTypeOperator:
		n := node
		return (boolToByte(!n.TypeOperatorNodeType().IsNil()) << 0)
	case ast.KindInferType:
		n := node
		return (boolToByte(!n.InferTypeNodeTypeParameter().IsNil()) << 0)
	case ast.KindArrayType:
		n := node
		return (boolToByte(!n.ArrayTypeNodeElementType().IsNil()) << 0)
	case ast.KindIndexedAccessType:
		n := node
		return (boolToByte(!n.IndexedAccessTypeNodeObjectType().IsNil()) << 0) | (boolToByte(!n.IndexedAccessTypeNodeIndexType().IsNil()) << 1)
	case ast.KindTypeReference:
		n := node
		return (boolToByte(!n.TypeReferenceNodeTypeName().IsNil()) << 0) | (boolToByte(n.TypeReferenceNodeTypeArguments() != 0) << 1)
	case ast.KindExpressionWithTypeArguments:
		n := node
		return (boolToByte(!n.ExpressionWithTypeArgumentsExpression().IsNil()) << 0) | (boolToByte(n.ExpressionWithTypeArgumentsTypeArguments() != 0) << 1)
	case ast.KindLiteralType:
		n := node
		return (boolToByte(!n.LiteralTypeNodeLiteral().IsNil()) << 0)
	case ast.KindTypePredicate:
		n := node
		return (boolToByte(!n.TypePredicateNodeAssertsModifier().IsNil()) << 0) | (boolToByte(!n.TypePredicateNodeParameterName().IsNil()) << 1) | (boolToByte(!n.TypePredicateNodeType().IsNil()) << 2)
	case ast.KindImportAttribute:
		n := node
		return (boolToByte(!n.ImportAttributeName().IsNil()) << 0) | (boolToByte(!n.ImportAttributeValue().IsNil()) << 1)
	case ast.KindImportAttributes:
		n := node
		return (boolToByte(n.ImportAttributesAttributes() != 0) << 0)
	case ast.KindTypeQuery:
		n := node
		return (boolToByte(!n.TypeQueryNodeExprName().IsNil()) << 0) | (boolToByte(n.TypeQueryNodeTypeArguments() != 0) << 1)
	case ast.KindMappedType:
		n := node
		return (boolToByte(!n.MappedTypeNodeReadonlyToken().IsNil()) << 0) | (boolToByte(!n.MappedTypeNodeTypeParameter().IsNil()) << 1) | (boolToByte(!n.MappedTypeNodeNameType().IsNil()) << 2) | (boolToByte(!n.MappedTypeNodeQuestionToken().IsNil()) << 3) | (boolToByte(!n.MappedTypeNodeType().IsNil()) << 4) | (boolToByte(n.MappedTypeNodeMembers() != 0) << 5)
	case ast.KindTypeLiteral:
		n := node
		return (boolToByte(n.TypeLiteralNodeMembers() != 0) << 0)
	case ast.KindTupleType:
		n := node
		return (boolToByte(n.TupleTypeNodeElements() != 0) << 0)
	case ast.KindNamedTupleMember:
		n := node
		return (boolToByte(!n.NamedTupleMemberDotDotDotToken().IsNil()) << 0) | (boolToByte(!n.NamedTupleMemberName().IsNil()) << 1) | (boolToByte(!n.NamedTupleMemberQuestionToken().IsNil()) << 2) | (boolToByte(!n.NamedTupleMemberType().IsNil()) << 3)
	case ast.KindOptionalType:
		n := node
		return (boolToByte(!n.OptionalTypeNodeType().IsNil()) << 0)
	case ast.KindRestType:
		n := node
		return (boolToByte(!n.RestTypeNodeType().IsNil()) << 0)
	case ast.KindParenthesizedType:
		n := node
		return (boolToByte(!n.ParenthesizedTypeNodeType().IsNil()) << 0)
	case ast.KindFunctionType:
		n := node
		return (boolToByte(n.FunctionTypeNodeTypeParameters() != 0) << 0) | (boolToByte(n.FunctionTypeNodeParameters() != 0) << 1) | (boolToByte(!n.FunctionTypeNodeType().IsNil()) << 2)
	case ast.KindConstructorType:
		n := node
		return (boolToByte(hasModifiers(n.Modifiers())) << 0) | (boolToByte(n.ConstructorTypeNodeTypeParameters() != 0) << 1) | (boolToByte(n.ConstructorTypeNodeParameters() != 0) << 2) | (boolToByte(!n.ConstructorTypeNodeType().IsNil()) << 3)
	case ast.KindTemplateLiteralType:
		n := node
		return (boolToByte(!n.TemplateLiteralTypeNodeHead().IsNil()) << 0) | (boolToByte(n.TemplateLiteralTypeNodeTemplateSpans() != 0) << 1)
	case ast.KindTemplateLiteralTypeSpan:
		n := node
		return (boolToByte(!n.TemplateLiteralTypeSpanType().IsNil()) << 0) | (boolToByte(!n.TemplateLiteralTypeSpanLiteral().IsNil()) << 1)
	case ast.KindSyntheticExpression:
		n := node
		return (boolToByte(!n.SyntheticExpressionTupleNameSource().IsNil()) << 0)
	case ast.KindPartiallyEmittedExpression:
		n := node
		return (boolToByte(!n.PartiallyEmittedExpressionExpression().IsNil()) << 0)
	case ast.KindJsxElement:
		n := node
		return (boolToByte(!n.JsxElementOpeningElement().IsNil()) << 0) | (boolToByte(n.JsxElementChildren() != 0) << 1) | (boolToByte(!n.JsxElementClosingElement().IsNil()) << 2)
	case ast.KindJsxAttributes:
		n := node
		return (boolToByte(n.JsxAttributesProperties() != 0) << 0)
	case ast.KindJsxNamespacedName:
		n := node
		return (boolToByte(!n.JsxNamespacedNameNamespace().IsNil()) << 0) | (boolToByte(!n.JsxNamespacedNameName().IsNil()) << 1)
	case ast.KindJsxOpeningElement:
		n := node
		return (boolToByte(!n.JsxOpeningElementTagName().IsNil()) << 0) | (boolToByte(n.JsxOpeningElementTypeArguments() != 0) << 1) | (boolToByte(!n.JsxOpeningElementAttributes().IsNil()) << 2)
	case ast.KindJsxSelfClosingElement:
		n := node
		return (boolToByte(!n.JsxSelfClosingElementTagName().IsNil()) << 0) | (boolToByte(n.JsxSelfClosingElementTypeArguments() != 0) << 1) | (boolToByte(!n.JsxSelfClosingElementAttributes().IsNil()) << 2)
	case ast.KindJsxFragment:
		n := node
		return (boolToByte(!n.JsxFragmentOpeningFragment().IsNil()) << 0) | (boolToByte(n.JsxFragmentChildren() != 0) << 1) | (boolToByte(!n.JsxFragmentClosingFragment().IsNil()) << 2)
	case ast.KindJsxAttribute:
		n := node
		return (boolToByte(!n.JsxAttributeName().IsNil()) << 0) | (boolToByte(!n.JsxAttributeInitializer().IsNil()) << 1)
	case ast.KindJsxSpreadAttribute:
		n := node
		return (boolToByte(!n.JsxSpreadAttributeExpression().IsNil()) << 0)
	case ast.KindJsxClosingElement:
		n := node
		return (boolToByte(!n.JsxClosingElementTagName().IsNil()) << 0)
	case ast.KindJsxExpression:
		n := node
		return (boolToByte(!n.JsxExpressionDotDotDotToken().IsNil()) << 0) | (boolToByte(!n.JsxExpressionExpression().IsNil()) << 1)
	case ast.KindSyntaxList:
		n := node
		return (boolToByte(n.Store().ListLen(n.SyntaxListChildren()) > 0) << 0)
	case ast.KindJSDoc:
		n := node
		return (boolToByte(n.JSDocComment() != 0) << 0) | (boolToByte(n.JSDocTags() != 0) << 1)
	case ast.KindJSDocTypeExpression:
		n := node
		return (boolToByte(!n.JSDocTypeExpressionType().IsNil()) << 0)
	case ast.KindJSDocNonNullableType:
		n := node
		return (boolToByte(!n.JSDocNonNullableTypeType().IsNil()) << 0)
	case ast.KindJSDocNullableType:
		n := node
		return (boolToByte(!n.JSDocNullableTypeType().IsNil()) << 0)
	case ast.KindJSDocVariadicType:
		n := node
		return (boolToByte(!n.JSDocVariadicTypeType().IsNil()) << 0)
	case ast.KindJSDocOptionalType:
		n := node
		return (boolToByte(!n.JSDocOptionalTypeType().IsNil()) << 0)
	case ast.KindJSDocTypeTag:
		n := node
		return (boolToByte(!n.JSDocTypeTagTagName().IsNil()) << 0) | (boolToByte(!n.JSDocTypeTagTypeExpression().IsNil()) << 1) | (boolToByte(n.JSDocTypeTagComment() != 0) << 2)
	case ast.KindJSDocUnknownTag:
		n := node
		return (boolToByte(!n.JSDocUnknownTagTagName().IsNil()) << 0) | (boolToByte(n.JSDocUnknownTagComment() != 0) << 1)
	case ast.KindJSDocTemplateTag:
		n := node
		return (boolToByte(!n.JSDocTemplateTagTagName().IsNil()) << 0) | (boolToByte(!n.JSDocTemplateTagConstraint().IsNil()) << 1) | (boolToByte(n.JSDocTemplateTagTypeParameters() != 0) << 2) | (boolToByte(n.JSDocTemplateTagComment() != 0) << 3)
	case ast.KindJSDocReturnTag:
		n := node
		return (boolToByte(!n.JSDocReturnTagTagName().IsNil()) << 0) | (boolToByte(!n.JSDocReturnTagTypeExpression().IsNil()) << 1) | (boolToByte(n.JSDocReturnTagComment() != 0) << 2)
	case ast.KindJSDocPublicTag:
		n := node
		return (boolToByte(!n.JSDocPublicTagTagName().IsNil()) << 0) | (boolToByte(n.JSDocPublicTagComment() != 0) << 1)
	case ast.KindJSDocPrivateTag:
		n := node
		return (boolToByte(!n.JSDocPrivateTagTagName().IsNil()) << 0) | (boolToByte(n.JSDocPrivateTagComment() != 0) << 1)
	case ast.KindJSDocProtectedTag:
		n := node
		return (boolToByte(!n.JSDocProtectedTagTagName().IsNil()) << 0) | (boolToByte(n.JSDocProtectedTagComment() != 0) << 1)
	case ast.KindJSDocReadonlyTag:
		n := node
		return (boolToByte(!n.JSDocReadonlyTagTagName().IsNil()) << 0) | (boolToByte(n.JSDocReadonlyTagComment() != 0) << 1)
	case ast.KindJSDocOverrideTag:
		n := node
		return (boolToByte(!n.JSDocOverrideTagTagName().IsNil()) << 0) | (boolToByte(n.JSDocOverrideTagComment() != 0) << 1)
	case ast.KindJSDocDeprecatedTag:
		n := node
		return (boolToByte(!n.JSDocDeprecatedTagTagName().IsNil()) << 0) | (boolToByte(n.JSDocDeprecatedTagComment() != 0) << 1)
	case ast.KindJSDocSeeTag:
		n := node
		return (boolToByte(!n.JSDocSeeTagTagName().IsNil()) << 0) | (boolToByte(!n.JSDocSeeTagNameExpression().IsNil()) << 1) | (boolToByte(n.JSDocSeeTagComment() != 0) << 2)
	case ast.KindJSDocImplementsTag:
		n := node
		return (boolToByte(!n.JSDocImplementsTagTagName().IsNil()) << 0) | (boolToByte(!n.JSDocImplementsTagClassName().IsNil()) << 1) | (boolToByte(n.JSDocImplementsTagComment() != 0) << 2)
	case ast.KindJSDocAugmentsTag:
		n := node
		return (boolToByte(!n.JSDocAugmentsTagTagName().IsNil()) << 0) | (boolToByte(!n.JSDocAugmentsTagClassName().IsNil()) << 1) | (boolToByte(n.JSDocAugmentsTagComment() != 0) << 2)
	case ast.KindJSDocSatisfiesTag:
		n := node
		return (boolToByte(!n.JSDocSatisfiesTagTagName().IsNil()) << 0) | (boolToByte(!n.JSDocSatisfiesTagTypeExpression().IsNil()) << 1) | (boolToByte(n.JSDocSatisfiesTagComment() != 0) << 2)
	case ast.KindJSDocThrowsTag:
		n := node
		return (boolToByte(!n.JSDocThrowsTagTagName().IsNil()) << 0) | (boolToByte(!n.JSDocThrowsTagTypeExpression().IsNil()) << 1) | (boolToByte(n.JSDocThrowsTagComment() != 0) << 2)
	case ast.KindJSDocThisTag:
		n := node
		return (boolToByte(!n.JSDocThisTagTagName().IsNil()) << 0) | (boolToByte(!n.JSDocThisTagTypeExpression().IsNil()) << 1) | (boolToByte(n.JSDocThisTagComment() != 0) << 2)
	case ast.KindJSDocImportTag:
		n := node
		return (boolToByte(!n.JSDocImportTagTagName().IsNil()) << 0) | (boolToByte(!n.JSDocImportTagImportClause().IsNil()) << 1) | (boolToByte(!n.JSDocImportTagModuleSpecifier().IsNil()) << 2) | (boolToByte(!n.JSDocImportTagAttributes().IsNil()) << 3) | (boolToByte(n.JSDocImportTagComment() != 0) << 4)
	case ast.KindJSDocCallbackTag:
		n := node
		return (boolToByte(!n.JSDocCallbackTagTagName().IsNil()) << 0) | (boolToByte(!n.JSDocCallbackTagTypeExpression().IsNil()) << 1) | (boolToByte(!n.JSDocCallbackTagName().IsNil()) << 2) | (boolToByte(n.JSDocCallbackTagComment() != 0) << 3)
	case ast.KindJSDocOverloadTag:
		n := node
		return (boolToByte(!n.JSDocOverloadTagTagName().IsNil()) << 0) | (boolToByte(!n.JSDocOverloadTagTypeExpression().IsNil()) << 1) | (boolToByte(n.JSDocOverloadTagComment() != 0) << 2)
	case ast.KindJSDocTypedefTag:
		n := node
		return (boolToByte(!n.JSDocTypedefTagTagName().IsNil()) << 0) | (boolToByte(!n.JSDocTypedefTagTypeExpression().IsNil()) << 1) | (boolToByte(!n.JSDocTypedefTagName().IsNil()) << 2) | (boolToByte(n.JSDocTypedefTagComment() != 0) << 3)
	case ast.KindJSDocSignature:
		n := node
		return (boolToByte(n.JSDocSignatureTypeParameters() != 0) << 0) | (boolToByte(n.JSDocSignatureParameters() != 0) << 1) | (boolToByte(!n.JSDocSignatureType().IsNil()) << 2)
	case ast.KindJSDocNameReference:
		n := node
		return (boolToByte(!n.JSDocNameReferenceName().IsNil()) << 0)
	case ast.KindModuleDeclaration:
		n := node
		return (boolToByte(hasModifiers(n.Modifiers())) << 0) | (boolToByte(!n.ModuleDeclarationName().IsNil()) << 1) | (boolToByte(!n.ModuleDeclarationBody().IsNil()) << 2)
	case ast.KindImportEqualsDeclaration:
		n := node
		return (boolToByte(hasModifiers(n.Modifiers())) << 0) | (boolToByte(!n.ImportEqualsDeclarationName().IsNil()) << 1) | (boolToByte(!n.ImportEqualsDeclarationModuleReference().IsNil()) << 2)
	case ast.KindExportDeclaration:
		n := node
		return (boolToByte(hasModifiers(n.Modifiers())) << 0) | (boolToByte(!n.ExportDeclarationExportClause().IsNil()) << 1) | (boolToByte(!n.ExportDeclarationModuleSpecifier().IsNil()) << 2) | (boolToByte(!n.ExportDeclarationAttributes().IsNil()) << 3)
	case ast.KindImportType:
		n := node
		return (boolToByte(!n.ImportTypeNodeArgument().IsNil()) << 0) | (boolToByte(!n.ImportTypeNodeAttributes().IsNil()) << 1) | (boolToByte(!n.ImportTypeNodeQualifier().IsNil()) << 2) | (boolToByte(n.ImportTypeNodeTypeArguments() != 0) << 3)
	case ast.KindImportClause:
		n := node
		return (boolToByte(!n.ImportClauseName().IsNil()) << 0) | (boolToByte(!n.ImportClauseNamedBindings().IsNil()) << 1)
	case ast.KindImportSpecifier:
		n := node
		return (boolToByte(!n.ImportSpecifierPropertyName().IsNil()) << 0) | (boolToByte(!n.ImportSpecifierName().IsNil()) << 1)
	case ast.KindJSDocLink:
		n := node
		return (boolToByte(!n.JSDocLinkName().IsNil()) << 0)
	case ast.KindJSDocLinkPlain:
		n := node
		return (boolToByte(!n.JSDocLinkPlainName().IsNil()) << 0)
	case ast.KindJSDocLinkCode:
		n := node
		return (boolToByte(!n.JSDocLinkCodeName().IsNil()) << 0)
	case ast.KindTypeParameter:
		n := node
		return (boolToByte(hasModifiers(n.Modifiers())) << 0) | (boolToByte(!n.TypeParameterDeclarationName().IsNil()) << 1) | (boolToByte(!n.TypeParameterDeclarationConstraint().IsNil()) << 2) | (boolToByte(!n.TypeParameterDeclarationExpression().IsNil()) << 3) | (boolToByte(!n.TypeParameterDeclarationDefaultType().IsNil()) << 4)
	case ast.KindSyntheticReferenceExpression:
		n := node
		return (boolToByte(!n.SyntheticReferenceExpressionExpression().IsNil()) << 0) | (boolToByte(!n.SyntheticReferenceExpressionThisArg().IsNil()) << 1)
	case ast.KindJSDocTypeLiteral:
		n := node
		return (boolToByte(n.Store().ListLen(n.JSDocTypeLiteralJSDocPropertyTags()) > 0) << 0)
	case ast.KindJSDocParameterTag, ast.KindJSDocPropertyTag:
		n := node
		return (boolToByte(!n.JSDocParameterOrPropertyTagTagName().IsNil()) << 0) | (boolToByte(!n.JSDocParameterOrPropertyTagName().IsNil()) << 1) | (boolToByte(!n.JSDocParameterOrPropertyTagTypeExpression().IsNil()) << 2) | (boolToByte(n.JSDocParameterOrPropertyTagComment() != 0) << 3)
	default:
		return 0
	}
}

func getNodeCommonData(node ast.Handle) uint32 {
	switch node.Kind {
	case ast.KindBlock:
		n := node
		return uint32(boolToByte(n.BlockMultiLine())) << 24
	case ast.KindHeritageClause:
		n := node
		var tokenIdx uint32
		switch n.HeritageClauseToken() {
		case ast.KindImplementsKeyword:
			tokenIdx = 1
		}
		return tokenIdx << 24
	case ast.KindExportAssignment:
		n := node
		return uint32(boolToByte(n.ExportAssignmentIsExportEquals())) << 24
	case ast.KindExportSpecifier:
		n := node
		return uint32(boolToByte(n.ExportSpecifierIsTypeOnly())) << 24
	case ast.KindPrefixUnaryExpression:
		n := node
		var operatorIdx uint32
		switch n.PrefixUnaryExpressionOperator() {
		case ast.KindMinusToken:
			operatorIdx = 1
		case ast.KindTildeToken:
			operatorIdx = 2
		case ast.KindExclamationToken:
			operatorIdx = 3
		case ast.KindPlusPlusToken:
			operatorIdx = 4
		case ast.KindMinusMinusToken:
			operatorIdx = 5
		}
		return operatorIdx << 24
	case ast.KindPostfixUnaryExpression:
		n := node
		var operatorIdx uint32
		switch n.PostfixUnaryExpressionOperator() {
		case ast.KindMinusMinusToken:
			operatorIdx = 1
		}
		return operatorIdx << 24
	case ast.KindMetaProperty:
		n := node
		var keywordTokenIdx uint32
		switch n.MetaPropertyKeywordToken() {
		case ast.KindNewKeyword:
			keywordTokenIdx = 1
		}
		return keywordTokenIdx << 24
	case ast.KindArrayLiteralExpression:
		n := node
		return uint32(boolToByte(n.ArrayLiteralExpressionMultiLine())) << 24
	case ast.KindObjectLiteralExpression:
		n := node
		return uint32(boolToByte(n.ObjectLiteralExpressionMultiLine())) << 24
	case ast.KindTypeOperator:
		n := node
		var operatorIdx uint32
		switch n.TypeOperatorNodeOperator() {
		case ast.KindReadonlyKeyword:
			operatorIdx = 1
		case ast.KindUniqueKeyword:
			operatorIdx = 2
		}
		return operatorIdx << 24
	case ast.KindImportAttributes:
		n := node
		var tokenIdx uint32
		switch n.ImportAttributesToken() {
		case ast.KindAssertKeyword:
			tokenIdx = 1
		}
		return uint32(boolToByte(n.ImportAttributesMultiLine()))<<24 | tokenIdx<<25
	case ast.KindSyntheticExpression:
		return getNodeCommonData_SyntheticExpression(node)
	case ast.KindJsxText:
		n := node
		return uint32(boolToByte(n.JsxTextContainsOnlyTriviaWhiteSpaces())) << 24
	case ast.KindModuleDeclaration:
		n := node
		var keywordIdx uint32
		switch n.ModuleDeclarationKeyword() {
		case ast.KindNamespaceKeyword:
			keywordIdx = 1
		}
		return keywordIdx << 24
	case ast.KindImportEqualsDeclaration:
		n := node
		return uint32(boolToByte(n.ImportEqualsDeclarationIsTypeOnly())) << 24
	case ast.KindExportDeclaration:
		n := node
		return uint32(boolToByte(n.ExportDeclarationIsTypeOnly())) << 24
	case ast.KindImportType:
		n := node
		return uint32(boolToByte(n.ImportTypeNodeIsTypeOf())) << 24
	case ast.KindImportClause:
		n := node
		var phaseModifierIdx uint32
		switch n.ImportClausePhaseModifier() {
		case ast.KindTypeKeyword:
			phaseModifierIdx = 1
		case ast.KindDeferKeyword:
			phaseModifierIdx = 2
		}
		return phaseModifierIdx << 24
	case ast.KindImportSpecifier:
		n := node
		return uint32(boolToByte(n.ImportSpecifierIsTypeOnly())) << 24
	case ast.KindJSDocTypeLiteral:
		n := node
		return uint32(boolToByte(n.JSDocTypeLiteralIsArrayType())) << 24
	case ast.KindJSDocParameterTag, ast.KindJSDocPropertyTag:
		n := node
		return uint32(boolToByte(n.JSDocParameterOrPropertyTagIsBracketed()))<<24 | uint32(boolToByte(n.JSDocParameterOrPropertyTagIsNameFirst()))<<25
	}
	return 0
}

func recordNodeStrings(node ast.Handle, strs *stringTable) uint32 {
	switch node.Kind {
	case ast.KindIdentifier:
		return strs.add(node.Text(), node.Kind, node.Pos(), node.End())
	case ast.KindPrivateIdentifier:
		return strs.add(node.Text(), node.Kind, node.Pos(), node.End())
	case ast.KindJsxText:
		return strs.add(node.Text(), node.Kind, node.Pos(), node.End())
	case ast.KindJSDocText:
		return strs.add(node.Text(), node.Kind, node.Pos(), node.End())
	case ast.KindJSDocLink:
		return strs.add(node.Text(), node.Kind, node.Pos(), node.End())
	case ast.KindJSDocLinkPlain:
		return strs.add(node.Text(), node.Kind, node.Pos(), node.End())
	case ast.KindJSDocLinkCode:
		return strs.add(node.Text(), node.Kind, node.Pos(), node.End())
	default:
		panic(fmt.Sprintf("Unexpected node kind %v", node.Kind))
	}
}

func recordExtendedData(node ast.Handle, strs *stringTable, positionMap *ast.PositionMap, extendedData *[]byte, structuredData *[]byte) uint32 {
	offset := uint32(len(*extendedData))
	switch node.Kind {
	case ast.KindStringLiteral:
		recordExtendedData_StringLiteral(node, strs, positionMap, extendedData, structuredData)
	case ast.KindNumericLiteral:
		recordExtendedData_NumericLiteral(node, strs, positionMap, extendedData, structuredData)
	case ast.KindBigIntLiteral:
		recordExtendedData_BigIntLiteral(node, strs, positionMap, extendedData, structuredData)
	case ast.KindRegularExpressionLiteral:
		recordExtendedData_RegularExpressionLiteral(node, strs, positionMap, extendedData, structuredData)
	case ast.KindNoSubstitutionTemplateLiteral:
		recordExtendedData_NoSubstitutionTemplateLiteral(node, strs, positionMap, extendedData, structuredData)
	case ast.KindTemplateHead:
		recordExtendedData_TemplateHead(node, strs, positionMap, extendedData, structuredData)
	case ast.KindTemplateMiddle:
		recordExtendedData_TemplateMiddle(node, strs, positionMap, extendedData, structuredData)
	case ast.KindTemplateTail:
		recordExtendedData_TemplateTail(node, strs, positionMap, extendedData, structuredData)
	case ast.KindSourceFile:
		recordExtendedData_SourceFile(node, strs, positionMap, extendedData, structuredData)
	default:
		panic(fmt.Sprintf("unknown extended data node kind %v", node.Kind))
	}
	return offset
}
