/**
 * Store AST generator: reads tools/scripts/tsc/ast.json and produces the
 * generated files of tsc/internal/ast/store (design:
 * tsc/internal/ast/docs/store-ast-design-20260922.md).
 *
 * Usage: node tools/scripts/tsc/generate-go-store.ts
 *
 * Generates:
 *   - shapes_generated.go: payload words and list mask per kind, role slot tables
 *   - views_generated.go: slot constants, typed views, member and role accessors
 *   - foreach_generated.go: ForEachChild
 *   - builder_generated.go: one constructor per definition
 *   - convert/convert_generated.go: Pointer AST to Store
 *   - storetest/equivalence_generated.go: Pointer and Store compared member by member
 *
 * A member takes payload words in declaration order: a child or list is one
 * word, a text is two ([offset, length]), a bool, TokenFlags or kind is one.
 * Identifier and PrivateIdentifier keep their text in the header instead.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { xSync } from "tinyexec";
import type {
    MemberInfo,
    NodeType,
    Type,
} from "./schema.ts";
import { api } from "./schema.ts";

const ROOT = path.resolve(import.meta.dirname!, "../../..");
const OUT_DIR = path.join(ROOT, "tsc/internal/ast/store");
const HEADER = "// Code generated by tools/scripts/tsc/generate-go-store.ts. DO NOT EDIT.";
const AST_IMPORT = `"github.com/microsoft/TypeScript/tsc/internal/ast"`;
const STORE_IMPORT = `"github.com/microsoft/TypeScript/tsc/internal/ast/store"`;

// ────────────────────────────────────────────────────────────────────────────
// Override tables
// ────────────────────────────────────────────────────────────────────────────

// Member order for definitions whose Pointer ForEachChild is hand-written. The
// order must be the order in which that ForEachChild visits.
const memberOrderOverrides: Record<string, string[]> = {
    SourceFile: ["Statements", "EndOfFileToken"],
    // TODO(store): the Pointer version visits TypeExpression before name when
    // !IsNameFirst. A fixed shape cannot express that. Decided together with
    // where JSDoc lives (store-ast-design-20260922.md section 7).
    JSDocParameterOrPropertyTag: ["TagName", "name", "IsBracketed", "TypeExpression", "IsNameFirst", "Comment"],
};

// Kinds removed from a role table although the member exists, because the
// Pointer accessor of the same name does not return it.
const roleOverrides: Record<string, string[]> = {
    // (*ast.Node).Expression panics on these kinds.
    Expression: ["DefaultClause", "TypeParameter", "SyntheticReferenceExpression"],
    // (*ast.Node).Body reads BodyBase, which ClassStaticBlockDeclaration does not embed.
    Body: ["ClassStaticBlockDeclaration"],
    // (*ast.Node).Type has no case for JSDocVariadicType.
    Type: ["JSDocVariadicType"],
    // (*ast.Node).Text panics on JsxText.
    Text: ["JsxText"],
};

// Definitions whose single text member lives in the header (section 5 of the
// implementation instructions), not in the payload.
const headerTextDefinitions = new Set(["Identifier", "PrivateIdentifier"]);

// Roles the equivalence test compares against the Pointer method of the same
// name. Text is compared on Identifier and PrivateIdentifier as well.
const testedRoles = ["Name", "Expression", "Type", "Initializer", "Body", "Text", "Modifiers"];

// ────────────────────────────────────────────────────────────────────────────
// Schema to slots
// ────────────────────────────────────────────────────────────────────────────

type SlotClass = "child" | "list" | "text" | "bool" | "tokenFlags" | "kind";

const slotWords: Record<SlotClass, number> = { child: 1, list: 1, text: 2, bool: 1, tokenFlags: 1, kind: 1 };

interface Slot {
    member: MemberInfo;
    /** Capitalized member name: the accessor name. */
    name: string;
    class: SlotClass;
    /** First payload word. */
    word: number;
}

interface KindRef {
    name: string;
    value: number;
}

interface Definition {
    node: NodeType;
    name: string;
    kinds: KindRef[];
    slots: Slot[];
    words: number;
    /** Identifier / PrivateIdentifier: text in the header, no payload. */
    headerText: boolean;
    /** Members without a slot, as TODO comments. */
    todos: string[];
}

const problems: string[] = [];

function isPrimitive(type: Type, name: string): boolean {
    return type.kind === "primitive" && type.name === name;
}

type Classification = { slot: SlotClass; } | { header: true; } | { skip: true; } | { todo: string; };

function classify(def: NodeType, m: MemberInfo): Classification {
    if (m.isKindParam() || m.name === "Flags" || m.name === "modifierFlags") return { header: true };
    if (m.goOnly || m.noGo) return { skip: true };
    if (m.isChild()) return { slot: m.listKind ? "list" : "child" };
    const type = m.type;
    if (type.kind === "list" && type.listKind === "raw" && isPrimitive(type.elementType, "string")) {
        return { todo: `${m.name} []string has no slot: where JSDoc lives is undecided (store-ast-design-20260922.md section 5)` };
    }
    if (isPrimitive(type, "string")) {
        return headerTextDefinitions.has(def.name) ? { header: true } : { slot: "text" };
    }
    if (isPrimitive(type, "bool")) return { slot: "bool" };
    if (isPrimitive(type, "TokenFlags")) return { slot: "tokenFlags" };
    if (type.baseKind() === "kind") return { slot: "kind" };
    if (isPrimitive(type, "any")) {
        // SyntheticExpression.Type is a checker type: checker data, like the
        // goOnly members (store-ast-design-20260922.md section 5).
        return { todo: `${m.name} any has no slot: a checker type, kept in a side table` };
    }
    problems.push(`${def.name}.${m.name}: no slot class for type ${JSON.stringify(m.rawType)}`);
    return { skip: true };
}

function orderedMembers(node: NodeType): MemberInfo[] {
    const override = memberOrderOverrides[node.name];
    if (!override) return node.members;
    const listed = override.map(name => {
        const m = node.members.find(m => m.name === name);
        if (!m) problems.push(`${node.name}: override names unknown member ${name}`);
        return m!;
    });
    return [...listed, ...node.members.filter(m => !override.includes(m.name))];
}

const kindValues = new Map<string, number>();
{
    let value = 0;
    for (const element of api.kindElements()) {
        if (element.name) kindValues.set(element.name, value++);
    }
}
if (kindValues.size > 512) {
    throw new Error(`${kindValues.size} kinds do not fit the 512-entry tables`);
}

function kindRef(name: string): KindRef {
    const value = kindValues.get(name);
    if (value === undefined) throw new Error(`unknown kind ${name}`);
    return { name, value };
}

const reservedParams = new Set(["b", "kind", "flags", "pos", "end", "data", "id"]);

function buildDefinition(node: NodeType): Definition {
    const def: Definition = {
        node,
        name: node.name,
        kinds: node.allKinds().map(k => kindRef(k.name)),
        slots: [],
        words: 0,
        headerText: headerTextDefinitions.has(node.name),
        todos: [],
    };
    for (const m of orderedMembers(node)) {
        const c = classify(node, m);
        if ("todo" in c) {
            def.todos.push(c.todo);
            continue;
        }
        if (!("slot" in c)) continue;
        if (reservedParams.has(m.goParamName())) {
            problems.push(`${node.name}.${m.name}: parameter name ${m.goParamName()} is reserved in the constructor`);
        }
        def.slots.push({ member: m, name: api.capitalize(m.name), class: c.slot, word: def.words });
        def.words += slotWords[c.slot];
    }
    if (def.words > 16) {
        problems.push(`${node.name}: ${def.words} payload words do not fit the 16-bit list mask`);
    }
    return def;
}

const definitions = api.nodes().map(buildDefinition);

// A kind may be covered by several definitions (Token covers Identifier and
// the keywords). The one with a payload wins; two with payloads is an error.
const kindDefinition = new Map<number, Definition>();
{
    const candidates = new Map<number, Definition[]>();
    for (const def of definitions) {
        for (const kind of def.kinds) {
            candidates.set(kind.value, [...(candidates.get(kind.value) ?? []), def]);
        }
    }
    const weight = (def: Definition) => def.words * 4 + (def.headerText ? 2 : 0) + (def.node.isMultiKind() ? 0 : 1);
    for (const [value, defs] of candidates) {
        defs.sort((a, b) => weight(b) - weight(a));
        if (defs.length > 1 && (defs[1].words > 0 || defs[1].headerText)) {
            problems.push(`kind ${defs[0].kinds.find(k => k.value === value)!.name} is defined by both ${defs[0].name} and ${defs[1].name}`);
        }
        kindDefinition.set(value, defs[0]);
    }
}

if (problems.length > 0) {
    throw new Error(`cannot generate the Store:\n  ${problems.sort().join("\n  ")}`);
}

/** Kinds with a payload, in Kind order. */
const payloadKinds: { kind: KindRef; def: Definition; }[] = [];
for (const [value, def] of [...kindDefinition].sort((a, b) => a[0] - b[0])) {
    if (def.words > 0) payloadKinds.push({ kind: def.kinds.find(k => k.value === value)!, def });
}

/** Definitions that get a typed view, a constructor and a convert case. */
const viewDefinitions = definitions.filter(def => def.words > 0 || def.headerText);

/** Kinds of a definition, in the order the definition lists them. */
function goKinds(def: Definition): string {
    return def.kinds.map(k => `ast.Kind${k.name}`).join(", ");
}

function isMultiKind(def: Definition): boolean {
    return def.kinds.length > 1;
}

// ── Roles ──

type RoleClass = "child" | "list" | "text";

interface Role {
    name: string;
    class: RoleClass;
    table: string;
    /** kind value → payload word */
    slots: Map<number, number>;
}

const roles: Role[] = [];
const mixedRoles: string[] = [];
{
    const byName = new Map<string, { classes: Set<SlotClass>; defs: Set<Definition>; }>();
    for (const def of viewDefinitions) {
        for (const slot of def.slots) {
            if (slot.class !== "child" && slot.class !== "list" && slot.class !== "text") continue;
            const entry = byName.get(slot.name) ?? { classes: new Set(), defs: new Set() };
            entry.classes.add(slot.class);
            entry.defs.add(def);
            byName.set(slot.name, entry);
        }
    }
    for (const [name, { classes, defs }] of byName) {
        if (defs.size < 2) continue;
        if (classes.size > 1) {
            mixedRoles.push(`${name} (${[...defs].map(d => `${[...classes].find(c => d.slots.some(s => s.name === name && s.class === c))} in ${d.name}`).join(", ")})`);
            continue;
        }
        const role: Role = { name, class: [...classes][0] as RoleClass, table: `${api.uncapitalize(name)}Slot`, slots: new Map() };
        const excluded = new Set(roleOverrides[name] ?? []);
        for (const { kind, def } of payloadKinds) {
            if (excluded.has(kind.name)) continue;
            const slot = def.slots.find(s => s.name === name);
            if (slot) role.slots.set(kind.value, slot.word);
        }
        roles.push(role);
    }
}
for (const name of Object.keys(roleOverrides)) {
    if (!roles.some(r => r.name === name)) throw new Error(`roleOverrides names ${name}, which is not a role`);
}

function role(name: string): Role {
    const r = roles.find(r => r.name === name);
    if (!r) throw new Error(`${name} is not a role`);
    return r;
}

// ────────────────────────────────────────────────────────────────────────────
// Code generation
// ────────────────────────────────────────────────────────────────────────────

class CodeWriter {
    private lines: string[] = [];

    write(line: string = "") {
        this.lines.push(line);
    }

    toString(): string {
        return this.lines.join("\n") + "\n";
    }
}

function slotConst(def: Definition, slot: Slot): string {
    return `${api.uncapitalize(def.name)}${slot.name}Slot`;
}

function goType(slot: Slot): string {
    switch (slot.class) {
        case "child":
            return "Node";
        case "list":
            return "List";
        case "text":
            return "string";
        case "bool":
            return "bool";
        case "tokenFlags":
            return "ast.TokenFlags";
        case "kind":
            return "ast.Kind";
    }
}

/** Constructor parameter type. */
function paramType(slot: Slot): string {
    switch (slot.class) {
        case "child":
            return "NodeRef";
        case "list":
            return "ListRef";
        default:
            return goType(slot);
    }
}

// ── shapes_generated.go ──

function generateShapes(): string {
    const w = new CodeWriter();
    w.write(HEADER);
    w.write();
    w.write("package store");
    w.write();
    w.write(`import ${AST_IMPORT}`);
    w.write();
    w.write("type shape struct {");
    w.write("\tslots    uint8  // payload words in extra");
    w.write("\tlistMask uint16 // bit i: word i holds a list block index");
    w.write("}");
    w.write();
    w.write("var shapes = [512]shape{");
    for (const { kind, def } of payloadKinds) {
        let mask = 0;
        for (const slot of def.slots) {
            if (slot.class === "list") mask |= 1 << slot.word;
        }
        w.write(`\tast.Kind${kind.name}: {${def.words}, 0b${mask.toString(2)}},`);
    }
    w.write("}");
    w.write();
    w.write("// Payload word of the member with that role; 0xFF = the kind does not have");
    w.write("// it. A role is a child, list or text member that two or more definitions");
    w.write("// declare with the same class. Declared with different classes, so not a role:");
    for (const mixed of mixedRoles) {
        w.write(`//   - ${mixed}`);
    }
    w.write("var (");
    for (const r of roles) {
        w.write(`\t${r.table} [512]uint8`);
    }
    w.write(")");
    w.write();
    w.write("func init() {");
    w.write(`\tfor _, t := range []*[512]uint8{${roles.map(r => `&${r.table}`).join(", ")}} {`);
    w.write("\t\tfor i := range t {");
    w.write("\t\t\tt[i] = 0xFF");
    w.write("\t\t}");
    w.write("\t}");
    for (const r of roles) {
        for (const { kind } of payloadKinds) {
            const word = r.slots.get(kind.value);
            if (word !== undefined) w.write(`\t${r.table}[ast.Kind${kind.name}] = ${word}`);
        }
    }
    w.write("}");
    return w.toString();
}

// ── views_generated.go ──

function memberAccessor(def: Definition, slot: Slot): string {
    const index = `int(n.h.data)+${slotConst(def, slot)}`;
    switch (slot.class) {
        case "child":
            return `return n.s.node(NodeRef(n.s.extra[${index}]))`;
        case "list":
            return `return List{n.s, ListRef(n.s.extra[${index}])}`;
        case "text":
            return `return n.s.text(${index})`;
        case "bool":
            return `return n.s.extra[${index}] != 0`;
        case "tokenFlags":
            return `return ast.TokenFlags(n.s.extra[${index}])`;
        case "kind":
            return `return ast.Kind(n.s.extra[${index}])`;
    }
}

function generateViews(): string {
    const w = new CodeWriter();
    w.write(HEADER);
    w.write();
    w.write("package store");
    w.write();
    w.write(`import ${AST_IMPORT}`);
    w.write();
    w.write("// A typed view is the same two words as Node under another type: creating one");
    w.write("// loads nothing, and each accessor reads only its own payload word. Accessors");
    w.write("// have no nil guard (nodes[0] and list block 0 are sentinels) and no kind check");
    w.write("// outside storeChecks. Slot constants are payload words in declaration order.");
    for (const def of viewDefinitions) {
        w.write();
        w.write(`// ${def.name}: ${goKinds(def)}`);
        if (def.slots.length > 0) {
            w.write("const (");
            for (const slot of def.slots) {
                const words = slot.class === "text" ? " // [offset, length]" : "";
                w.write(`\t${slotConst(def, slot)} = ${slot.word}${words}`);
            }
            w.write(")");
            w.write();
        }
        for (const todo of def.todos) {
            w.write(`// TODO(store): ${todo}.`);
        }
        w.write(`type ${def.name} struct {`);
        w.write("\ts *Store");
        w.write("\th *NodeHeader");
        w.write("}");
        w.write();
        w.write(`func (n Node) As${def.name}() ${def.name} {`);
        w.write("\tif storeChecks {");
        if (isMultiKind(def)) {
            w.write(`\t\tn.assertKinds("${def.name}", ${goKinds(def)})`);
        }
        else {
            w.write(`\t\tn.assertKind(${goKinds(def)})`);
        }
        w.write("\t}");
        w.write(`\treturn ${def.name}(n)`);
        w.write("}");
        if (def.headerText) {
            w.write();
            w.write(`func (n ${def.name}) Text() string { return Node(n).identifierText() }`);
        }
        for (const slot of def.slots) {
            w.write();
            w.write(`func (n ${def.name}) ${slot.name}() ${goType(slot)} { ${memberAccessor(def, slot)} }`);
        }
    }

    w.write();
    w.write("// Kind-polymorphic accessors. One static table lookup picks the payload word,");
    w.write("// so the code is the same for every kind: no switch, no jump table. A kind");
    w.write("// without the role returns the nil node, the nil list or the empty string.");
    for (const r of roles) {
        w.write();
        const index = `int(n.h.data)+int(slot)`;
        w.write(`func (n Node) ${r.name}() ${r.class === "child" ? "Node" : r.class === "list" ? "List" : "string"} {`);
        if (r.name === "Text") {
            // Identifier and PrivateIdentifier keep their text in the header.
            w.write("\t// TODO(store): Text is the one role accessor that does not inline (cost");
            w.write("\t// 157, budget 80): identifierText (72) plus text (42) plus the table lookup.");
            w.write("\t// Every call pays a call and its prologue, and the Identifier path, which");
            w.write("\t// hot paths hit repeatedly, cannot be folded into the caller. Left as is for");
            w.write("\t// now (2026-09-22); a hot call site with a known kind uses the typed");
            w.write("\t// Identifier.Text, which inlines. Measure once the Store is wired in, then");
            w.write("\t// decide whether to split it into an inline Identifier path and a slow path.");
            w.write("\tif n.h.kind == ast.KindIdentifier || n.h.kind == ast.KindPrivateIdentifier {");
            w.write("\t\treturn n.identifierText()");
            w.write("\t}");
        }
        w.write(`\tslot := ${r.table}[n.h.kind&511]`);
        w.write("\tif slot == 0xFF {");
        switch (r.class) {
            case "child":
                w.write("\t\treturn n.s.node(0)");
                break;
            case "list":
                w.write("\t\treturn List{n.s, NoListRef}");
                break;
            case "text":
                w.write(`\t\treturn ""`);
                break;
        }
        w.write("\t}");
        switch (r.class) {
            case "child":
                w.write(`\treturn n.s.node(NodeRef(n.s.extra[${index}]))`);
                break;
            case "list":
                w.write(`\treturn List{n.s, ListRef(n.s.extra[${index}])}`);
                break;
            case "text":
                w.write(`\treturn n.s.text(${index})`);
                break;
        }
        w.write("}");
    }
    return w.toString();
}

// ── foreach_generated.go ──

function generateForEachChild(): string {
    const w = new CodeWriter();
    w.write(HEADER);
    w.write();
    w.write("package store");
    w.write();
    w.write(`import ${AST_IMPORT}`);
    w.write();
    w.write("// The cases are in Kind order and cover every kind that has a payload.");
    w.write("func (n Node) ForEachChild(v Visitor) bool {");
    w.write("\tswitch n.h.kind {");
    for (const { kind, def } of payloadKinds) {
        if (!def.slots.some(s => s.class === "child" || s.class === "list")) continue;
        w.write(`\tcase ast.Kind${kind.name}:`);
        w.write(`\t\treturn forEachChild${def.name}(n, v)`);
    }
    w.write("\t}");
    w.write("\treturn false");
    w.write("}");
    const seen = new Set<Definition>();
    for (const { def } of payloadKinds) {
        if (seen.has(def) || !def.slots.some(s => s.class === "child" || s.class === "list")) continue;
        seen.add(def);
        w.write();
        w.write(`func forEachChild${def.name}(n Node, v Visitor) bool {`);
        w.write("\ts, data := n.s, int(n.h.data)");
        for (const slot of def.slots) {
            if (slot.class === "child") {
                w.write(`\tif ref := NodeRef(s.extra[data+${slot.word}]); ref != NoNodeRef && v(s.node(ref)) { // ${slot.name}`);
                w.write("\t\treturn true");
                w.write("\t}");
            }
            else if (slot.class === "list") {
                w.write(`\tif at := ListRef(s.extra[data+${slot.word}]); at != NoListRef && visitList(s, at, v) { // ${slot.name}`);
                w.write("\t\treturn true");
                w.write("\t}");
            }
        }
        w.write("\treturn false");
        w.write("}");
    }
    return w.toString();
}

// ── builder_generated.go ──

function generateBuilder(): string {
    const w = new CodeWriter();
    w.write(HEADER);
    w.write();
    w.write("package store");
    w.write();
    w.write(`import ${AST_IMPORT}`);
    w.write();
    w.write("// One constructor per definition, parameters in payload order. Children must");
    w.write("// already exist (post-order); the constructor writes their parent. A");
    w.write("// definition with several kinds takes the kind first.");
    for (const def of viewDefinitions) {
        const params = ["flags ast.NodeFlags", "pos, end int32"];
        if (isMultiKind(def)) params.unshift("kind ast.Kind");
        if (def.headerText) params.push("text string");
        for (const slot of def.slots) {
            params.push(`${slot.member.goParamName()} ${paramType(slot)}`);
        }
        const kind = isMultiKind(def) ? "kind" : goKinds(def);
        w.write();
        w.write(`func (b *Builder) New${def.name}(${params.join(", ")}) NodeRef {`);
        if (def.headerText) {
            w.write(`\treturn b.header(${kind}, flags, 0, pos, end, b.identifierData(end, text))`);
            w.write("}");
            continue;
        }
        const words: string[] = [];
        for (const slot of def.slots) {
            const p = slot.member.goParamName();
            switch (slot.class) {
                case "child":
                    words.push(`uint32(${p})`);
                    break;
                case "list":
                    words.push(`uint32(${p})`);
                    break;
                case "text":
                    w.write(`\t${p}Off, ${p}Len := b.textWords(end, ${p})`);
                    words.push(`${p}Off`, `${p}Len`);
                    break;
                case "bool":
                    words.push(`boolWord(${p})`);
                    break;
                case "tokenFlags":
                case "kind":
                    words.push(`uint32(${p})`);
                    break;
            }
        }
        w.write("\tdata := uint32(len(b.s.extra))");
        w.write(`\tb.s.extra = append(b.s.extra, ${words.join(", ")})`);
        const modifiers = def.slots.find(s => s.name === "Modifiers" && s.class === "list");
        const mod = modifiers ? `b.modifierFlags(${modifiers.member.goParamName()})` : "0";
        const children = def.slots.filter(s => s.class === "child" || s.class === "list");
        if (children.length === 0) {
            w.write(`\treturn b.header(${kind}, flags, ${mod}, pos, end, data)`);
            w.write("}");
            continue;
        }
        w.write(`\tid := b.header(${kind}, flags, ${mod}, pos, end, data)`);
        for (const slot of children) {
            const p = slot.member.goParamName();
            w.write(`\tb.${slot.class === "child" ? "adopt" : "adoptList"}(${p}, id)`);
        }
        w.write("\treturn id");
        w.write("}");
    }
    return w.toString();
}

// ── convert/convert_generated.go ──

/** Go expression reading the member of the typed Pointer struct v. */
function pointerRead(v: string, slot: Slot): string {
    const m = slot.member;
    return m.private ? `${v}.${slot.name}()` : `${v}.${m.name}`;
}

function convertArg(slot: Slot): string {
    const read = pointerRead("d", slot);
    switch (slot.class) {
        case "child":
            return `c.node(${read})`;
        case "list":
            switch (slot.member.listKind) {
                case "ModifierList":
                    return `c.modifiers(${read})`;
                case "raw":
                    return `c.raw(${read})`;
                default:
                    return `c.list(${read})`;
            }
        case "kind":
            return `ast.Kind(${read})`;
        default:
            return read;
    }
}

function generateConvert(): string {
    const w = new CodeWriter();
    w.write(HEADER);
    w.write();
    w.write("package convert");
    w.write();
    w.write("import (");
    w.write(`\t${AST_IMPORT}`);
    w.write(`\t${STORE_IMPORT}`);
    w.write(")");
    w.write();
    w.write("// Convert builds a Store from a Pointer AST in post-order. It follows exactly");
    w.write("// the children that the Pointer ForEachChild visits, so JSDoc is not converted.");
    w.write("func Convert(file *ast.SourceFile, fileIndex uint32) *store.Store {");
    w.write("\tc := &converter{b: store.NewBuilder(file.Text(), fileIndex)}");
    w.write("\tc.node(file.AsNode())");
    w.write("\treturn c.b.Finish()");
    w.write("}");
    w.write();
    w.write("type converter struct {");
    w.write("\tb     *store.Builder");
    w.write("\telems []store.NodeRef // stack of the elements of the lists under construction");
    w.write("}");
    w.write();
    w.write("func (c *converter) elements(pos, end int32, nodes []*ast.Node) store.ListRef {");
    w.write("\tmark := len(c.elems)");
    w.write("\tfor _, n := range nodes {");
    w.write("\t\tc.elems = append(c.elems, c.node(n))");
    w.write("\t}");
    w.write("\tat := c.b.List(pos, end, c.elems[mark:])");
    w.write("\tc.elems = c.elems[:mark]");
    w.write("\treturn at");
    w.write("}");
    w.write();
    w.write("func (c *converter) list(l *ast.NodeList) store.ListRef {");
    w.write("\tif l == nil {");
    w.write("\t\treturn store.NoListRef");
    w.write("\t}");
    w.write("\treturn c.elements(int32(l.Pos()), int32(l.End()), l.Nodes)");
    w.write("}");
    w.write();
    w.write("func (c *converter) modifiers(l *ast.ModifierList) store.ListRef {");
    w.write("\tif l == nil {");
    w.write("\t\treturn store.NoListRef");
    w.write("\t}");
    w.write("\treturn c.list(&l.NodeList)");
    w.write("}");
    w.write();
    w.write("// A raw list has no Loc of its own.");
    w.write("func (c *converter) raw(nodes []*ast.Node) store.ListRef {");
    w.write("\tif nodes == nil {");
    w.write("\t\treturn store.NoListRef");
    w.write("\t}");
    w.write("\treturn c.elements(0, 0, nodes)");
    w.write("}");
    w.write();
    w.write("// node converts in post-order: the arguments of a constructor are evaluated");
    w.write("// left to right, so the children exist, in member order, before their parent.");
    w.write("func (c *converter) node(n *ast.Node) store.NodeRef {");
    w.write("\tif n == nil {");
    w.write("\t\treturn store.NoNodeRef");
    w.write("\t}");
    w.write("\tpos, end := int32(n.Pos()), int32(n.End())");
    w.write("\tswitch n.Kind {");
    for (const def of viewDefinitions) {
        w.write(`\tcase ${goKinds(def)}:`);
        w.write(`\t\td := n.As${def.name}()`);
        const args = ["n.Flags", "pos", "end"];
        if (isMultiKind(def)) args.unshift("n.Kind");
        for (const slot of def.slots) args.push(convertArg(slot));
        if (def.headerText) args.push("d.Text");
        w.write(`\t\treturn c.b.New${def.name}(${args.join(", ")})`);
    }
    w.write("\t}");
    w.write("\treturn c.b.NewToken(n.Kind, n.Flags, pos, end)");
    w.write("}");
    return w.toString();
}

// ── storetest/equivalence_generated.go ──

function generateEquivalenceTest(): string {
    const w = new CodeWriter();
    let members = 0;
    let roleChecks = 0;
    w.write(HEADER);
    w.write();
    w.write("package storetest");
    w.write();
    w.write("import (");
    w.write(`\t${AST_IMPORT}`);
    w.write(`\t${STORE_IMPORT}`);
    w.write(")");
    w.write();
    w.write("// compareMembers compares every member of the definition of p.Kind through the");
    w.write("// typed view: a child by kind and position, a list by length, position and");
    w.write("// elements, a text by value, a bool, TokenFlags or kind by value.");
    w.write("func compareMembers(m *comparer, p *ast.Node, n store.Node) {");
    w.write("\tswitch p.Kind {");
    for (const def of viewDefinitions) {
        w.write(`\tcase ${goKinds(def)}:`);
        w.write(`\t\tpv, sv := p.As${def.name}(), n.As${def.name}()`);
        if (def.headerText) {
            w.write(`\t\tif pv.Text != sv.Text() {`);
            w.write(`\t\t\tm.add(p, "${def.name}.Text")`);
            w.write("\t\t}");
            members++;
        }
        for (const slot of def.slots) {
            const label = `"${def.name}.${slot.name}"`;
            const read = pointerRead("pv", slot);
            members++;
            switch (slot.class) {
                case "child":
                    w.write(`\t\tm.node(${label}, p, ${read}, sv.${slot.name}())`);
                    break;
                case "list":
                    switch (slot.member.listKind) {
                        case "ModifierList":
                            w.write(`\t\tm.modifiers(${label}, p, ${read}, sv.${slot.name}())`);
                            break;
                        case "raw":
                            w.write(`\t\tm.raw(${label}, p, ${read}, sv.${slot.name}())`);
                            break;
                        default:
                            w.write(`\t\tm.list(${label}, p, ${read}, sv.${slot.name}())`);
                    }
                    break;
                case "kind":
                    w.write(`\t\tif ast.Kind(${read}) != sv.${slot.name}() {`);
                    w.write(`\t\t\tm.add(p, ${label})`);
                    w.write("\t\t}");
                    break;
                default:
                    w.write(`\t\tif ${read} != sv.${slot.name}() {`);
                    w.write(`\t\t\tm.add(p, ${label})`);
                    w.write("\t\t}");
            }
        }
    }
    w.write("\t}");
    w.write("}");
    w.write();
    w.write("// compareRoles compares the role accessors with the Pointer methods of the same");
    w.write("// name, on the kinds whose role table is not 0xFF. A Pointer method that panics");
    w.write("// on a kind is reported by guard and belongs in the generator's roleOverrides.");
    w.write("func compareRoles(m *comparer, p *ast.Node, n store.Node) {");
    w.write("\tswitch p.Kind {");
    for (const { kind, def } of [...payloadKinds, ...definitions.filter(d => d.headerText).map(d => ({ kind: d.kinds[0], def: d }))]) {
        const lines: string[] = [];
        for (const name of testedRoles) {
            const r = role(name);
            const present = r.slots.has(kind.value) || (name === "Text" && def.headerText);
            if (!present) continue;
            roleChecks++;
            const label = `"${name}"`;
            switch (name) {
                case "Text":
                    lines.push(`\t\tm.guard(p, ${label}, func() {`, `\t\t\tif p.Text() != n.Text() {`, `\t\t\t\tm.add(p, ${label})`, "\t\t\t}", "\t\t})");
                    break;
                case "Modifiers":
                    lines.push(`\t\tm.guard(p, ${label}, func() { m.modifiers(${label}, p, p.Modifiers(), n.Modifiers()) })`);
                    break;
                default:
                    lines.push(`\t\tm.guard(p, ${label}, func() { m.node(${label}, p, p.${name}(), n.${name}()) })`);
            }
        }
        if (lines.length === 0) continue;
        w.write(`\tcase ast.Kind${kind.name}:`);
        for (const line of lines) w.write(line);
    }
    w.write("\t}");
    w.write("}");
    w.write();
    w.write("// Comparisons per node kind, for the verification report.");
    w.write("const (");
    w.write(`\tComparedMembers = ${members}`);
    w.write(`\tComparedRoles   = ${roleChecks}`);
    w.write(")");
    return w.toString();
}

// ────────────────────────────────────────────────────────────────────────────
// Write output
// ────────────────────────────────────────────────────────────────────────────

function writeAndFormat(filePath: string, content: string) {
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    fs.writeFileSync(filePath, content);
    xSync("dprint", ["fmt", filePath], {
        throwOnError: true,
        nodeOptions: { stdio: "inherit", cwd: ROOT },
    });
    console.log(`Wrote ${filePath}`);
}

export default function main() {
    console.log("Generating Go Store AST code...");
    writeAndFormat(path.join(OUT_DIR, "shapes_generated.go"), generateShapes());
    writeAndFormat(path.join(OUT_DIR, "views_generated.go"), generateViews());
    writeAndFormat(path.join(OUT_DIR, "foreach_generated.go"), generateForEachChild());
    writeAndFormat(path.join(OUT_DIR, "builder_generated.go"), generateBuilder());
    writeAndFormat(path.join(OUT_DIR, "convert/convert_generated.go"), generateConvert());
    writeAndFormat(path.join(OUT_DIR, "storetest/equivalence_generated.go"), generateEquivalenceTest());
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
    main();
}
